extension.ts, package.json, src/mode/mode_insert.ts, src/mode/mode_visual.ts
Added a few keys and improved mode switching.
=> assorted fixes

extension.ts, package.json, src/mode/mode_normal.ts, test/mode/mode_normal.test.ts, tsd.json
Small PR that adds support for `>>` and `<<`.
=> Support `<<` and `>>`

src/mode/modeNormal.ts
After getting normal mode (e.g. from insert mode to normal mode), the cursor position should be moved to 1 left.
=> move cursor position after getting normal mode

gulpfile.js, package.json, src/cmd_line/commands/quit.ts, src/cmd_line/commands/write.ts, src/cmd_line/main.ts, src/cmd_line/node.ts, src/cmd_line/subparser.ts, src/cursor.ts, src/error.ts, src/mode/mode.ts, src/mode/modeHandler.ts, src/mode/modeInsert.ts, src/mode/modeNormal.ts, src/mode/modeVisual.ts, src/textEditor.ts, test/cmd_line/lexer.test.ts, test/cmd_line/subparser.quit.test.ts, test/cmd_line/subparser.test.ts, test/cursor.test.ts, test/error.test.ts, test/extension.test.ts, test/index.ts, test/mode/modeHandler.test.ts, test/mode/modeNormal.test.ts, test/textEditor.test.ts, tslint.json
* add gulp task to trim-whitespace
* updating source with trailing whitespace trimmed. 
* update tslint to check against trailing whitespace
=> gulp: add trim-whitespace task

README.md, src/cursor.ts, src/mode/modeNormal.ts, test/cursor.test.ts
Add navigation commands support:
- 'gg': go to fist line, on first non-blank character
- 'G': go to last line, on first non-blank character
=> Add commands support for 'gg' and 'G'

extension.ts, package.json, src/configuration.ts, src/keyboard.ts, src/mode/modeHandler.ts, test/keyboard.test.ts
Uses a `vim.keyboardLayout` setting to determine which keyboart layout to use; defaults to letting the key trhough as is.
=> map keys from US keyboard to other layouts

src/cursor/caret.ts, src/cursor/cursor.ts, src/mode/modeInsert.ts, src/mode/modeNormal.ts, test/caret.test.ts, test/cursor.test.ts, test/mode/modeInsert.test.ts, test/testUtils.ts, test/textEditor.test.ts
fix line end determination for a, A, $
=> fix line end determination for a, A, $

src/mode/modeNormal.ts
after merged Refactor motion. #87, this process was discarded.
=> fix cursor position after entering command mode (again)

package.json, src/mode/modeNormal.ts
Small change to invoke deleteRight command when you press x.
BTW, are there any tests around the normal mode keys handling. I admit I'm still looking around and trying to add the small things that I feel productive with.
=> Delete Right when user presses x

extension.ts, package.json, src/keyboard.ts
Solution for #128 
This also adds support for binding and translating the ```oem_102``` key.
Note: This only works when building the vscode from source, but it should be available in their next release.
=> Add Swedish keyboard layout

test/testUtils.ts
Waiting asynchronously for the workspace test files to get written helps to get rid of those unexpected `cannot open file` failures on test runs.
=> Wait for test files to get written

README.md, src/mode/modeNormal.ts, src/motion/position.ts, test/mode/modeNormal.test.ts
Implemented `dw`, `dW`, `db`, `dB`, `de`, `dE` and some tests. 
Not the best way of handling `d` motions (we need a specific case for each key combo), but it _fits_ with the current key handling API.
=> d{motion} support

extension.ts, src/cmd_line/commands/write.ts, src/cmd_line/main.ts, src/cmd_line/node.ts, src/mode/modeHandler.ts, src/mode/modeNormal.ts
=> Commands can write to status bar

README.md, src/mode/mode.ts, src/mode/modeHandler.ts, src/mode/modeInsert.ts, src/mode/modeNormal.ts, src/mode/modeVisual.ts, src/motion/motion.ts, src/motion/position.ts, test/mode/modeNormal.test.ts, test/testUtils.ts
Adds commands `cw`, `ciw`, `caw`, `C`, `ge` and `gE`. 
Fixes #179. 
Had to rework a bit how the mode handler activates modes, as e.g. `ciw` activated insert mode.
=> c commands and ge motions

extension.ts, package.json, src/mode/modeNormal.ts
* fixes #159 
* opens vscode's search panel when '/' pressed in command mode
=> Search '/' in Command Mode

src/mode/modeNormal.ts
Just correct the behavior of "/" to search the current file instead of finding in the whole project.
=> Fix issue / key doesn't search current file

src/mode/modeNormal.ts, src/motion/motion.ts, test/mode/modeNormal.test.ts
- This fixes `dw` so that the cursor ends in the correct position.
Closes https://github.com/VSCodeVim/Vim/issues/199
=> Fixes Issue with Cursor Position After 'dw'

src/motion/motion.ts
- By having `redraw` enforce cursor position, we were double
moving because both `redraw` (via `Motion.changedMode`) and
`handleActivationKey` were moving the cursor left. This makes
it so `redraw` is not responsible for enforcing the cursor
position. Instead, position enforcement is handled only when
the cursor may have been moved externally (ie via the mouse).
Closes https://github.com/VSCodeVim/Vim/issues/201
=> Fixes Incorrect Cursor Position after Transition into Normal Mode

.travis.yml, package.json, src/mode/modeNormal.ts, src/mode/modeVisual.ts, src/operator/put.ts, src/textEditor.ts, test/operator/put.test.ts, test/textEditor.test.ts, typings.json
Hello, I have added two things:
1. Support for copying to the system clipboard
2. A basic version of the put command that pastes from the system clipboard
When first looking around I found [this issue](https://github.com/Microsoft/vscode/issues/217) on the vscode repository about supporting copy/paste operations for extensions. I have followed the advice in that issue and included the [copy-paste](https://www.npmjs.com/package/copy-paste) npm package to do  copy/paste.
Be great to hear what everyone thinks 👍
=> Support for copy and p command

README.md, package.json, src/mode/commands.ts, src/mode/mode.ts, src/mode/modeHandler.ts, src/mode/modeInsert.ts, src/mode/modeNormal.ts, src/mode/modeVisual.ts, test/mode/modeInsert.test.ts, test/mode/modeNormal.test.ts, test/mode/modeVisual.test.ts
Support is limited but nothing should be changed for anything not related to rebinding keys using user configuration. 
Partial fix for #185 and #128.
=> Added basic support for rebinding keys.

src/mode/commands.ts, src/mode/modeNormal.ts
Executes in normal mode:
`zc` - editor.fold
`zo` - editor.unfold
`zC` - editor.foldAll
`zO` - editor.unfoldAll
=> Added basic fold commands zc, zo, zC, zO.

src/mode/modeHandler.ts, src/mode/modeVisual.ts, src/operator/yank.ts, src/textEditor.ts
This pull request add the ability to yank selected text in Visual Mode. The selected text will be yanked into the system clipboard. So it is the equivalent of doing a copy. After a successful yank the mode will be changed to Normal.
=> Add yank support for Visual mode

.vscode/launch.json, extension.ts, src/mode/modeHandler.ts, src/mode/modeNormal.ts, src/operator/put.ts, src/textEditor.ts, test/mode/modeInsert.test.ts, test/mode/modeNormal.test.ts, test/operator/put.test.ts, test/testUtils.ts
This is much nicer because now it's an end-to-end test of the Vim interface. Also, it's much easier to test that commands allow us to enter/leave different modes.
=> Rewrite Normal Mode tests to use the ModeHandler interface.

extension.ts, test/mode/modeNormal.test.ts
Continuing from https://github.com/VSCodeVim/Vim/pull/230
This actually caught a bug with how we were doing tests before. The `i` in `ciw` when running the extension forces you to go into insert mode, but the test incorrectly passed anyways. Commented out those tests for now.
=> Rewrite normal mode tests.

package.json, src/operator/put.ts, src/register/register.ts, src/textEditor.ts, test/mode/modeNormal.test.ts, test/operator/put.test.ts, test/textEditor.test.ts, typings.json
Hoping to kill 2 birds with one stone here:
1. Remove that dumb copy-paste dependency that (I think) caused some intermittent test failures.
2. Begin to implement Registers with a simple enough API.
This has the downside of no longer yanking to the clipboard, but many other implementations of Vim don't yank to clipboard either, including... uh... Vim itself. Cmd-C or Ctrl-C still work, too, so I'm not concerned.
=> Add rudimentary register implementation.

src/actions/actions.ts, src/motion/position.ts
So tempting to name this branch `a-dd-cc-yy`.
=> Add cc/yy/dd.

README.md, src/actions/actions.ts, src/configuration/commandKeyMap.ts, test/mode/modeNormal.test.ts
This is one of the keybindings I use quite often and felt was missing
=> Add s keybinding

src/actions/actions.ts, src/mode/modeHandler.ts
Why does w have so many special cases?
=> Move word special case to appropriate place.

src/actions/actions.ts, src/mode/modeHandler.ts, src/motion/position.ts, src/register/register.ts, src/textEditor.ts, test/mode/modeNormal.test.ts, test/mode/modeVisual.test.ts, test/operator/put.test.ts, test/textEditor.test.ts
Vim does this weird thing where it allows you to select and delete the newline character, which it places 1 past the last character in the line (it looks like a space). Properly handling this character makes some visual mode idiosyncrasies work. It also makes Visual Line mode work a lot better.
=> Fix vims wonky visual eol behavior

src/actions/actions.ts, src/mode/modeHandler.ts, src/motion/position.ts, test/mode/modeNormal.test.ts
Special thanks to @tienshiao for providing the initial implementation, part of which I stole :)
=> Add f, F, t and T motions

src/mode/modeHandler.ts, test/mode/modeHandler.test.ts
Added some simple tests for this and moved it out of the hot path as it's something that only happens during mode changes.
=> Use vscode built in support for block cursors

src/actions/actions.ts, src/mode/modeHandler.ts
* Motions now just return a single position - or at worse a 3 tuple of start, end and (unfortunately) register mode
* Special case motion handling in modeHandler. This greatly simplifies the core loop. I was trying to be too clever before by not special casing motions before.
=> Refactor motions

src/actions/actions.ts, src/mode/modeHandler.ts
This makes . work with actions such as `cawasdf<esc>` and even the extra-tricky `d/blah<esc>`. 
. is actually pretty solid now. Now I just need to do repeated actions and then my work here is done. 😉
=> Refactor dot

extension.ts, src/actions/actions.ts, src/mode/modeHandler.ts, test/mode/modeHandler.test.ts
Clicking should move the cursor, and selecting should cause you to go into visual mode.
It's hard to do this perfectly with the current state (and/or my understanding) of the VSCode API, but this solution works 99% of the time.
=> Select into visual mode

test/mode/modeNormal.test.ts, test/testSimplifier.ts, test/testUtils.ts
Hi I've had a first crack at #256.
I'm new to typescript/javascript/git/github so feel free to tell me how to improve or change this to what you have in mind.
I've added an extra optional **endMode**: parameter so we can check the final mode.
```typescript
+    newTest("Can handle 'caw' on blanks",
+        {
+            start: ['text   tex|t'],
+            keysPressed: '^lllllcaw',
+            end: ['text|'],
+            endMode: ModeName.Insert
+        }
+    );
```
Here is a code snippet which will make entering tests easier. Activate with 'newt':
```typescript
"Add new test": {
"prefix": "newt",
"body": [
"newTest(\"$1\",",
"	{",
"		start: ['$2'],",
"		keysPressed: '$3',",
"		end: ['$4'],",
"		//endMode: ModeName.Insert",
"	}",
");",
"$5"
],
"description": "Create a new test"
} …
```
=> Add simpler test mechanism and convert some tests

src/actions/actions.ts, test/mode/modeVisualLine.test.ts
Convert selected range to Uppercase is an often-used command.
The code is well designed so it's easy enough to add new commands support. The only catch is all commands are implemented inside a single file, which makes it lack of categorization and readability, any ideas to refactor it?
=> Add support for 'U' uppercase

src/actions/actions.ts, src/mode/modeHandler.ts, test/mode/modeVisualLine.test.ts
=> Uppercase support

src/actions/actions.ts
Code formatting requires language mode detection. In current test infrastructure, we just create a temp file with no extension, there is no way for VS Code to guess what's the correct language. We should add some test files (like js files, cs files, etc) and launch them directly instead of creating temp files in some cases related to Language Mode. This can be done later with a separate PR.
=> Add format code support. Fix #308.

test/mode/modeVisualLine.test.ts, test/testUtils.ts
When we format code, change code indentation, the final output relies on TextEditorOptions like `tabSize` and `insertSpaces`. Here we allow changing the options in test cases to keep alignment.
=> Align TextEditorOptions between test code and workspace

src/actions/actions.ts, src/mode/modeHandler.ts
Now search is more organized, shorter, wraps around the document, and highlights all matches!
=> Refactor search

extension.ts, package.json
Since VS Code treats ctrl keys as modifiers, all modifiers related keys need be registered in contribution. Here I just register them then we have all related functionalities back
1. `ctrl-b`
2. `ctrl-f`
3. `ctrl-r`
=> Bring Ctrl keys back

extension.ts, package.json, src/actions/actions.ts
Leverage VS Code TabGroup to implement Windows management. Mark it as Work in progress as we still have no key mapping and it will still people's Ctrl+w on Windows. Besides, VS Code treats Ctrl as modifiers but not keys, so you must press `ctrl+w` first then `hjkl` so the experience is somewhat not smooth.
=> [WIP]: Switch Window

src/actions/actions.ts, src/register/register.ts, test/mode/normalModeTests/commands.test.ts
Original `cc` behaviour is not the same as Vim. When you trigger `cc` in Vim with below content,
```
one
|two
three
```
You will get
```
one
|
three
```
However, what we get in VSCodeVim is
```
one
|three
```
I suppose it's not a correct way of `cc` and it's caused by treating `cc` as `LineWise`. Now I add numeric support and set it as `CharacterWise` to fix this problem.
=> Add Ncc support and revise cc behavior

src/actions/actions.ts, test/mode/normalModeTests/commands.test.ts
Delete from the cursor position to the end of the line and [count]-1 more lines [into register x], and start insert.
=> Support `C`

package.json, src/actions/actions.ts, src/history/historyTracker.ts, src/mode/modeHandler.ts, src/motion/position.ts, src/textEditor.ts, test/mode/modeNormal.test.ts, test/testSimplifier.ts
Correctly implement `u` and `<c-r>`!!!
=> Manual history tracking

test/testUtils.ts
`workbench.files.action.closeAllFiles` is deprecated and we should use `workbench.action.closeAllEditors ` instead, which is already invoked before.
This is just test code so it won't block any user as we are using the latest version of VS Code to develop. But if it's an API we are using in production code, I don't know how we can avoid breaking users using old version of VS Code.
=> `workbench.files.action.closeAllFiles` is deprecated.

tsconfig.json
Firstly ignore `.vscode-test` folder, otherwise it will slow down the auto-compilation. Secondly as we set `noLib` as `true` and we are using ES6 most of the time (currently we don't have any ES7 syntax yet), so I add es6 lib file to it.
=> Fix TS2318 and ignore .vscode-test folder

src/actions/actions.ts, src/mode/modeHandler.ts
As noted in https://github.com/VSCodeVim/Vim/issues/416, ctrl+b should be upward, ctrl+f should be downward.
=> Fix ctrl+b, ctrl+f

gulpfile.js, package.json, src/actions/actions.ts
Here's how it works:
1) `npm postinstall` script (which auto-runs after npm install) will run `gulp init`
2) `gulp init` will run `typings install` and once that is finished we manually modify the `index.d.ts` to include the vscode definitions.
Somewhat of a hack but it works.
=> Include vscode typings

src/actions/actions.ts, src/motion/position.ts, test/mode/modeNormal.test.ts
Since #369 is out there for a while so I'd like to give it a quick fix.
=> Fix#369. `dw` eats EOF.

ROADMAP.md, extension.ts, package.json, src/actions/actions.ts, src/mode/modeHandler.ts
Fix #214. Since currently we don't have VS Code Screen Line support, we simply use `20` as the half window size, but users can configure `vim.scroll` to override this setting the same as Vim.
=> Ctrl+U and Ctrl+D

extension.ts, package.json, src/actions/actions.ts, src/cmd_line/commands/substitute.ts, src/cmd_line/commands/tab.ts, src/cmd_line/lexer.ts, src/cmd_line/main.ts, src/cmd_line/parser.ts, src/cmd_line/scanner.ts, src/cmd_line/subparsers/substitute.ts, src/cmd_line/subparsers/tab.ts, src/configuration/keyboard.ts, src/history/historyTracker.ts, src/mode/modeHandler.ts, src/motion/position.ts, src/textEditor.ts, test/mode/modeInsert.test.ts, test/mode/modeNormal.test.ts, test/testSimplifier.ts, test/testUtils.ts, tsconfig.json
Woo woo!
This actually fixed a couple of bugs.. 😲
=> Use TypeScript 2.0 and use strictNullChecks.

package.json
No existing issue that I can find, happy to open one if that helps.
=> Fix spec for otherModesKeyBindings to match insert

src/actions/actions.ts, src/textEditor.ts, test/mode/modeNormal.test.ts
1. Fix #407.
2. Support [p, [p, gp and gP and have all features covered with test cases.
=> [p, [p, gp and gP

src/textEditor.ts, test/mode/modeNormal.test.ts
We were reading TextEditor options from configuration but there are some drawbacks:
1. We didn't monitor the configuration change (not sure if there is any event exposed)
2. VS Code puts a copy of the text editor related configuration in each Text Editor object and there is no bidirectional between them. If people change the configuration file, every copy of text editor option will be reloaded but if we change `vscode.window.activeTextEditor.options` through API on the fly, it's not synced back to `vscode.workspace.getConfiguration("editor")`. It does make sense because `vscode.workspace.getConfiguration("editor")` is likely representing the state of the configuration file.
Here I …
=> Read TextEditor options from active editor

extension.ts
Two impoartant things to note here:
1. We are handing `type` events **asynchronously**, in which case, `default:replacePreviousChar` might be executed before our customized `type` event. When we type in CJK characters, we are typing English characters firstly then replace them with the desired CJK character/s. If the `replacePreviousChar` happens before its corresponding `type` event, we are running into chaos.
2. We are maintaining `cursorPosition` in `vimState` and we will leverage this state to implement dot repeat somehow. However, when we perform `type` then `replacePreviousChar`, it will ruin our `cursorPosition` maintaining. So we should always update the cusor info after …
=> Fix #341 CJK Problem.

src/actions/actions.ts
Looks like this was accidentally removed in #445
=> Add back missing control-c registration

src/cmd_line/commands/file.ts, src/cmd_line/subparser.ts, src/cmd_line/subparsers/file.ts
Support `:vsp`, `:vne` and `:vnew`.
This feature is limited to VS Code's group editors, which only support 3 groups at most. Besides, all horizontal splitting commands wont' work in VS Code
=> Open file in new window.

ROADMAP.md, extension.ts, package.json, src/actions/actions.ts, test/mode/modeInsert.test.ts
This deletes backwards, and is for some reason one of my most commonly
used keyboard shortcuts.
Fixes #452
=> Add support for ctrl+w in insert mode

ROADMAP.md, src/actions/actions.ts, src/matching/matcher.ts, src/motion/position.ts, test/mode/modeNormal.test.ts
This allows for e.g. 'ci(' and 'da<' commands.
Fixes #449
=> Implement additional text object commands

gulpfile.js, package.json, test/mode/modeNormal.test.ts, test/tslint.json
This adds a test-specific tslint.json that allows for unused variables in tests. I verified manually.
NOTE: I'm a total gulp (and node) noob. I followed https://github.com/gulpjs/gulp/blob/master/docs/recipes/using-multiple-sources-in-one-task.md for how to get different behavior from multiple sources, but it feels silly to pull in the dependency just for this. LMK if there's a better way.
Fixes #379
=> Add test-specific tslint

src/actions/actions.ts, src/motion/position.ts
Since this configuration is not accessible in `vscode 1.0.0`, we can't write test cases for it currently. So I just tested manually for now. A proper workaround is adding a test folder for testing (mentioned this before with @johnfn ) or waiting for VS Code's July release.
=> FixTabStops

.vscode/settings.json, src/actions/actions.ts, src/mode/modeHandler.ts, src/motion/position.ts, test/mode/modeNormal.test.ts
It's always a pleasant thing when a change that seems tricky ends up being very simple. 😃 
Fixes a bug I promised @sectioneight I'd get to where ci{ when you're not inside {} would cause you to switch into insert mode. Also fixes an old bug where dtx when x couldn't be found would delete a character.
=> Add support for failed motions

extension.ts
Our extension starts in normal mode but it doesn't change the cursor until you move it either by command or click. The fix is initializing mode handler for active text editor once it starts up.
=> Initialize mode and cursor after startup

src/actions/actions.ts, src/motion/position.ts, test/mode/modeNormal.test.ts
Prior to this commit, we would naively search for the previous e.g. "{"
character when you wanted to "ci{".
However, if you were inside two levels of nesting:
```
one {
two {}
// cursor here
}
```
Then the backwards search would take you to the wrong place.
Switching to the same logic for forward searching, we now handle this
case properly.
=> Fix handling of opener for nested text objects

src/actions/actions.ts, test/mode/modeNormal.test.ts
=> Implement square-bracket text object

src/actions/actions.ts, src/matching/matcher.ts, test/mode/modeNormal.test.ts
This PR fixes a regression in text objects when positioned over the final character.
It also fixes a regression with `<` objects, which is unfortunately not easy to test right now due to the way test cases are tokenized. I'd like to follow up and make it testable and add the appropriate tests, but I also want to leave master in a stable state.
I am starting to appreciate just how much vim does under the hood :)
=> Fix regressions in text objects

src/actions/actions.ts
After code format, the cursor should be set to the first character of the first line of original selection.
=> Set correct cursor and selection after code format.

src/actions/actions.ts, test/mode/modeNormal.test.ts
Vim's behavior is to move to the closing match, if available. Prior to
this commit, we were moving to the opening char.
Fixes #480
=> Fix % movement when not on opening character

src/actions/actions.ts
This PR changes CommandFold to be used in Normal mode, just like all other fold commands.
Note that i am explicitly setting `vimState.currentMode = ModeName.Normal`, the reason is that *vscode* sometimes changes to Visual mode when folding the block:
Fore example this works fine.
But when the cursor is on the beginning line it goes to Visual mode!
=> CommandFold should be available in Normal mode

ROADMAP.md, src/actions/actions.ts, test/mode/modeNormal.test.ts, test/mode/modeVisual.test.ts
1. Enrich `aw` with `executeWithOperator` and `executeWithCount`
2. Add `aW`
3. Enrich `iw`
4. Add `iW`
5. Normal/Visual mode test cases.
=> Word in visual mode

src/actions/actions.ts
I did not write tests for this since the existing, closely-related actions `MoveToRightPane` and `MoveToLeftPane` did not have tests.
Let me know if anything looks wrong.
=> Fix #338 - add gt, gT support

ROADMAP.md, src/actions/actions.ts, src/matching/matcher.ts, src/matching/quoteMatcher.ts, test/mode/modeNormal.test.ts
=> Implement quoted text objects

src/actions/actions.ts, test/mode/normalModeTests/motions.test.ts
=> Omit first word in hash backwards search

extension.ts, package.json, src/actions/actions.ts, src/mode/modeHandler.ts, src/motion/position.ts, src/number/numericString.ts, test/mode/modeNormal.test.ts, test/number/numericString.test.ts, test/testSimplifier.ts
This adds support for single or numeric-prefix control+x and control+a.
Numeric modes supported:
Fixes #513
=> Implement increment and decrement operators

ROADMAP.md, src/cmd_line/commands/tab.ts, src/cmd_line/subparser.ts, src/cmd_line/subparsers/tab.ts
1. Correct the behavior of `{count}`.
2. Add tabs movement support with newly added Code API.
=> Add tabs movement and fix tab command with correct counting

src/history/historyTracker.ts
Adds a method `HistoryStep.merge` that merges all of `this.changes` into as few `DocumentChange`s as possible, and call it in `finishCurrentStep()`. This makes undoing much faster.
I did some manual testing and I'm pretty sure the logic is sound, but it should probably be reviewed carefully.
See #427.
=> Merge history changes into a single operation. Fixes #427

src/actions/actions.ts, src/mode/modeHandler.ts, src/textEditor.ts
`document.version` is incremented each time the document is changed. Using a regex might be faster too, and since `/` is supposed to be a regex search, that's another thing that could be done. But you'll need to handle invalid regexes and stuff and I didn't want to do it in this change.
=> Fix #438 - Limit the number of matches, and try to only recalculate when the searchString changes, or the document changes

src/actions/actions.ts, src/mode/modeHandler.ts
We are adding APIs for screen lines/characters in Insider and this PR is integrating those APIs for following commands
As @johnfn mentioned while I did #478, the way we implment Movement in VSCodeVim is calculating the target Position or Selection and update the View in a central place (modelHandler). We are likely doing this from the very beginning.
While we are exposing commands in VS Code, we try to avoid exposing View Model information as they are way too complex and always require additional work. Take `scroll to next screen line` as example, we want VSCodeVim just provides the Position information and handle the movment ourselves, but for other extension authors or just users …
=> Screen lines and characters.

extension.ts, package.json, src/actions/actions.ts, test/mode/normalModeTests/commands.test.ts
Previously `<delete>` key works in Normal Mode but is not repeatable.
This PR makes it repeatable, so commands like `5<delete>` would work like `5x`.
=> Make <delete> repeatable in Normal Mode. Fix #394

src/actions/actions.ts
=> Support gd

package.json, src/actions/actions.ts
Sry, i tried to fix #526 but i'm not a typescript nor js nor web developer and not really familiar with github pull request and your contribution guidelines. Just take a look, its a simple fix but i'm not sure if i created any side-effects.
=> Added CommandGoToOtherEndOfHiglightedText - #526

src/actions/actions.ts, test/mode/modeInsert.test.ts
This fixes the issue I reported in #550, and adds a test to prevent regressions.
=> Fix incorrect cursor location after deleting linebreak (fixes #550)

extension.ts
Seems to be a regression from recent refactor. Tested manually in debug
extension. Prior to this commit, ctrl+a/ctrl+x didn't work. Now they do.
=> Fix binding of control-keys

gulpfile.js, src/actions/actions.ts
* Small workaround to prevent extension from locking up when `#` on whitespace.
* Adding `gulp watch` command to auto-compile things on file changes.
The current implementation of `#` and `*` do not current map to the expected behaviour of vim and will require more time to fix.
=> Hack to mitigate #569 and prevent extension from locking up

README.md
The current README has the user disable OS X’s “press and hold” feature at a global level. It’s possible to disable this on a per-app basis, though, provided you know the name of an app’s .plist file.
This change will disable “press and hold” only for VSCode, not globally.
=> OS X non-global key repeat fix

ROADMAP.md, src/actions/actions.ts, src/cmd_line/commands/substitute.ts, src/cmd_line/lexer.ts, src/cmd_line/node.ts, src/cmd_line/parser.ts, src/cmd_line/subparsers/substitute.ts, src/cmd_line/token.ts, src/mode/modeHandler.ts, test/cmd_line/substitute.test.ts
Fix #512. 
We support followings substitute commands
=> Substitute with no range or marks

src/actions/actions.ts, src/mode/mode.ts, src/mode/modeHandler.ts, src/mode/modeReplace.ts, src/textEditor.ts, test/mode/modeReplace.test.ts
=> Replace mode

src/actions/actions.ts, test/mode/modeNormal.test.ts
=> Fix for issue #571

README.md, src/actions/actions.ts, test/mode/modeNormal.test.ts
=> fix C or cc kill the empty line

ROADMAP.md, src/actions/actions.ts, src/motion/position.ts, test/mode/modeNormal.test.ts, test/mode/modeVisual.test.ts, test/motion.test.ts
The code becomes complex when dealing with Vim' special logic of leading/trailing spaces handling.
=> Sentence selection

README.md, ROADMAP.md, package.json, src/actions/actions.ts, src/cmd_line/commands/setoptions.ts, src/cmd_line/scanner.ts, src/cmd_line/subparser.ts, src/cmd_line/subparsers/setoptions.ts, src/configuration/configuration.ts, src/mode/modeHandler.ts, src/motion/position.ts, src/textEditor.ts, test/mode/normalModeTests/dot.test.ts, test/testUtils.ts, tsconfig.json
This feature is related to #433, #463, #487 and #481. The basic idea is maintaining a singleton of Vim Settings. This Vim Seting object reads configuration from User Settings, `.vimrc`, Code configuration then our own (VSCodeVim) default value.
=> Vim Settings

src/actions/actions.ts, test/mode/modeVisual.test.ts
=> Add support Y in visual mode

package.json, src/mode/modeHandler.ts, src/mode/remapper.ts
Adds functionality for Non-Recursive keybindings.
=> Added Non-Recursive mapping capability. Fixes issue #408

ROADMAP.md
Github is just not displaying these because it thinks we're trying to
put real HTML tags in.
Full preview: https://github.com/sectioneight/Vim/blob/fix-tag-roadmap/ROADMAP.md
Example before:
Example after:
=> Fix tag markup in roadmap

src/actions/actions.ts, src/configuration/configuration.ts, src/motion/position.ts, test/mode/modeNormal.test.ts
This uses a new `autoindent` setting (default true) to determine whether
a line replacement should cut to the beginning of the line, or the first
non-whitespace char.
Fixes #626
Two things to note:
- We're not actually doing any smart indentation, we're just assuming they want to keep the original indentation that was on the line. This appears to be how Vim behaves as well.
- In Vim, `autoindent` is not enabled by default, but I think most people enable it and VSCode obviously has it on by default as well.
=> Respect indentation on cc and S

src/actions/actions.ts, test/mode/modeNormal.test.ts
=> fix #501 some more to include 'k'

README.md
Tiny fix to README that had missleading instructions.
=> Fix missleading readme instruction

src/mode/modeHandler.ts
=> updating the undo tree when using bracket operators slightly

package.json, src/history/historyTracker.ts, src/mode/modeHandler.ts
This is to address issue #644 
I am not sure I like this approach and want to see if I can do something with cursor ending position vs start position so that it applies to mouse AND arrows without needing to register the keys the way I am.
=> Undo behavior when position changes using arrows or mouse

src/matching/matcher.ts, src/mode/modeHandler.ts, src/motion/position.ts
=> improves bracket undo behavior when vscode autocloses brackets

src/actions/actions.ts, src/mode/modeHandler.ts, test/mode/modeNormal.test.ts
=> Allow regex in / search

src/cmd_line/commands/quit.ts, src/cmd_line/commands/write.ts, src/cmd_line/commands/writequit.ts, test/cmd_line/writequit.test.ts
Bug fix is currently not working with Visual Studio Code - Insiders
>Version 1.5.0-insider
>Commit 3d9622208b2167921b6664e04fd1fbd51507a4a0  
it seems that the `isDirty` property of the `vscode.TextDocument` is set false for newly created document. Going to check it tomorrow with normal vscode.
=> Fix bug #613 ":wq command dows not work"

README.md, package.json, src/configuration/configuration.ts, src/mode/modeHandler.ts
=> implement useSystemClipboard command

README.md, extension.ts, src/actions/actions.ts, src/history/historyTracker.ts, src/mode/modeHandler.ts, src/mode/remapper.ts, src/util.ts, test/cmd_line/substitute.test.ts, test/cmd_line/writequit.test.ts, test/mode/modeInsert.test.ts, test/mode/modeNormal.test.ts, test/mode/modeReplace.test.ts, test/mode/modeVisual.test.ts, test/mode/modeVisualLine.test.ts, test/mode/normalModeTests/commands.test.ts, test/mode/normalModeTests/dot.test.ts, test/mode/normalModeTests/motions.test.ts, test/operator/put.test.ts, test/testSimplifier.ts
Easing myself back into the project after a short hiatus with this simple change. 
Update: Translating key presses to Vim's angle bracket notation:
`ctrl+*` becomes `<C-*>`
`escape` becomes `<Esc>`
`backspace` becomes `<BS>`
`delete` becomes `<Del>`
=> Use Angle Bracket Notation (Fixes #64)

src/motion/position.ts
Fix crash when `<BS>` at beginning of document as it tries to move to a position that doesn't exist.
=> Fix error when <BS> at beginning of document

src/actions/actions.ts, test/mode/normalModeTests/commands.test.ts
=> Handle Ns and fix #684

src/actions/actions.ts, src/error.ts, src/globals.ts, src/mode/modeHandler.ts, src/motion/position.ts, src/textEditor.ts, test/error.test.ts, test/mode/modeNormal.test.ts, test/mode/normalModeTests/motions.test.ts
Properly fixes https://github.com/VSCodeVim/Vim/issues/569. 
Behaviour of `#` and `*` is expected to be:
1) If cursor selects whitespace, the word closest to right is chosen
2) If there is no word to the right of the cursor, a VIM error is thrown
3) Otherwise, searches for currently selected word.
=> Fix `#` and `*` Behaviour

extension.ts, src/history/historyTracker.ts, src/mode/modeHandler.ts
@johnfn Fix for #680 !
Let me know if you need something to change :-)
=> clear history when content from disk is changed

ROADMAP.md, src/actions/actions.ts, src/mode/modeHandler.ts, src/motion/position.ts, test/index.ts, test/register/register.test.ts, test/register/repeatableMovement.test.ts
Related Issue #410 
@rebornix @johnfn please let me know if you want me to change something in this PR.
=> Implement ; and ,

.gitignore, src/actions/actions.ts
=> Some visual block fixes

extension.ts, src/mode/modeHandler.ts
When you `ctrl-w h` into another editor, the undo history states of the two editors would become intertwined. It could also cause VSCodeVim to crash if they were big enough, because it'd attempt to diff them against each other and take a really long time.
=> Fix race condition with switching active text editor.

package.json, src/util.ts
We were remapping `j` to `<j>`
=> Hotfix remapping

src/actions/actions.ts, test/mode/normalModeTests/dot.test.ts
Toggle case wasn't toggling interWoVen cases...
Also made it repeatable with dot and <num> correctly
=> fix #690 and other toggle case issues

extension.ts, src/actions/actions.ts, src/mode/remapper.ts, src/notation.ts, src/util.ts, test/notation.test.ts
* Fix for #716. In the config, you can now set `<Esc>` or `<esc>`
* Moved angle notation stuff to it's own class
=> Remapper fixes

src/actions/actions.ts
Apparently we were not using the latest cursor movement related API.
=> Align Screen Line commands with latest Code API

package.json
Thought it didn't make it to 0.1.8 and was anxious :p
@johnfn 
=> Add autoindent setting

src/cmd_line/commands/wall.ts, src/cmd_line/subparser.ts, src/cmd_line/subparsers/wall.ts
Implements a basic `:wa[ll]` command (http://vimdoc.sourceforge.net/htmldoc/editing.html#:wall)
It currently just triggers vscode's `workbench.action.files.saveAll` command, so the bang version (`wa!`) doesn't overwrite readonly files.
=> Implement :wa[ll] command (write all)

ROADMAP.md, package.json, src/actions/actions.ts
Add support for https://github.com/VSCodeVim/Vim/blob/master/ROADMAP.md#special-keys-in-insert-mode
=> Special keys in Insert Mode

ROADMAP.md, src/actions/actions.ts, src/cmd_line/commands/setoptions.ts
I'm going through the roadmap and see our current status. But I do find the warning tag a little bit confusing. It indicates the feature is partly implemented but we don't which part is missing: corner user case, test case or anything else? When we run into issues with commands in this category, we don't know whether it's a bug or a missing feature.
So here I did two things to the roadmap
1. Add 🔴 to each command that requires better description of the status: which part is missing and how current command works. Part of the commands are handled by me so I'll give them a update while rest of them are implemented by @jpoon @johnfn @xconverge @sectioneight @aminroosta ,etc. Please leave …
=> [WIP] Roadmap update

.vscode/launch.json, .vscode/tasks.json
Request for comment cc: @johnfn @rebornix 
Force a build via `gulp` on extension launch/test. I tend to forget to run `gulp watch` manually; often times I would change the source, run it, and wonder why the behaviour didn't change before the duh moment.
With this change,
* Pro: Guaranteed that the TS is compiled; no need to run `gulp watch` or `npm compile` manually and check console if things compiled correctly. auto-runs tslint.
* Con: Adds build time (5s right now) before you can launch the extension/run tests
=> build on extension/test launch

ROADMAP.md, src/cmd_line/commands/register.ts, src/cmd_line/subparser.ts, src/cmd_line/subparsers/register.ts, src/register/register.ts
Show register info by running `:reg {arg}`
=> Register info

ROADMAP.md, package.json, src/cmd_line/commands/read.ts, src/cmd_line/scanner.ts, src/cmd_line/subparser.ts, src/cmd_line/subparsers/read.ts, test/cmd_line/read.test.ts
Initial support for read and read!.
[Vim documentation, read](http://vimdoc.sourceforge.net/htmldoc/insert.html#:read)
[Vim documentation, read!](http://vimdoc.sourceforge.net/htmldoc/insert.html#:read!)
Range and opt arguments are not yet implemented.
=> Read command

src/actions/actions.ts, src/mode/modeHandler.ts, src/textEditor.ts
Add editor scroll commands. The trick in this PR is disabling view updating for editor scrolling as Code already does it for us, re-updating the view will lead to unexpected result of layout redraw.
This PR should fix #672, #673, #675, #676 .
=> Editor Scroll

src/actions/actions.ts, test/mode/modeNormal.test.ts, test/register/register.test.ts
Fixes #743.
Delete was not taking a possible `\r` into consideration when performing a linewise delete, which resulted in an extra linebreak being appended to the line if it later was pasted.
Also removed a duplicate test related to this functionality (`"Can copy to a register"`). That test was failing on Windows with `"files.eol": "crlf"`, but now passes after this change.
=> Fix delete line with CRLF (#743)

.github/CONTRIBUTING.md, .travis.yml, gulpfile.js
On a successful build of the `release` branch, Travis will:
1) Create a GitHub release uploading the packaged vsix
2) Publish the new version to the marketplace
Moving forward, for pushing a release, it will be:
1) merge `master` to `release` branch
2) `git tag`/`gulp release` and `git push origin --tags`
=> Release Pipeline

src/register/register.ts, test/register/register.test.ts
This adds support for accessing the system clipboard using the `"+` register, addressing #780.
The `"+` register is basically an alias for the `"*` register, so I didn't make any changes to [how the `useClipboard` setting is handled](https://github.com/VSCodeVim/Vim/blob/master/src/mode/modeHandler.ts#L372).
=> Support "+ system clipboard register (#780)

README.md
I believe [hlsearch is false by default](https://github.com/VSCodeVim/Vim/blob/214619d8d61524960c2c4d099a6a120e3a0e91a2/src/configuration/configuration.ts#L56).
Trivial change, haven't run tests 😃
=> Add autoindent to README, fix hlsearch default

src/actions/actions.ts, test/mode/normalModeTests/commands.test.ts
=> Fix bug joining lines with whitespace only next line

src/actions/actions.ts
Weird bug, weird fix, but I am ok with it if you are
=> fixes #739

src/actions/actions.ts
=> zz in visual, visualline, and visual block mode

src/mode/modeHandler.ts
=> Fixes arrow navigation to EOL while in insert

src/actions/actions.ts, test/mode/modeVisual.test.ts
=> fixes #784

src/cmd_line/commands/quit.ts
Is there a reason this was here? This PR is more of a question, but could be merged if it makes sense...
Shouldnt :q on a new untitled file work? On MacVim if I open it and immediately do :q it quits
This is also causing #846
=> Unnecessary quit check on untitled files

src/actions/actions.ts, src/mode/modeHandler.ts, src/motion/position.ts, src/motion/range.ts, src/transformations/transformations.ts, test/mode/modeVisual.test.ts
Refactoring this massive codebase into this new style is... tough.
The more we do it, though, the more awesome multi-cursor becomes. And also, the more consistent our codebase becomes. Which is nice for anyone who wants to add stuff to it. 😉
=> [WIP] Use new transformation style in delete and paste

extension.ts, package.json, src/actions/actions.ts, src/globals.ts, src/history/historyTracker.ts, src/mode/modeHandler.ts, src/register/register.ts, test/mode/modeNormal.test.ts, test/mode/normalModeTests/dot.test.ts, test/testSimplifier.ts
This PR implements `ctrl-A` and `ctrl-@` in Insert Mode, which inserts previously change. Instead of maintaining the change in history ourselves, I'm currently just leveraging `documentContentChangeEvent`. This way when we type `ab` and intellisense helps us autocomplete it to `abstract`, we can get the whole `abstract` through `contentChange`, not just `ab`.
@johnfn @xconverge this is totally a different way of handing last change which we currently maintained in HistorySteps, so for now I just put the plain array in HistoryTracker. Please take a look and see if it can inspire you on how to handle history.
The only catch here is there might be racing condition between …
=> Insert Previous text

extension.ts
Done cleaning up my git...sorry for the noise in the closed PRs
This mitigates when bad things happen in a modehandler, you can close the tab and when you reopen the file you can start again...
=> Remove unused modehandlers when tabs are closed

package.json
Edit package.json to allow `ctrl-j` and `ctrl-k` to be mapped in settings.json
=> allow remapping of ctrl-j and ctrl-k in settings.json

src/cmd_line/commands/register.ts
---
Display register value in reg command. Also fixes #830.
=> display register value in reg-cmd, fix #830

src/mode/modeHandler.ts
---
I did not create an issue for that, so here is the thing. In Visual Multicursor Mode no decorator for multicursor where drawn, and also the selection start was not drawn correctly.
Now it looks like:
=> Draw multicursor correctly in Visual Mode

src/mode/modeHandler.ts
=> update internal cursor position per Code selection change

extension.ts
Wasn't able to reproduce this when running from source, but based on the trace this should fix 905
The following was something I saw in my log as well, just like the issue
```
Cannot read property 'dispose' of undefined: TypeError: Cannot read property 'dispose' of undefined
at vscode.workspace.onDidCloseTextDocument (/Users/sean/.vscode/extensions/vscodevim.vim-0.3.7/out/extension.js:127:45)
at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5:6321)
at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5:14643)
at t.$acceptModelRemoved (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:12:5814)
at …
```
=> fixes #905

extension.ts, src/mode/modeHandler.ts, test/mode/modeVisualLine.test.ts, test/mode/normalModeTests/commands.test.ts, test/mode/normalModeTests/dot.test.ts
I did two things here
1. Update internal cursor position whenever there is selection change.
2. Stop redrawing cursors when switching panes or tabs as Code is maintaining the cursor position for us.
=> Update internal cursor position when necessary

test/mode/modeNormal.test.ts, test/mode/normalModeTests/dot.test.ts, test/operator/put.test.ts, test/testUtils.ts
Finally decrease our manual test step count to 4.
=> Test enhancement

src/actions/actions.ts
@johnfn After talking on the Slack channel (as willwow), here's a little PR to add a `gh` command to bring up the hover text when in normal mode. One thing that's annoying is that it seems that `showHover` takes focus away from the editor, so you have to press ESC to get back to normal mode (the same thing happens with the default VS Code shortcut). I'd think that ideally any other command would close that hover box, but I'm not sure how I'd set that up.
Thanks!
=> add gh hover command

src/actions/actions.ts, test/mode/modeVisualBlock.test.ts
I add a command is `D` in visual block mode.
It's like below ↓
=>  Add a command is `D` in visual block mode.

src/actions/actions.ts, test/mode/modeInsert.test.ts
fix #685 
I found it annoying that <Esc> doesn't remove leading spaces in insert mode. Today, I'm going to fix it myself, contributing to this aaaaaawesome project. You guys have done a great job. 👍
=> remove leading spaces when <Esc>... is pressed #685

package.json
The Marketplace now supports a Keymaps category.
=> Add Keymaps category

src/actions/actions.ts, src/mode/modeHandler.ts, src/motion/position.ts, src/transformations/transformations.ts, test/mode/modeVisual.test.ts, test/mode/modeVisualBlock.test.ts, test/mode/modeVisualLine.test.ts
Any feedback on better ways of doing any of this?
1. Visual block mode returns correctly after running "r" instead of having a few cursors left around
2. Replace does not replace unless there is a character, this applies to line, block, and regular visual
3. Replace added to visual and visual line with ~~an IterateSelection position function~~ selective replace transforms in chunks
=> Fix replace in visual, visual line, and visual block mode

src/mode/modeHandler.ts, test/mode/modeVisualLine.test.ts
Here you go @rebornix 
Sorry about that!
=> Fix for visual line behaving funky when going from bottom up

src/state/searchState.ts
Currently, when a SearchState object is defined, the searching begins before this.isRegex is set. This is because the setter, `searchString` runs the search function, and it is set in the constructor before isRegex is set, which means it will be undefined during the search.
This PR makes sure isRegex is set and available during the search by defining it before searchString.
=> SearchState - Fixed isRegex not set on search

src/actions/actions.ts, src/number/numericString.ts, test/mode/modeNormal.test.ts
@sectioneight @johnfn took another stab at this one, last attempt was https://github.com/VSCodeVim/Vim/pull/661
=> New increment without separators

src/number/numericString.ts
- [√] Commit message has a short title & issue references
- [√] Each commit does a logical chunk of work.
- [√] It builds and tests pass (e.g `gulp`)
=> No need for "i" flag on a numerical only regex

src/actions/actions.ts, test/mode/modeNormal.test.ts
=> fixes #998

src/actions/actions.ts, src/cmd_line/commands/register.ts, src/register/register.ts, test/register/register.test.ts
Implements basic functionality for numbered registers (#500)
- `0` for last yanked text
- `1` to `9` delete history
Implements appending to register with uppercase letter
- for `single` to `single` cursor register
- for `single` to `multi` cursor register
- for `multi` to `multi` cursor register (if line count match)
Closes PR #918 because i was to stupid to rebase that branch...
=> Numbered, upper case and multicursor register

src/actions/actions.ts
Makes `Cmd-D`, `Cmd-Alt-Up` and `Cmd-Alt-Down` repeatable by setting the `runsOnceForEachCountPrefix` property to `true`.
So you can type `3<Cmd-Alt-Down>` and end up with 4 multi-cursor because 3 where created beneath your main cursor.
=> Make create-multicursor commands repeatable

src/actions/actions.ts, test/mode/modeVisual.test.ts
=> fixes #1013

package.json, src/configuration/configuration.ts, src/mode/modeHandler.ts, src/taskQueue.ts, test/mode/normalModeTests/dot.test.ts
=> [Post 1.0] Two way syncing of Vim and Code's configuration

.github/ISSUE_TEMPLATE.md
Learned this trick from TypeScript's issue template: https://github.com/Microsoft/TypeScript/issues/new
The top line won't be rendered, but will be visible when issue gets reported.
=> Hide the info line in issue template

package.json, src/actions/actions.ts, src/mode/modeHandler.ts, test/mode/modeInsert.test.ts
@johnfn Do you thank that the getter way is cleaner than this? This doesn't seem too bad to me but it is relatively specific for this command.
=> fixes #1065

README.md
The README stated that the useCtrlKeys default is `false` while the default in package.json defines it as `true`. This PR makes the readme consistent with the settings in package.json.
=> Updated useCtrlKeys default value

src/actions/actions.ts
Could be related to #1130, but I am unable to reproduce that specific issue yet so will not close it.
Highlighting works fine for me using * and #, this fixes highlighting ONLY in the case that :nohl had been used previously at some point.
=> minor fixes for # and * after using :nohl

src/actions/actions.ts, src/history/historyTracker.ts
implements g; to go to last edited location
=> fixes #1063

src/mode/modeHandler.ts
Tested it pretty thoroughly, including https://gist.github.com/rebornix/d21d1cc060c009d4430d3904030bd4c1
Fixes selection starting past eol not including last char, and clicking past eol should go to normal
=> More click past eol o no

package.json
These keybindings are all used in the default bindings (on linux) and so should respect the `vim.useCtrlKeys` setting.
=> control key bindings respect the useCtrlKey setting

src/actions/actions.ts, test/mode/modeNormal.test.ts
In Multi-Cursor mode "d" in Visual Mode and "D" in Normal-Mode is not working.
Added the current multicursorindex to the `Register.Put` method.
=> Fixed "d" and "D" in multicursor mode

src/actions/actions.ts
=> fixes #1170

src/actions/actions.ts, src/mode/modeHandler.ts, src/state/globalState.ts, src/state/searchState.ts, src/textEditor.ts, src/util.ts, test/mode/normalModeTests/dot.test.ts, test/mode/normalModeTests/motions.test.ts
Holds state of repeat "." actions and search globally (across editors), and added tests for each in their respective test files.
Should fix #1081 and #1156 issues
=> Implements Global state

src/register/register.ts
Tested on ubuntu with and without xclip installed
=> fixes #1180

src/cmd_line/commands/file.ts
@johnfn In the es6 import statements, the file extension is omitted, this PR tries to add the file extension automatically.
For example when your cursor is at `"../node"` the `gf` command will open `../node.ts`
`---------current file:  src/cmd_line/commands/file.ts--------- `
`import * as node from "../node";`
=> Support "gf" in es6 import statements by adding the file extension

src/mode/modeHandler.ts
=> Added tag text to status bar in surround mode

src/mode/modeHandler.ts
#1236
Clear commandList for any remapped commands that handled successfully. This resolves the issue of remapped command occasionally doing the original command instead of the remapped command.
=> Clearing commandList for remapped commands

src/actions/actions.ts
Re [#862](https://github.com/VSCodeVim/Vim/issues/862#issuecomment-274751266). I rewrote `CommandInsertNewLineAbove` to mirror `CommandInsertNewLineBefore`, just using `editor.action.insertLineBefore` as the editor command to execute.
=> Fix autoindent when opening a line above

src/actions/actions.ts
this was also impacting other surround actions ```cs{"``` in this case would have had similar results
sorry for such a silly fix...really just playing whack-a-mole here :)
=> fixes #1271

src/mode/modeHandler.ts
User remapping affect tests, resulting in unpredictable test breakage on local. If the remapping functionality starts to receive testing later, a new solution will probably need to be found.
=> avoid using user remapping in test mode

src/matching/matcher.ts, src/mode/modeHandler.ts, test/mode/modeInsert.test.ts
#1228 
When in insert mode, if a user is deleting an opening bracket, and a matching closing bracket is immediately after it, also delete the closing bracket. Corresponding test included.
=> Delete matching bracket upon backspace

src/actions/actions.ts, test/mode/normalModeTests/motions.test.ts
Rename `CommandStar` and `CommandHash` to `CommandSearchCurrentWordExactForward` and `CommandSearchCurrentWorldExactBackward`, which describe their effect. Also include regex word bounds in the search so that they act the same as in Vim.
Add `CommandSearchCurrentWordForward` and `…Backward` (commands `g*` and `g#` respectively), that match without word bounds.
Closes #1266
---
So this is mainly a copy+paste, I wasn't sure if there was an idiomatic approach to sharing behaviour between these two commands. Also I renamed the classes because it felt more sensible to name them after their effect than their keybindings (also it seemed strange to call the new one something like `CommandGStar`.
Let me know if there's anything stylistically or functionally wrong here, I'm happy to iterate on it.
=> Support exact and inexact current word search

src/mode/modeHandler.ts, src/mode/remapper.ts
should work...tested the few cases that were in the issue reported
=> fixes #1145

src/actions/actions.ts
When using `C-o` in Insert Mode to execute a single Normal Mode command, the cursor will be of by one after the change.
Changing the argument input for the specific action fixes this bug, while not changing the behavior of other code
=> Fix for #1293

src/actions/actions.ts, test/mode/modeVisual.test.ts
The delete function of the DeleteOperation Class already account for this case, if the Register Mode is set to LineWise.
=> D in visual mode behaves like d

src/actions/actions.ts, src/matching/matcher.ts, src/mode/modeHandler.ts
Fixes the important ones from #1255, the only ones left have nothing to do with surround but more so how sentence objects and word objects work
- backspace when entering tags
- visual line then surround creates newlines before/after and puts cursor in right place
- surround t triggers tag input correctly
- added some shortcuts from the original surround plugin b = (, B = {, and r = [
=> More surround fixes

src/actions/actions.ts, test/mode/modeVisual.test.ts
Changed the c Action to encounter for cases where the selection ends at the beginning of a line.
The tests revealed, that s is implemented using c(0,0).
Therefore i check, if this is a real selection before calling the getLeftThroughLineBreaks() function
=> Fix c on line beginning#1302

src/matching/matcher.ts
@rufusroflpunch this isn't the cleanest way to fix the problem but I think it is fine, what do you think?
The problem is we use nextPairedCharacter in the matcher in a few other places, and if it is not in the pairings, then it returns instantly. However, when we added quotes, this meant nextPairedCharacter would now iterate the document looking for a forward or backward matching char, this could probably be made to work correctly since in these cases quotes are typically pairs, but this solution seemed easier to me for now...
=> fixes #1327

src/configuration/configuration.ts
Fix #1329 
The reason behind failing build was due to the changes made in typescript 2.2 as below.
> TypeScript 2.2 improves checking of nullable operands in expressions.
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-2.html
Hence, I removed union type of undefined in configuration.ts to make the build work.
Builds successfully in typescript 2.1.6 & 2.2.1
=> Fix #1329 failing build by removing undefined in configuration.ts

README.md, package.json, src/actions/actions.ts, src/configuration/configuration.ts, src/mode/modeHandler.ts
I just couldn't resist fixing bug #1337. (Not really.) 
This fixes the annoying problem of cmd-c or ctrl-c not copying the final character, which I have heard a lot of people complain about. I would like people on alternate platforms to test this before I release a new version.
=> Override VSCode copy command. #1337, #616.

src/cmd_line/commands/sort.ts, src/cmd_line/subparser.ts, src/cmd_line/subparsers/sort.ts, test/cmd_line/sort.test.ts
- Works on a range
- ! option is supported to reverse the sort
- Other options not supported at this time
Fixes: #1341
=> Add limited support for :sort

src/matching/matcher.ts
Use regex to match brackets instead of iterating all characters one by one. Fix performance issues of inserting brackets in a large file.
cc @xconverge @johnfn
=> regex match

extension.ts, src/configuration/configuration.ts, src/mode/modeHandler.ts, src/mode/remapper.ts
This is really nice and was easy!
It exposes some weirdness with how we do remapping but o well.. let me know what you think
=> Update config options without restarting

src/mode/mode.ts, src/mode/modeEasyMotion.ts, src/mode/modeHandler.ts, src/mode/modeInsert.ts, src/mode/modeInsertVisualBlock.ts, src/mode/modeNormal.ts, src/mode/modeReplace.ts, src/mode/modeSearchInProgress.ts, src/mode/modeVisual.ts, src/mode/modeVisualLine.ts, src/mode/surroundInputMode.ts
This PR changes the visual mode cursor to the standard block cursor, and the replace mode cursor to an underline. These two changes result in a cleaner look, and more closely match Vim's aesthetic. The block cursor unfortunately not possible in visual block mode.
_Cursors Before_
_Cursors After_
=> Use block cursor in visual & underline in replace

extension.ts, src/mode/modeHandler.ts
@johnfn @jpoon 
This will fix the cursor issue but break peeking apparently
I don't have time to look at it now but will put this here incase we want to do a temporary release...
=> fix for cursor not changing correctly, workaround for vscode issue

src/mode/modeHandler.ts
I think you commented this out when you added multicursor...it is really a drag if you are an arrow/mouse user, so atleast here this will improve it for everyone except for multiCursor AND arrow/mouse users
but multicursor is already messed up if you use the mouse so I don't think we need to fix this now
=> fix undo points when moving around in insert with mouse or arrow keys

src/mode/remapper.ts
- fixes using o then jj remapped to <esc> not deleting whitespace due to o checking for previous keys
=> Remapper cleanup key history

README.md, extension.ts, package.json, src/configuration/configuration.ts
I like this. PR for #1424
example config option that may be handy on windows for some
```
"vim.handleKeys":{
"<C-a>": false,
"<C-f>": false
},
```
I would like to have it all in configuration.ts so that it can happen without a vscode restart so that will be next. Then trying to clean it up some more and make sure all of our keys in package.json are handled (only modifier key combos I think will be part of this)
=> Allowing user to selectively disable some key combos

src/actions/actions.ts
=> gUU and guu

src/configuration/configuration.ts, src/notation.ts
move some magic related to configuration of leader to the right place
=> minor cleanup to improve leader usage with <space>

src/mode/modeHandler.ts
pretty scared of this function still...
=> fixes #1312

README.md, package.json, src/configuration/configuration.ts, src/easymotion/easymotion.ts
I can get the same result without the library if we want, but it definitely cleans up the code
Also, I spent a while using different functions of it to manipulate the color wheel to try out different things for readability. Complementary font color, etc don't look good.
Black and white and using the light()/dark() luminosity formula seemed to give the best results.
=> Change easymotion decoration colors to use searchHighlight colors

README.md, package.json, src/actions/actions.ts, src/configuration/configuration.ts
Someone asked on slack, not sure why but seems to make sense to at least have the option since easymotion does as well.
=> Add ability to turn surround plugin off

README.md, package.json, src/configuration/configuration.ts, src/easymotion/easymotion.ts
Made this for my own issue :P #1481 
Here's an example of the settings in use:
```
"vim.easymotionMarkerBackgroundColor": "#3C6478",
"vim.easymotionMarkerForegroundColorOneChar": "white",
"vim.easymotionMarkerForegroundColorTwoChar": "white",
"vim.easymotionMarkerHeight": 20,
"vim.easymotionMarkerYOffset": 12,
"vim.easymotionMarkerWidthPerChar": 10,
```
**I removed the existing easymotion background color option since I feel this encompasses that, but feel free to add it back if you think it's better to keep it!**
Here are some examples of what the styling can look like: (p.s. I happened to use white and black for the font colors but they can be anything, like yellow text on dark blue bg or something)
=> Added new style settings (color, size, etc.) for easymotion markers

README.md, src/actions/actions.ts, test/mode/modeHandler.test.ts, test/operator/comment.test.ts, test/testUtils.ts, test/textEditor.test.ts
This PR adds functionality similar to tpope's [vim-commentary](https://github.com/tpope/vim-commentary). As it didn't require a lot of work I thought I would just create a PR instead of opening an issue / feature request.
It can toggle line comment the current line using `gbb` or toggle comments on the target of a motion i.e. `gb5j` to toggle line comments on current line and the following next four lines or `gbap` to toggle line comments in a paragraph etc.
It uses the built-in _Toggle Line Comment_ functionality of VSCode to determine how to apply/unapply comments.
A few questions:
- I would have liked to use `gc` as the original Vim plugin but since this is already used in this extension I settled for `gb`. Thought on this?
- Since VSCode's _Toggle Line Comment_ relies on the current …
=> Add line comment operator

README.md, package.json, src/actions/actions.ts, src/cmd_line/commands/nohl.ts, src/configuration/configuration.ts, src/mode/modeHandler.ts, src/mode/remapper.ts, src/state/globalState.ts
This fixes #1166 
example usage:
```
{
"before":["<C-n>"],
"after":[],
"commands": [
{
"command": ":nohl",
"args": []
}
]
},
{
"before":["<C-r>"],
"after":[],
"commands": [
{
"command": ":%s/test/123/g",
"args": []
}
]
}
```
=> added cmd_line commands to remapper

README.md
In the section on `af`, the README says to press `az` again. This looks like it might be a typo.
=> Fix README description for `af`

src/actions/actions.ts, test/mode/modeInsert.test.ts
is this better or worse than adding another flag type @johnfn?
=> fixes #1519

README.md, package.json, src/configuration/configuration.ts, src/mode/modeHandler.ts
I am ok opening this now since it is off by default and behind a config flag. We can either wait on it or just release it now and change that single function in the future when vscode changes the way this is done...
fixes #1056
=> Allow user to change status bar color based on mode

src/actions/actions.ts, src/mode/modeHandler.ts
A little funky but I don't think its too bad :)
This is to fix #1244
Any suggestions on a better way would be great... @johnfn
=> make surround repeatable with dot

.travis.yml, README.md, package.json, src/actions/actions.ts, src/register/register.ts, src/util.ts, test/register/register.test.ts
This library is being worked on consistently and is not stale with potential issues
Still having issues with the character • which I use for testing. Once it works perfectly with this I will also test chinese characters
=> [WIP] change system clipboard library to a newer more maintained library

src/actions/actions.ts, test/mode/modeNormal.test.ts
The issue is that if your cursor starts on the end of a word, getCurrentWordEnd should clearly include the current word.
I plan on adding a couple more unit tests for some edge cases.
=> Fixed Issue #1528

src/actions/actions.ts, test/mode/modeInsert.test.ts
So I fixed issue #1513. This issue only occurs when Configuration.expandTab is turned on. 
The main behavioral decision I made is that if you press backspace on a whitespace only line, it deletes both to the next "tab" as well as all the whitespace after it.
I'm unsure about a couple of things
1. I'd like to create tests, but from looking through the repo, I don't see how to set Configuration.expandTab to be true while running these tests.
2. When running the tests locally,  I get 56 tests failing, with or without my change. I don't really know what I'm supposed to do there (I thought I would try running the tests on CI, and cool! They passed.).
Cheers,
Horace
=> [WIP] Fixed issue #1513

src/actions/actions.ts, test/mode/modeNormal.test.ts
As I was working on the "aw" object, I thought I would fix the other related bugs.
It'd be ideal if I didn't need to special case this, but from thinking about it, it does seem like it's a special case. Normally, when you daw with a "." right at the end, you also want to delete all the whitespace on the left of the word until you reach another word. In this scenario, however, you want it to stay in the same place.
I was working on a complete rewrite of the 'aw' object based off "boundaries", but decided that it was overengineering. However, while writing it, I came some more cases where our behavior doesn't align with vim. I'd like some feedback on whether those cases are worth fixing (imo, vim does some very bizarre things in some of these cases).
```
one  
|  
three
```
becomes
`|one`
=> Fixes #1193, #1350

src/cmd_line/commands/register.ts
Pretty simple. As this.getRegisterDisplayValue returns a promise, we need to await that promise before we use it.
Also, that functionality happened not to be implemented, so I implemented it.
=> Fixes #1539

src/cmd_line/commands/register.ts
This time for real.
The showInformationMessage function just straight up drops the rest of the string after a newline, which seems like unintuitive behavior to me.
There's also the possibility that some other kind of character needs to be escaped. If any of you guys know a better way to escape strings in typescript, I'd love to hear it.
=> Fixes #1539 

package.json
UTF-8 on windows was fixed with this release. He spun his own copy/paste binaries for windows so performance should be fixed now too since there is no sketchy html vbscript stuff. Now macos, linux, and windows should handle utf8 correctly.
fixes #1299 
fixes #1125 
fixes #1284
Thanks to @sindresorhus
https://github.com/sindresorhus/clipboardy/pull/13
=> update clipboardy library with windows utf-8 fix

src/actions/actions.ts, src/motion/position.ts, test/mode/modeNormal.test.ts
Fixes those two issues. One potentially bad practice is that I'm accessing vimState.recordedState.count. I don't know how that might play with things like undo.
This commit also fixes a regression I introduced in PR #1549 . In my defense, the reason the regression happened was that buggy behavior was hiding another bug.
I also added a comment explaining code added in PR #1549 .
=> Fixes #1554, #1553

README.md
The relative URL that was being used only works when viewing the README
from GitHub, and leaves a big blank space if you open VSCodeVim's page
inside VSCodeVim.
This uses a full URL, which should fix the issue. This is how the Chrome
Debugger plugin loads their logo.
=> Fix logo src so logo displays inside VSCode

src/actions/actions.ts, test/mode/modeInsert.test.ts
Simple edge case detection with an added test case to cover.
Admittedly, I'm not completely sure why it fails (I'm guessing it has something to do with the error or maybe the action "deleteText" not processing), but this is a simple enough edge case that makes sense to handle.
=> Fixes #1573

extension.ts, package.json, src/mode/remapper.ts
Ref https://github.com/VSCodeVim/Vim/issues/1543
```
{
"key": "F3",
"command": "vim.remap",
"when": "editorTextFocus",
"args": {
"value": ["a", "b", "c", "<Esc>"]
}
}
```
Fixes #1505, #1452
=> Allow users to use VSCode keybinding for remapping

src/actions/actions.ts
I think the issue here is that when we go word by word adding it in, we always add " {$word}". However, the first word shouldn't have an extra space in front of it.
This problem should also be fixable here, but I thought my current solution was fine. 
https://github.com/VSCodeVim/Vim/blob/master/src/actions/actions.ts#L4514,
=> Fixes #1251

src/actions/actions.ts
Another pretty simple bug fix.
start is not necessarily before stop in visual mode (start is where the cursor is currently, and stop is the "stop" of your selection).
=> Fixes #1594

src/actions/actions.ts, test/mode/modeNormal.test.ts, test/mode/modeVisual.test.ts
I'm a bit confused by this one. The fix for this one was basically reverting #1303. It's possible to make them not conflict, but upon looking at #1303, it seemed to me like the bug it was fixing, #1302 , wasn't a bug at all (doesn't follow vim behavior).
So I removed the corresponding test and added a new one.
Can somebody confirm that that issue was filed erroneously?
=> Fixes #1369

src/mode/modeHandler.ts
this._vimState.editor.selection.start doesn't get updated until we call updateView. 
Why, you ask?
No clue. But it works!
(Well, we know that updateView updates the vscode object a bunch of times, so that probably has something to do with it.)
=> Fixes #1532

src/actions/actions.ts, src/mode/modeHandler.ts
I think this fixes all the visual selection related bugs I could find.
=> Fixes #890, #1377

src/actions/actions.ts, src/cmd_line/main.ts, src/state/searchState.ts, test/mode/modeNormal.test.ts
Basically, the general approach is that we count how many newlines there are in their search string, and expand our search beyond line by line accordingly.
Thus, if their string contains two newline characters, then we check two lines at a time, and so on.
Accordingly, if there are no newline characters, this shouldn't affect performance at all, and performance should then degrade linearly with the amount of newlines (which makes sense).
One thing that it's missing is that Vscode doesn't seem to support highlighting the "newline" character. That makes newlines pretty invisible.
I've also added a test.
PS: You'll notice the commit that made the command line persistent, PR #1601. I accidentally checked it out and don't know how to delete a commit in the past, so I simply reverted it and …
=> Fixes #1575 (and also adds general newline support for searches)

src/motion/position.ts, test/mode/modeNormal.test.ts
Comes from a bug in the IterateWords helper function used. The function should stop at the end of the line, but since wordEnd() isn't at lineEnd(), it continues onto the next line and takes characters from there.
Fixes another small bug as well. Namely, 
```
|-5
abcd
```
does not do right things.
=> Fixes #1588

src/mode/modeHandler.ts
When there is no active editor, `handleSelectionChange` throws an error:
```
TypeError: Cannot read property 'selections' of undefined
at ModeHandler.<anonymous> (/Users/brandoncc/.vscode/extensions/vscodevim.vim-0.6.20/out/src/mode/modeHandler.js:451:74)
at next (<anonymous>)
at __awaiter (/Users/brandoncc/.vscode/extensions/vscodevim.vim-0.6.20/out/src/mode/modeHandler.js:7:71)
at __awaiter (/Users/brandoncc/.vscode/extensions/vscodevim.vim-0.6.20/out/src/mode/modeHandler.js:3:12)
```
This PR updates that function to use the editor that is attached to the event argument instead.
I did the manual testing located at https://gist.github.com/rebornix/d21d1cc060c009d4430d3904030bd4c1
=> use editor from event fixes #1607

README.md, package.json, src/actions/actions.ts, src/configuration/configuration.ts, test/mode/modeVisual.test.ts, tslint.json
The default behaviour of `*` and `#` isn't really intuitive, and Vim itself has [many plugins to handle this](https://www.google.com/search?q=vim+visual+star).
This PR adds a new option to treat `*` and `#` as a new search when pressed in visual mode.
=> Visualstar

extension.ts, package.json, src/actions/actions.ts
Ref #1375. Leverage new Code api to navigate between viewlets, panels, editors by <Ctrl>-<hjkl>.
This is contributed by rebornix/Peng's personal account on his personal machine in personal time.
=> Navigate between view

src/actions/actions.ts, src/motion/position.ts, test/mode/modeInsert.test.ts
I was really really hoping we could reuse code from 'diw' or something like that, but basically, this is the behavior we want from <C-w>.
Get the closest to you of either the beginning of the line or the beginning of the first word to the left of your current position (including your current word if you're on a word), or a newline.
It doesn't really fit well into how we're handling word boundaries anywhere else.
I also added a position utility function to determine whether the current position is in leading whitespace of a line.
Speaking of which, we really need to explain what some of our utility functions do. A lot of them are pretty self explanatory, but one that keeps tripping me up is `position.getLastWordEnd()`
Failed tests are not this PR's issue (pretty sure).
=> Fixes #1137

src/actions/actions.ts, src/matching/tagMatcher.ts, src/textEditor.ts, test/mode/modeNormal.test.ts
Fixes #971, #1108, #1232, and #1300.
Remaining existing issues: `cit` does not enter insert mode when tag is empty, and it also doesn't return to the correct position when you run `cit` in the closing tag.
=> fix multi line in 'at' and 'it' commands

README.md
It would appear that the marketplace website (https://marketplace.visualstudio.com/items?itemName=vscodevim.vim)
is converting line-breaks in the HTML source into <br> tags, creating heaps of ugly whitespace.
This is a test to see if we remove most of the line-breaks that it'll clean all the extra whitespace.
=> Join HTML on single line to prevent extraneous <br>s

extension.ts, src/mode/modeHandler.ts
It seems that whenever we switch editors, we don't have access to cursorPosition until after the stack clears?
Whatever it is, it's similar to this PR: https://github.com/VSCodeVim/Vim/pull/1605
=> Fixes #1503: Undo history isn't kept when switching tabs

src/actions/actions.ts
In insert mode, selecting from left to right results in one more character being selected, so our old workaround was to shift the end of the selection to the left if we're in insert mode. 
So this is how the cursor selections look when we're in "<copy>".
In Normal mode dragging from left to right or right to left,
"|fooba|r"
In Insert mode dragging from left to right,
"|foobar|"
In Insert mode dragging from right to left,
"|fooba|r"
Thus, it works normally if we're selecting from right to left.
Also fixes #1355
=> Fixes #1441: Ctrl-c dropping a character when selecting from right to left in insert mode

src/actions/commands/actions.ts
Added keybindings for <C-w> j, <C-w> k, and changed <C-w> w to navigateEditorGroups.
Fixes #1585.
Also implements more of #1451.
=> Fixes #1585: Added <C-w> j and <C-w> k

src/cmd_line/commands/close.ts, src/cmd_line/subparser.ts, src/cmd_line/subparsers/close.ts, src/error.ts, test/cmd_line/subparser.close.test.ts, test/error.test.ts
This pull request implements the close command.  It is largely based on the existing quit command.  The difference is that it will refuse to close the last window as stated in the vim documentation.
http://vimdoc.sourceforge.net/htmldoc/windows.html#:close
=> Add :close support based on :quit

src/cmd_line/commands/tab.ts
Commands `gt` and `gT` are currently navigating through all opened tabs, instead of navigating inside a split. This change let the behavior more like the default `CTRL-Tab` shortcut, that navigates in files inside the same split/tab group.
=> Changes tabs to navigate inside the same split

package.json, src/actions/commands/actions.ts, src/mode/modeHandler.ts
It's not really idiomatic, but I don't really see a way around it.
One thing I'd like to add before we merge is a rebinding of C-d to D-d. 
Also fixes #1467 and fixes #1311.
=> Fixes #1535, #1467, #1311: D-d doesn't work in insert mode

package.json, src/cmd_line/main.ts
Bumps required version of VSCode to 1.12 though.
=> Fixes #792: Selecting range before Ex-commands highlights initial text

package.json, src/actions/commands/actions.ts, src/actions/operator.ts, test/mode/normalModeTests/commands.test.ts
Otherwise, this PR fixes the first part of #1256 through just adding more key capturing, and fixes the second part by setting desiredColumn in visual mode.
=> Fixes #1256 and #394: Fixes delete key and adds functionality

src/actions/motion.ts, src/actions/operator.ts, src/actions/textobject.ts, src/mode/modeHandler.ts, test/mode/modeNormal.test.ts
This fixes #1196, which was a lot harder than it seemed. I also refactored a tiny part of modeHandler that made it very difficult/impossible to fix this.
I also fixed #1197 
However, the fix also actually broke a test, but I think it actually broke the test so it actually has correct behavior now! I've committed the test I changed as well.
=> Fixes #1196, #1197: d}/y} not working correctly

src/actions/plugins/surround.ts, test/plugins/surround.test.ts
Fixes issue with complex tag surround by only including the actual tag name instead of the whole contents of the tag.
Before:
After:
Couldn't find any tests written for surround... So no tests. If someone lets me know where I should put tests for this; I'll update the PR.
=> feat(surround): support complex tags surround

package.json, src/util.ts
noticed that the clipboard library was updated to use utf-8 on macos now too
https://github.com/sindresorhus/clipboardy/pull/16
=> remove system clipboard hack for UTF-8

src/common/matching/tagMatcher.ts, test/mode/modeNormal.test.ts
Pretty straightforward bug fix.
I needed to make the second regex capturing group lazy so that the closing slash could always be matched if it existed.
I also needed to move onto the next tag if we found a self closing tag.
Fixes #1668
=> Fixes #1668: Self closing tags not properly handled.

src/actions/commands/actions.ts, src/cmd_line/commands/file.ts
Pretty simple, mostly. One thing to note is that I'm not sure what's the best way of setting cursor position after we change files. Any ideas?
[Link to the regex used](https://regex101.com/r/o1MJt5/2)
=> Fixes #1655: Extends gf to line numbers

package.json
Just to be a good extension citizen, we should only be capturing as much as we use. We can re-add them back in if we need them.
Fixes #1720
=> Fixes #1720: Removed unused <c- > bindings from package.json

src/actions/commands/actions.ts, src/mode/modeHandler.ts
Just needed to add a multicursor index to paste, as well as make sure that the registermode gets set back at the end of each multicursor "action".
For w.e. reason, multicursor tests seem to be fairly buggy on the travis server, so I couldn't add one for this.
=> Fixes #1715: Adds multicursor paste

src/actions/commands/actions.ts
So pretty much the issue is that here, because nothing pops up, vscode doesn't think we're in the "find all references" context, and lets vscodevim capture keystrokes again.
Thus, all we need to is call API calls that close stuff when the user presses `<Esc>` in normal mode. Doesn't seem to have any performance impact, and fixes an annoyance.
=> Fixes #1436: extension prevents 'find all references' pop-up from closing through <esc> if it's empty.

src/mode/modeHandler.ts
So this one is kinda weird.
I'll put my main comments in the code review.
=> Fixes #1674: repeating . with characters like " or ) leaves cursor in wrong place

src/actions/commands/actions.ts
Specifically, this one: https://github.com/VSCodeVim/Vim/issues/1467#issuecomment-303904886 and the 4th bullet point here: https://github.com/VSCodeVim/Vim/issues/1467#issuecomment-303909797
=> Fixes #1749: <D-d> in insert mode doesn't work when the word isn't by itself

src/actions/operator.ts
Fix was just like @johnfn said. Only thing was that I needed to move the single line comments after the multiline comments
=> Fixes #1750: gq doesn't work for JSDoc type comments

src/actions/commands/actions.ts, src/actions/operator.ts, test/mode/modeNormal.test.ts
* Fixes d2d not working.
* Hopefully fixes gq once and for all.
=> More v8 patches

src/actions/commands/insert.ts
When a language specific syntax setting overrides the user's configuration settings, I'm not sure how to handle that.
This fix handles this specific issue, but there may be more bugs surrounding this kind of stuff.
=> Fixes #1768: Backspace deletes more than one tab when tabs are mandated by language specific settings

src/neovim/nvimUtil.ts
Pretty much, the problem was that we convert the indentation to spaces (if that's the user setting).
However, the problem raised here: https://github.com/VSCodeVim/Vim/pull/1769 will still be present here (ie: we don't detect language-specific indentation settings).
=> Fixes #1760: Deindenting not working properly with neovim ex-commands

src/actions/commands/actions.ts, src/mode/modeHandler.ts, test/mode/modeNormal.test.ts, test/mode/modeVisual.test.ts
We just need to set the register to the default register before we yank.
=> Fixes #1743: Fixed pasting over visual mode with named register overwriting the named register

src/actions/commands/actions.ts
This PR binds `C-w v` to `workbench.action.splitEditor`, achieving similar functionality to what happens in Vim.
I've previously manually maintained a shortcut to match the Vim vertical split shortcut, but thought it might be helpful to add it for everyone else. Please close if it's not a complete fit, I'm happy to maintain the shortcut configuration myself.
At the moment it's just the binding, had a look at the automated tests and not entirely sure how I'd go about testing it. If this is required, some rough direction would be greatly appreciated.
Keep up the great work, this is one of the best Vim modes I've ever used, if not the best.
Relates to #1451.
=> Vertical split shortcut keys

src/cmd_line/main.ts
We were doing an incorrect check for `.isEmpty()` that occurred as a result of incomplete command line parsing.
=> Fixes #1786: Adds relative line ranges

src/actions/commands/actions.ts, src/actions/motion.ts
We just need to wait for the cursors to come back before continuing.
=> Fixed #1803: zc automatically reopens folds if the fold is performed in the middle.

package.json, src/cmd_line/commands/file.ts
This does require installing another dependency though...
See this discussion: https://github.com/nodejs/node/issues/684
=> Fixes #1200: :e doesn't expand tildes

extension.ts
So I'm currently fixing the issue by simply getting rid of the offending code. So pretty much what happens when you remove that code is that when the file changes on disk, an undo simply reverts back the disk file change first, which I think is perfectly fine behavior.
=> Fixes #1814: Undo history getting deleted when file changes

src/history/historyTracker.ts
For whatever reason, we were cutting off the history kept.
https://github.com/VSCodeVim/Vim/issues/1589#issuecomment-305946543
This simply removes that line!
=> Fixes #1794: Undo not undoing all changes

src/cmd_line/commands/quit.ts
To be honest, I'm not able to properly test this locally. As @misoguy notes over here, `workbench.action.closeEditor` has some weird behavior when running in local development mode.
However, it's only one if statement. How badly could I possibly mess this up?
=> Fixes #979: Adds q! to close without saving

extension.ts, package.json, src/cmd_line/commands/file.ts, src/cmd_line/subparser.ts, src/cmd_line/subparsers/file.ts, test/extension.test.ts
I just copied @rebornix 's keybindings into package.json.
Fixes #754 and fixes #1351
=> WIP Fixes #754: Adds j,k,o,<Enter>, gg, G, ctrl+d, and ctrl+u commands for navigating inside the file explorer

src/actions/commands/actions.ts, src/mode/modeHandler.ts
Based off @rebornix's changes.
We just need to make sure we wait for the right cursor after doing the view change. Otherwise, the cursor change that's a result of `revealCursor: true` isn't propagated, and we get stuck once we're at the edge.
Fixes #907,
=> Select in visual mode when scrolling

src/actions/commands/actions.ts, src/cmd_line/commands/only.ts, src/cmd_line/subparser.ts, src/cmd_line/subparsers/only.ts
I added the [`:only` command and shortcuts](http://vimdoc.sourceforge.net/htmldoc/windows.html#CTRL-W_CTRL-O) (`<c-w>o`, `<c-w><c-o>`).
=> Added :only command and corresponding shortcuts

package.json, src/configuration/configuration.ts, src/mode/modeHandler.ts
Change it with `vim.mouseSelectionsGoesIntoVisualMode`
=> Fixes #1871: Adds configuration option to go into visual mode upon clicking in insert mode

test/operator/comment.test.ts
This PR: Microsoft/vscode#28238 inserts spaces inside block comments, which affects VSCodeVim tests.
=> Update tests due to VSCode PR 28238

src/actions/commands/actions.ts, src/mode/modeHandler.ts, test/mode/modeVisual.test.ts, test/mode/modeVisualBlock.test.ts, test/mode/modeVisualLine.test.ts, test/register/register.test.ts, test/testSimplifier.ts, test/testUtils.ts
When yanking to clipboard, the selection should also reset to normal
=> Ctrl-C should copy to clipboard in visual mode - fix for #1896

test/mode/normalModeTests/dot.test.ts, test/mode/normalModeTests/motions.test.ts
This comment was put in the code too, but this is my rationale:
```
// These "remembering history between editor" tests have started
// breaking. Since I don't remember these tests ever breaking for real, and
// because they're the cause of a lot of flaky tests, I'm disabling these for
// now.
```
=> Remove flaky tests

src/actions/textobject.ts, src/common/motion/position.ts
See individual commit messages and associated issues for details.
=> Improvements to paragraph text objects.

gulpfile.js
This PR resolves #1961.
Windows doesn't have unix commands like `xargs`, `find`, so it fails to run prettier.
This change ahieves the same thing using only git commands, so it will be work also on Windows.
=> Make prettier work on Windows

src/mode/modeHandler.ts
This can happen if you interact with the editor while vim mode is still
loading.
=> Fix deref of undefined race on startup.

README.md, package.json, src/actions/plugins/easymotion/easymotion.cmd.ts, src/actions/plugins/easymotion/easymotion.ts, src/actions/plugins/easymotion/markerGenerator.ts, src/actions/plugins/easymotion/registerMoveActions.ts, src/configuration/configuration.ts, src/mode/modeHandler.ts, test/plugins/easymotion.test.ts
Make easymotion work even better.
=> Easymotion improvements

src/actions/commands/actions.ts
Fixes #1089.
Dependency: https://github.com/Microsoft/vscode/pull/33715
=> Implement '' and ``.

src/mode/modeHandler.ts
At the moment even when `mouseSelectionGoesIntoVisualMode` set to `false` then the visual mode is still turned on when the mouse is clicked or dragged.
This PR ensure that if the `mouseSlectionGoeIntoVisualMode` is `false` then regardless the current mode, visual mode will not be not turned on.
=> Correct behavior of mouseSelectionGoesIntoVisualMode

src/mode/modeHandler.ts
This is a cleaner Pull request for fixing this issue, replacing closed Pull request #2029. Please reference the comments & details in issue #1860 for info, including the problem definition & solution justification.
@nguymin4 - Per your comments on #2029, I have implemented this fix using `Array.map()`.
=> Fix for issue #1860, visual multicursor movement.

ROADMAP.md, src/actions/commands/actions.ts, src/history/historyTracker.ts
This is a PR to resolve issue #1248.
I'm not sure whether the `historyTracker` class can be properly unit-tested, as I couldn't find any related tests. If it's possible, I'd love to get some suggestions & backfill those tests.
=> Fixes #1248: support for '., `., and gi commands.

src/actions/commands/actions.ts
This is a fix for the g, and g; commands, which currently have offset issues per #1824.
=> Fixes #1824: g; and g, commands.

src/actions/commands/actions.ts
Use the normal selection in insert mode.
This fixes #1951. Selection in insert mode seems to be
specific to this plugin and is not easily possible in normal Vim.
=> Bugfix #1951: text selection in insert mode

extension.ts
This MIGHT help with the undo issue (#2007)
This is a change I had made before. It was reverted in this PR:
https://github.com/VSCodeVim/Vim/pull/981
The problem was that when switching tabs we would dispose before. Now the check operates a little differently and only disposes if the vscode workspace has NO idea what this file is (all instances of this file in a tab are closed)
=> Dispose modehandler if NO documents match the modehandler document anymore

README.md, extension.ts, package.json, src/actions/commands/actions.ts, src/cmd_line/main.ts, src/configuration/configuration.ts
Just a simple option to show the colon character at the start of the command line box.
Something I've been missing from vim itself, maybe others would find this useful too. If set to false the behavior should be the same like now.
I find it helps distinguish the vim command line with the command palette and the file search boxes.
=> An option to show the colon at the start of the command line box

src/cmd_line/main.ts
This makes the command line behave like the builtin VSCode command palette and fuzzy file opening box. It also makes a lot of sense to not block the user until he reaches the mouse and refocuses on that box just to be able to close it. Vim users don't like to leave their home row :-)
=> Change ignoreFocusOut to false for the command line

package.json, src/cmd_line/commands/file.ts
Fixes #1877
I could test this commit on my local machine and it works.
But the `gulp watch` task always complains:
```
src/cmd_line/commands/file.ts(75,44): error TS2339: Property 'showOpenDialog' does not exist on type 'typeof window'.
```
Do I have to update the typings somehow?
How could I do that?
=> added `showOpenDialog` when typing emtpy e

src/actions/commands/actions.ts
Fixes #2103.
The VSCode command `editor.unfold` didn't support `direction` yet (`editor.fold` did).
I added it to VSCode for consistency reasons, but that breaks the VIM extension as unfolding with multiple levels is expected to work down, not up.
=> Use 'editor.unfold' with direction: 'down'

src/actions/commands/actions.ts
```
src/actions/commands/actions.ts(3230,11): error TS2345: Argument of type '{ type: "replaceText"; text: string; start: Position; end: Position; position: Position; }' is not assignable to parameter of type 'Transformation'.
Object literal may only specify known properties, and 'position' does not exist in type 'ReplaceTextTransformation'.
```
=> fix(build): position does not exist for replacetexttransformation

.travis.yml
As discovered by @parkovski in https://github.com/VSCodeVim/Vim/pull/2123, prettier is a different version on Travis. I suspect it's because we are using npm v3 on Travis. Upgrade it to use lts/carbon (node v8.9.1 // npm v5.5.1) as npm@5 introduced support for package-lock.json
=> fix(travis): use lts/carbon (v8.9.1) for travis

src/state/searchState.ts, test/mode/modeNormal.test.ts
- Fixes #2086 and #2101 by adding the 'm' flag to the search regex, which causes `^` and `$` to match per-line instead of per-file.
- Implements #2100 by stripping all `\c` and `\C` from the search pattern and changing `ignorecase` for that search based on the first one found - this mimics vim's behavior.
Substitute is not affected by either of these issues - `^` and `$` already work there, and `/i` to override case is already implemented - vim doesn't support `\c` there.
=> Fix ^, $, add case sensitivity override in search

src/actions/base.ts, src/actions/operator.ts, src/mode/modeHandler.ts, src/mode/remapper.ts
=> Fix remapping keys to actions with "mustBeFirstKey", fixes #2216

src/cmd_line/subparsers/substitute.ts, test/cmd_line/subparser.substitute.test.ts, test/cmd_line/substitute.test.ts
This PR addresses the issue where the slash `/` character could not be substituted using standard Vim syntax. I have added tests for the substitute and subparser substitute to cover this functionality.
=> Fix #2155, Fix #2133: escape delimiter substitute

src/cmd_line/commands/file.ts, test/cmd_line/vsplit.test.ts, test/testUtils.ts
This PR fixes the vertical split command, which was a regression caused by PR #2067.
I have added unit tests for the `:vs` and `:vsp` commands.
=> Fix #2148: vertical split command

src/mode/modeHandler.ts
Our decorations were stupidly done. I just copied over the relevant CSS from the actual cursor in VSCode. Now they should be indistinguishable.
Before:
After:
=> Fixed incorrect styling of 'fake' cursors

package.json
Hi, VS Code dev here! ✋ 
Due to https://github.com/Microsoft/vscode/commit/234e2db9d7cb28bca2e07290b2b587bbea42b649, the `when` context keys for `list.*` commands need to be updated.
This should be merged ASAP. It is compatible with the current stable release and fixes the VIM integration for the upcoming November release.
=> Update `list.*` command keybindings

src/cmd_line/commands/file.ts
Changes:
- When using a hash bang, return after the file is reverted. This prevents opening an open-file-dialog.
Fixes:  #2172
=> Do not open open file dialog when calling `:e!`

src/actions/commands/actions.ts
Closes #2221 - simple change, just adds `C-[` as a key that can escape replace mode.
=> Add C-[ to Replace Mode escape

extension.ts, src/configuration/configuration.ts, src/configuration/notation.ts, src/configuration/remapper.ts, src/mode/modeHandler.ts, src/mode/modes.ts, test/notation.test.ts
* move logic out of modeHandler into configuration simplifying modeHandler, and simplifying accessing keybindings/remappedKeys settings as the keys will already be normalized to angle bracket notation.
* update status bar text to be more like vanilla vim
=> refactor: normalize keys when loading configuration

src/cmd_line/commandLine.ts, src/cmd_line/parser.ts, src/error.ts, src/mode/modeHandler.ts
* show cmd-line errors in status bar instead of informational window
* adds E492: no editor command error
=> fix: show cmd-line errors in status bar. add new E492 error

extension.ts, src/cmd_line/commands/file.ts, src/configuration/configuration.ts, src/configuration/notation.ts, src/error.ts, test/notation.test.ts
**What this PR does / why we need it**: fixes circular dependency between notation and configuration
**Which issue(s) this PR fixes** #2275 
=> fix: fixes circular dependency between notation and configuration

src/cmd_line/commandLine.ts, src/common/matching/matcher.ts, src/configuration/configuration.ts, src/mode/modeHandler.ts, test/configuration/notation.test.ts
**What this PR does / why we need it**: 
Fixes VSCode warnings when retrieving configurations without resource
=> Fix: Warnings when retrieving configurations w/o resource

extension.ts, src/actions/commands/actions.ts, src/mode/mode.ts, src/mode/modeHandler.ts, src/mode/modes.ts
- fixes status bar not updating correctly following disabling of vim (through `toggleVim`).
- instead of ad-hoc handling `toggleVim`, creating a new `DisabledMode` which aligns with our architecture
- reorganize `modes.ts` to same order as mode enum.
=> fix: status bar not updating following toggle

extension.ts, src/mode/modeHandlerMap.ts, test/mode/modeHandlerMap.test.ts
code-cleanup. move `modehandlermap` to it's own static class.
=> refactor: move modehandlermap to own class

src/mode/modeHandler.ts
This PR make ```<C-d>``` disabled by default, unless users explicitly defined ```<C-d>:true``` in ```handleKeys```.
> handleKeys config trumps usectrlkeys conifg 
This configuration
```
"vim.useCtrlKeys": false,
"vim.handleKeys": {
"<C-d>": true
}
```
It should have ```<C-d>``` working as **Vim move page half down**, now it behaviors as ```add selection to next find match```.
This PR modified [this line](https://github.com/VSCodeVim/Vim/blob/master/src/mode/modeHandler.ts#L289), eventually results in this logic:
|                             | useCtrlKeys = true                     | useCtrlKeys  = false                |
|--------------------- | ------------------------------|-----------------------------|
| handleKeys = true | VSCodeVim move page …
=> fix: <C-d> remapping disabled by default. functionality controlled by "handleKeys"

src/actions/base.ts, test/baseAction.test.ts
When `BaseAction.couldActionApply` slices the `keys` array it assumes it is one-dimensional (e.g. `['a', 'b']`). This pull request fixes it so that it also works when the `keys` array is two-dimensional (e.g. `[['a', 'b'], ['c', 'd']]`).
=> Fix BaseAction.couldActionApply to work with two-dimensional keys array

README.md
I was having trouble getting my Mac to key repeat, I did some quick research and found https://github.com/Microsoft/vscode/issues/31919. The issue was that I had a global default that was true, which was overriding the application level `com.microsoft.VSCode` setting.
Fixes key repeat for Mac users that already have a global default set for `ApplePressAndHoldEnabled`.
https://github.com/VSCodeVim/Vim/issues/2315
There might be a better way than resetting the global default.
=> Update README for Mac key repeat

extension.ts, src/configuration/configuration.ts, src/mode/modeHandler.ts, src/state/vimState.ts
**What this PR does / why we need it**: We need to `setContext` following a switch of the active text editor. 
**Which issue(s) this PR fixes** #730
=> fix: closes #730. setcontext when switching active text editors

package.json
Users installing a vim plugin will probably expect Ctrl+D to work like
vim. So this changes the default settings to do that.
Fixes #2312
I tried adding tests, but then realized that <kbd>Ctrl+D</kbd> / <kbd>Cmd+D</kbd> doesn't actually work as per https://github.com/VSCodeVim/Vim/issues/1348 and I've been using the workaround posted there.
=> Default to vim behaviour for Ctrl+D

src/cmd_line/commandLine.ts
https://github.com/VSCodeVim/Vim/issues/2346#issuecomment-361826197
explains the problem and the fix.
=> Fixes #2346

extension.ts, src/cmd_line/commandLine.ts, src/mode/modeHandlerMap.ts, src/neovim/neovim.ts, src/state/vimState.ts
**What this PR does / why we need it**: Properly kills neovim processes on exit. Refactoring of neovim to a class. 
**Which issue(s) this PR fixes** #2038
=> fix: clean-up neovim processes. closes #2038

src/cmd_line/commands/file.ts
**What this PR does / why we need it**: on any file command-line (`:e/vsp/vs filename` creates filename if it doesn't exist.
**Which issue(s) this PR fixes** #2274
=> feat: create file if file does not exist. closes #2274

package.json, src/actions/commands/actions.ts, test/mode/modeInsert.test.ts, test/mode/modeNormal.test.ts, test/mode/modeReplace.test.ts, test/motion.test.ts
**What this PR does / why we need it**: Continuation of https://github.com/VSCodeVim/Vim/pull/2295. Haven't heard back from @gibranrosa, and so creating a new PR with his changes. 
**Which issue(s) this PR fixes**. #1787 
**Special notes for your reviewer**: Don't have an `insert` key on my keyboard to test.
=> feat: implements usage of `insert` to toggle between modes (as per #1787)

src/cmd_line/commands/tab.ts
Updates `:tabm` to use `moveActiveEditor` so that it works.
**Which issue(s) this PR fixes**:
Fixes #2401 
I did not write automated tests for this because I could not figure out how to inspect an editor index position. Does anyone know how to access that information?
=> Fix :tabm to use moveActiveEditor command

src/cmd_line/commands/file.ts
**What this PR does / why we need it**: there was a case where a file would get overwritten. specifically, when we are trying to find a file ("hello"), we search for the file with the same extension ("hello.ts"), and if that exists, we overwrite the file :(
**Which issue(s) this PR fixes** #2408.
=> fix: don't overwrite file if file exists. fixes #2408

src/cmd_line/commands/file.ts, src/cmd_line/commands/tab.ts
Use `fspath` as that is corresponds to file system path
**What this PR does / why we need it**: Fixes errors with Windows pathing when opening/creating new files through the vim cmd-line.
**Which issue(s) this PR fixes**: #2422
=> fix: use 'fsPath'. closes #2422

src/actions/commands/actions.ts, src/mode/modeHandler.ts, src/util.ts, test/testSimplifier.ts
This should hopefully fix the ctrl-e problems, as well as fix performance for it, so long as it doesn't create race conditions elsewhere.
Fixes #1943, #1985,
=> Set the timeout to 0 for waitforcursorupdatestopropagate

src/mode/modeHandler.ts, test/mode/modeVisual.test.ts
Fix the selection range in search in visual mode.
When you start search by `/` or `?` in visual mode, the start of selection remains the position you started the visual mode in vim, but it reset to the position you started the search in VSCodeVim without this fix.
See the issue #2406 for detail.
fixes #2406 
This is my first pull request in github.
Although I read the contributing guidelines, I am sorry if something is missing.
=> fix: selection in search in visual mode #2406

src/mode/modeHandler.ts, src/state/vimState.ts
We need it to be part of vimstate because we need state that persists between multiple calls to handleSelectionChange.
=> Readds vimState.lastClickWasPastEOL. Fixes #2404

src/cmd_line/commands/tab.ts
Previously there was a bug in VSCode which prevented me from doing:
```
await
vscode.commands.executeCommand('workbench.action.openEditorAtIndex1')
```
The most recent release of VSCode (1.21.0) fixes the bug. See
https://github.com/Microsoft/vscode/issues/44636
This PR ties up a loose end because the latest VSCode release fixed a bug.
No specific issue though I mentioned this in https://github.com/VSCodeVim/Vim/pull/2400#discussion_r170515948
This change will impact users who use `:tabn` or `:tabfirst` but do not have the latest version of VSCode. For such users, `:tabn` or `:tabfirst` will cause the command line (`:`) to be disabled until VSCodeVim is restarted. What is …
=> await openEditorAtIndex1 command

gulpfile.js, package-lock.json
When running `gulp`, prettier would sometimes never return when no `files`is empty.
=> fix: don't call prettier when no files updated

src/editorIdentity.ts
As has been noted previously, I think the issue behind this second "undo" problem is because we separate EditorIdentity not only by  `fileName`, but also by `viewColumn`. This is problematic for several reasons.
1. The `viewColumn` isn't how we think about what our current editor is. For example, if one drags a file from column 1 to column 2, one'd expect that to be the same editor.
2. We'd expect most state to be shared from a file open in 2 different columns. For example, undo doesn't really make sense (we can't undo locally; we're not building a collaborative editor here).
Looking at these 2 problems, we arrive at what is the fundamental problem: There can be multiple `undoStates` for the same file, indexed by `viewColumn`. Here are a couple of cases where this is a problem.
Case 1: …
=> Hopefully fixing the rest of our undo issues

src/actions/motion.ts, test/mode/modeVisual.test.ts
Fixes the logic for selecting within pairs of braces in certain specific cases:
* Nested braces where the outer closing brace has no leading whitespace and the brace above does
* Closing braces indented by only one space
#2569
=> Fixes #2569. Fix vi{ for nested braces.

src/actions/commands/actions.ts, test/mode/modeVisual.test.ts
I expect the same behavior as original Vim :)
* `vv` -> normal mode
* `VV` -> normal mode
* `<C-v><C-v>` -> normal mode
* `vV` -> visual line mode
* `v<C-v>` -> visual block mode
* `Vv` -> visual (char) mode
* `V<C-v>` -> visual block mode
* `<C-v>v` -> visual (char) mode
* `<C-v>V` -> visual line mode
I could not find the issue.
=> [Fix] Transition between v,V,<C-v> is different with original Vim behavior

src/actions/commands/actions.ts, test/mode/modeVisualLine.test.ts
Thanks for great work.
I'm using Vim for primary text editor but I have to use VSCode at work.
But I found this extension is awesome because Vim like keybinding helps me a lot to concentrate :)
In original Vim behavior, `p` command in visual-mode replaces current text.
VSCodeVim also does it but it is slightly different.
Unnecessary newline is inserted before the text when the text is yanked as linewise.
1. Yank current line's text by `yy`
1. Replace current line's text by `Vp`
In original Vim, it does not change the text (the buffer is marked modified, though).
But VSCodeVim inserts a newline before the current line.
No exact issue yet.
But the problem is touched by #1991 comment.
> Note: there are extraneous newlines in the VSCode output, but I believe this is a separate issue
=> [Fix] Don't add beginning newline of linewise put in visual-mode

src/actions/textobject.ts, test/mode/modeNormal.test.ts
This fixes aW behavior at the WORD (big word) of the end of line or the end of document.
Fixes #2571
=> [Fix] aW doesn't work at the end of lines

src/actions/commands/actions.ts, test/mode/modeVisual.test.ts, test/mode/modeVisualLine.test.ts
Please see #2587
This PR covers characterwise and linewise.
Blockwise put seems unimplemented (also in normal-mode), so this PR does not care.
Fixes #2587
=> [Fix] p in visual-mode should save last selection

package.json, src/actions/commands/actions.ts, test/mode/modeNormal.test.ts
Nothing happened when typing `<C-h>` in search in progress mode.
See #2592 for the details.
Fixes #2592
=> [Fix] <C-h> should work as same as <BS> in search mode

src/mode/modeHandlerMap.ts
VSC only automatically disposes resources when an extension is shutdown. Since every time a new ``TextEditor`` is opened, we also instantiate a new ``ModeHandler`` (along other Disposables like neovim processes), those pile up and will not get properly disposed until we get shutdown one way or the other.
One issue this is causing is that neovim processes are not being cleaned up and hang around until our shutdown.
Thus, every time we remove a ``ModeHandler``, we manually dispose it to free its resources.
Fixes #2558.
=> fix: Manually dispose ModeHandler when no longer needed

src/actions/commands/actions.ts, test/mode/modeVisualBlock.test.ts
Currently `o` command in visual block mode is missing.
This PR adds the command.
Fixes #2456
=> Add o command in visual block mode

src/actions/commands/actions.ts, test/mode/modeVisualLine.test.ts
This PR fixes `p` command to update register content, when it is executed in visual-mode.
Please see #1991 for the original Vim's behavior.
NOTE: this PR only fix to update register content.
`p` command is yet not Vim compatible behavior.
For example, the buffer content is:
```
hello
world
```
And cursor position is line 1, and type `ddVpP` results in:
```
world
hello
```
Unnecessary newline at the end.
Expected is:
```
world
hello
```
But this is another problem.
I will fix it later at the another PR.
Fixes #1991
=> [Fix] p in visual-mode should update register content

src/actions/commands/actions.ts, test/mode/modeVisualLine.test.ts
The fix of #2579 was incomplete.
Because it didn't care the line at the end of document.
No
=> [Fix] p won't work in linewise visual-mode at the end of document

src/actions/commands/actions.ts, src/common/motion/position.ts, test/mode/modeVisualLine.test.ts
```
hello
world
```
Typing `ggddVp` results in
```
world
hello
```
The behavior of the issue (#2608) was changed by #2601, but it's wrong yet.
After this PR is merged, the result is (no newline at the beginning or end)
```
world
hello
```
Fixes #2608
=> [Fix] p in visual line appends unnecessary newline

package.json, src/actions/commands/actions.ts
Some commands are even implemented but only keymappings are missing.
This PR makes it to work just to add the keymappings to invoke the implementation.
Fixes #2582, #2467
=> Add missing window keys (<C-w><C-[hjklovq]>)

gulpfile.js
https://github.com/VSCodeVim/Vim/pull/2599 updates the build to no longer emit files when a transpile fails. however, the builds still continue to pass.  This PR makes it fail as soon as there is an error thus making it more obvious what's broken.
=> fix: immediately exit if there is an error on ts

.travis.yml
As per https://docs.travis-ci.com/user/customizing-the-build#Customizing-the-Build-Step, for scripts in `script`, build continues until the end regardless of returned exit codes. 
If build fails, I don't think we should even bother with running tests. Moving build and forceprettier to `before_script`.
=> fix: immediately exit travis on build error

src/actions/motion.ts, test/mode/modeNormal.test.ts
When using ]) and ]} motions combined with change ('c'), delete ('d'), or yank ('y') operators, vim doesn't include the closing parenthesis/bracket in the operation. The same does not apply the equivalent backwards motions ( '[(' / '[{' )
fixes #2670
=> Fixed difference in behavior for ]) and ]} when combined with certain operators

src/actions/commands/actions.ts, src/actions/operator.ts, src/mode/modeHandler.ts, src/transformations/transformations.ts, test/mode/modeNormal.test.ts
Changes the `cc` and `S` commands to delete the whole line's contents and reindent it when `autoindent` is enabled. Originally these commands would only delete the text after the indent, which could leave the cursor inside the untouched indent text rather than moving it to the end of the indent.
I think that since commands like `o` already 'reindent' the new line that `cc` and `S` should too, and this implementation also moves the cursor to the end of the line automatically.
fixes #2497
=> Fix autoindent on cc/S #2497

src/mode/modeHandler.ts
Allow remappings from mocked configurations during testing.
fixes #2732 
All tests seems to mock the configuration, so user configurations no longer bork the tests.
=> Don't ignore mocked configurations' remaps during testing.

extension.ts, src/cmd_line/commandLine.ts, src/cmd_line/commandLineHistory.ts, src/configuration/remapper.ts, src/mode/modeHandler.ts, src/util/util.ts, test/cmd_line/commandLineHistory.test.ts, test/cmd_line/sort.test.ts, test/cmd_line/substitute.test.ts, test/cmd_line/tab.test.ts, test/cmd_line/vsplit.test.ts, test/cmd_line/writequit.test.ts, test/testConfiguration.ts
bug fixes:
* resolve issue where if the command line history file was empty, it would fail to load
* delete command line history file if it is corrupted instead of infinitely retrying
* resolves issue where max history as defined by `configuration.history` was not being honored
refactor:
* make `commandLineHistory` and `commandLine` real classes instead of static methods
=> fix: handle when commandLineHistory is empty

README.md, extension.ts, package.json, src/actions/commands/actions.ts, src/cmd_line/commandLine.ts, src/cmd_line/commandLineHistory.ts, src/configuration/configuration.ts, src/configuration/iconfiguration.ts, src/mode/mode.ts, src/mode/modeHandler.ts, src/mode/modes.ts, src/state/recordedState.ts, src/state/vimState.ts, src/transformations/transformations.ts, test/cmd_line/commandLineHistory.test.ts, test/testConfiguration.ts
Fixes #779
This is our most thumbs upped/sad faced issue currently!
I did not do any complex or majestic refactoring. I mostly took what worked well with searching and applied it to the commandline. Works pretty well!
=> Move commandline to status bar to allow history navigation

src/actions/commands/actions.ts
The issue we ran into is there are inconsistency of start/end between vscode's selection and vimState's internal one. As we already track the real position in Visual Mode (as it's controlled by vimState), I use `vimState.cursorPosition` instead of `editor.selection.end` .
=> Fix #2766.

src/configuration/notation.ts
Simplify `normalizeKey()`. Leverage the existing map instead of the additional `if` statements.
=> refactor: simplify normalizekey() by using existing map

src/actions/base.ts, src/actions/operator.ts, src/configuration/remapper.ts, src/mode/modeHandler.ts, src/state/recordedState.ts, test/configuration/remapper.test.ts
* This PR addresses issue #2759 to enable remapping of numbers (e.g. remapping `0` to `^`). Although this PR enables the remapping of ALL numbers, I don't see a real scenario where somebody would want to remap numbers 1-9 as that would override the default count behaviour for motions and operators. 
* Adds more checks for remapped configurations ignoring all that are invalid (e.g. duplicate or missing an `after` or a `command`)
#2759
=> fix: enable remapping of numbers

README.md, extension.ts, package.json, src/cmd_line/commandLine.ts
fixes #2773
@jpoon I think that this doesn't add too much to maintain and was functionality that existed before
=> Allow for quickpick commandline usage

src/actions/commands/insert.ts, test/mode/modeInsert.test.ts
"Fixes" the behavior of <kbd>&lt;C-u&gt;</kbd> in Insert mode.
Fixes #2804
See issue for reasoning, and let me know if I've missed anything or if you disagree. 🙂
=> feat: Update <C-u> insert mode behavior

README.md, src/configuration/iconfiguration.ts, src/configuration/remapper.ts
Enables the syntax specified in #2806 to work.
#2806.
**Notes:**
This simply makes the "command" object in `IKeyRemapping` be either the old object or a string. If it's a string, we then interpret the string as `{ command: str; args: [] }`.
=> Added ability to register commands using simple strings (fixes #2806)

src/cmd_line/commands/substitute.ts
Fixes bug with interactive-substitute implementation that resulted in the wrong number of characters getting replaced.  
Ex
test
test
test
`%s/test/1/gc`
fixes #1010 
=> fixed buggy interactive substitute replacements

src/cmd_line/node.ts
fixes #2858
I believe that when this was in the quickpick, it was still an error scenario yet, was "caught", ignored, and then updateView was explicitly called so it worked "ok". Now it doesn't error and goes to a valid line.
This used to be logged every time you ran a :$ or :% command
```
error: ModeHandler: error handling key=
. err=Error: Illegal value for `line`.
```
=> Fixes $ and % commands

src/actions/plugins/surround.ts
When deleting surroundings using <kbd>ds</kbd>, this plugin doesn't recognize it as being handled, so the command list remains what it was before surround.ts handled it. This pull request fixes this by clearing the command list when a surround command finishes.
N/A
A better way to fix this bug would be to somehow have [this line of code](https://github.com/VSCodeVim/Vim/blob/e12c6f35edb35d777e5f2f8f1770057cb1e83ce1/src/mode/modeHandler.ts#L330) executed. However, I wasn't able to figure out how, so I came up with this workaround.
=> Workaround surround bug

ROADMAP.md
Adds an undocumented shortcut to the roadmap docs.
n/a
`~` works for case switching in visual mode, so I've assumed that the docs just aren't up to date.
It looks like the description text fell into the keyboard shortcut column... and the keyboard shortcut wasn't yet provided.
=> Roadmap doc fix for visual mode case switching

extension.ts, src/mode/modeHandler.ts
This call takes 2-5ms on my machine....that is a pretty huge for how easy this was to remove...
=> Cache mode so that calls to setContext is minimized

src/actions/motion.ts
Improved the foldfix setting behaviour for improved performance, reduced bugs, and hopefully easier extension and addition of more fold commands in the future.
Should fix #1855 and fix #2163, though it may require more testing. `gulp test` passed all tests with and without forcing `configuration.foldFix` to `true`, but more tests may need to be added.
One bug this may have introduced is flickering when prefixing a downward movement command with a large repeat. This is indicated in a comment inside `MoveDownFoldFix` but is still much better behaviour than before where an infinite loop would begin. To fix it we would need a more reliable way to detect the  last visual line of a file …
=> Improve foldfix performance and potentially fix some bugs(#1855 #2163)

extension.ts, src/mode/modeHandler.ts
Reverts VSCodeVim/Vim#2861
Causes some really bad things to happen, the easiest one is when you do ```:``` or search with ```/```
=> Fix regression with setContext in modeHandler

gulpfile.js
I initially created a fork of the image as I wanted `1.15.0` of the changelog generator. Now that ferrarimaro has pushed it up that version up, using ferrarimaro's image as it's more official than my fork. 
https://hub.docker.com/r/ferrarimarco/github-changelog-generator/tags/
=> fix: use ferrarimarco's image instead of my fork to generate changelog

src/configuration/remapper.ts
=> Fix issue with incorrectly finding and triggering certain remappings

src/neovim/neovim.ts
Improves neovim status bar reporting on a successful command execution
=> Improve neovim command execution status reporting in status bar

package.json, src/cmd_line/commandLineHistory.ts, src/util/util.ts
Fixes #2799 
Just tested on 3 platforms
Windows:
```C:\Users\xxxxx\AppData\Local\VSCodeVim\VSCodeVim\Cache```
MacOS:
```/Users/xxxxx/Library/Caches/VSCodeVim```
Linux:
```/home/xxxxx/.cache/VSCodeVim```
=> Move commandline history to XDG_CACHE_HOME or %APPDATA%

README.md
To use native functions for Ctrl the vim.useCtrlKeys needs to be false
Update the readme FAQ
=> Updating README FAQ

.github/CONTRIBUTING.md, gulpfile.js, test/index.ts
Add --grep flag to `gulp test` for faster testing and iteration. The flag --grep takes js regex as a string and filters by test and test suite names. Also works with the default task since it includes `gulp test` (eg `gulp --grep foldFix`).
=> Add --grep flag to gulp test

extension.ts, src/mode/modeHandler.ts
There was not actually any issue with this that I can detect. I believe the reason I reverted it was that I upgraded VSCodeVim, and did not click Reload, so the contexts were out of sync. Upon restarting vscode, the extension would have worked properly WITH the performance improvements enabled (this PR).
=> Reenable change that minimized the calls to setContext

README.md
Currently the TOC points to `#emulated-plugins` but the actual anchor is `#-emulated-plugins`
Fixes the Emulated Plugins link in the README TOC
None, thought it was simpler to just submit a PR
I hope you're having a lovely day :)
=> Fix Emulated Plugins TOC link in README

package-lock.json, package.json, src/cmd_line/commands/tab.ts
Vscode 1.25 removed the command workbench.action.openLastEditorInGroup.
Change tablast to workbench.action.lastEditorInGroup to fix this issue
Fixes #2813
=> Fix :tablast breaking in vscode 1.25 #2813

README.md, extension.ts, package.json, src/configuration/configuration.ts, src/configuration/iconfiguration.ts, src/mode/modeHandler.ts, src/taskQueue.ts, test/testConfiguration.ts
* Enable auto-complete when trying to configure statusbar colors and custom cursors for mode. 
* Remove need for having to create a map of the custom cursors every tick. 
=> fix: use full path for configs

src/cmd_line/commands/file.ts
=> fix: files with extensions not being auto-created. closes #2923.

ROADMAP.md
Typo error in the description of commands in ROADMAP
=> Fix Typo in ROADMAP

src/cmd_line/commands/file.ts
https://github.com/VSCodeVim/Vim/issues/2966
This PR makes `gf` work as-expected. (Currently, `gf` just shows an error message.)
Fixes #2966 
None.
=> Fix `gf` showing error for files which exist

README.md
Just need a dash due to the emoji:`#-emulated-plugins`
=> Fix emulated plugins link in README

extension.ts
I implemented the new Jump Tracker that handles `<C-o>` behavior. @Chillee and I noticed a few issues when trying to jump from or to files that are auto closed.
One use case, if you close all editors, then open temporary editor, then jump to definition to open another editor (auto-closing the previous editor), `<C-o>` often doesn't work. vscode ends up sending two separate `vscode.window.onDidChangeActiveTextEditor` events, once for closing one editor, once for opening the new editor, where as we were expecting just one event.
Another similar use case from @Chillee has the same cause:
```If you create a new tab that isn't saved, and you just switch back to the original tab
`ctrl-o` gets you stuck switching between the 2 tabs
So you're in file A
you …
```
=> Fixed Jump Tracker jumps when jumping from a file that auto closes

extension.ts, src/actions/commands/insert.ts, src/completion/lineCompletionProvider.ts, test/completion/lineCompletion.test.ts
This adds support for Vim's line completion mode:
* http://vimdoc.sourceforge.net/htmldoc/insert.html#i_CTRL-X_CTRL-L
The line completion hotkey `<C-x><C-l>` opens up a Quick Pick menu. Standard autocompletion wasn't used because extensions like ours can't limit the suggestions to just our own. I tried implementing it that way at first, and results were overwhelming. Quick Pick has the added benefit of being able to do additional searching within the list, so I actually prefer it for this use case.
Completions come from vscode's open editors list. The current file is prioritized, and search starts from the cursor position.
See a video here:
* https://cl.ly/f32a1aa9871e
#2141 - Just the line completion aspect. …
=> Support for line completion (<C-x><C-l>)

src/actions/commands/actions.ts
This fixes #3035, adding the missing key bindings to exit CommandMode:
* <C-[>  which is the same as <Esc>
* <C-c>
=> Fix: Missing bindings to exit CommandMode. closes #3035

package-lock.json, package.json, src/cmd_line/commands/substitute.ts, test/cmd_line/substitute.test.ts
This PR fixes the behavior when run substitute command with gc flag.
Please see #2950 for the problem.
fixes #2950, #3015
=> Fix substitute with gc flag

src/mode/modeHandler.ts, test/configuration/remapper.test.ts
#3081 handled allowing remapping black hole operator deletion, but this lead to a regression. It bypassed remapping for any operator in action, but it should still remap for any operator in action in normal mode.
For example,`ciwjj` with `jj -> <Esc>` mapping should result in cutting inner word, then exiting back to normal mode, but it does not. The remapping doesn't apply since the code is checking for an operator in recordedState; the whole ciwjj combination is a full recorded state, and therefore the "c" operator exists the whole time.
We should therefore be preventing "d" in "dd" normal mode from being remapped, as Vim seems to do, to allow black hole deletion remappings still. But we shouldn't prevent remappings if the operator puts us into …
=> Remappings not applying when operators that enter insert mode

extension.ts, src/mode/modeHandler.ts
Fix issues with keybindings when changing to an editor in different mode. This resulted in keybindings not working until changing modes again, including seeing `<Tab>` inserted as text in insert mode, if vscode thought we were in normal mode still.
fixes #3096 
fixes #730 
fixes https://github.com/Microsoft/vscode/issues/59925
I'm not exactly sure why we don't have tests between editors. It would be nice to add tests here. I know that in the onDidChangeActiveTextEditor handler we even return automatically if `Globals.isTesting` is true.
Anyway, there are two main changes here:
1. "setContext vim.mode" is called when switching editor windows (previously this wasn't getting called …
=> Fix issues with keybindings when changing to an editor in different mode

src/cmd_line/subparser.ts
Just adds "edit" to the list of commands, as currently the shorthand `:e` is supported but the explicit `:edit` is not.
=> support "edit" command

extension.ts
ModeHandler.syncCursors() and updateView() stopped being called on active editor changes after the bugfix to EditorIdentity because a window change wasn't being detected as a window change when the filename-only identity is identical :D.
getAndUpdateModeHandler() is called in a ton of places, so this PR adds a force-sync option, and has the ActiveEditorChange handler use it.
#2688
This PR restores the behavior to how it was before.
I took a wrong turn on another PR, but because of that, I noticed that there's some differences between selection change handling and editor switches.  It's pretty clear from just the length of it ;), but for example, EOL-checking seems to behave …
=> fix (simpler) - cursor whenever changing editors - closes #2688

src/state/searchState.ts, src/textEditor.ts
We were seeing the error on startup with globalState.loadSearchHistory(), related to #3116.
```
TypeError: Cannot read property 'document' of undefined
[Extension Host] Here is the error stack:  TypeError: Cannot read property 'document' of undefined
at Function.getDocumentName (/Users/shawnaxsom/side-projects/Vim/out/src/textEditor.js:62:47)
at SearchState._recalculateSearchRanges (/Users/shawnaxsom/side-projects/Vim/out/src/state/searchState.js:52:88)
at SearchState.set searchString [as searchString] (/Users/shawnaxsom/side-projects/Vim/out/src/state/searchState.js:43:18)
at new SearchState (/Users/shawnaxsom/side-projects/Vim/out/src/state/searchState.js:25:27)
at __dirname.loadSearchHistory.GlobalState._searchHistory.get.forEach.val …
```
=> Prevent error on loading search history if no active editor on startup

README.md
Since UK keyboard has `shift+3` to be `£` instead of `#`. The command for going to the previous word under cursor wouldn't work. I have been searching online and couldn't find any documentation about this. So I thought would be nice to include at README here.
=> Added common example for key remapping for £

src/neovim/neovim.ts
As recommended https://github.com/VSCodeVim/Vim/issues/3013#issuecomment-429335777, disable shada. @justinmk's second point has already been addressed: https://github.com/VSCodeVim/Vim/blob/master/src/neovim/neovim.ts#L32
https://github.com/VSCodeVim/Vim/issues/3013
=> fix: disable nvim shada

.github/ISSUE_TEMPLATE/bug_report.md, extension.ts, src/configuration/configuration.ts, src/mode/modeHandler.ts, src/util/vscode-context.ts
The following operation `vscode.commands.executeCommand('setContext', ...` takes roughly 1s to complete. Cache the value and only update vscode context when value changes.
We had done this for some of the context values. This PR does it for _all_ context values.
- sorted imports
=> fix: slightly improve perf by caching vscode context

extension.ts, src/configuration/configurationValidator.ts, src/configuration/remapper.ts
As we parse through the remapped keys, if a remapping uses a non-existent command, it is ignored. More information on our readme: https://github.com/VSCodeVim/Vim#debugging-remappings
https://github.com/VSCodeVim/Vim/issues/3295
~~the new class `commandValidator` is not a true singleton. as the `getCommand` is async, the map can be initialized multiple times.~~ fixed this.
=> fix: ignore remappings with non-existent commands. fixes #3295

src/actions/commands/actions.ts, src/actions/commands/insert.ts, src/actions/plugins/surround.ts, src/cmd_line/commandLine.ts, src/common/matching/tagMatcher.ts, src/history/historyFile.ts, src/neovim/neovim.ts, src/register/register.ts, src/state/globalState.ts, src/statusBar.ts, src/textEditor.ts, src/util/util.ts, test/cmd_line/commandLineHistory.test.ts
* Workaround to https://github.com/VSCodeVim/Vim/issues/3277. `vscode.commands.executeCommand('editor.action.goToDeclaration');` returns immediately, as a result, add a 1s wait for editor to update before updating vim state with new cursor location. 
* Upstream vscode issue: https://github.com/Microsoft/vscode/issues/65809
* Code clean-up for `TextEditor`. Removing unused functions and adding `@deprecated` jsdocs.
https://github.com/VSCodeVim/Vim/issues/3277
=> fix: #3277

src/cmd_line/commands/write.ts
This PR fixes the error when saving remote files (via ssh or others)
fixes #2956
scheme value in document's uri is "file" for disk files.
for remote files, the scheme value may be different.
To use the workbench's save function can work on saving remove files.
=> fix saving remote file  error

package.json, src/configuration/configuration.ts
* Adds `iskeyword` as an overlap setting to `editor.wordSeparators`. As a result, the following will take precedence:
1. vim.iskeyword
2. if (1) is undefined, editor.wordSeparators
3. if (2) is undefined, then default value of `@,48-57,_,128-167,224-235` is used
* This change removes the default value for `iskeyword` so unless users have explicitly configured this value, `editor.wordSeparators` will be used. 
So in the standard use case where users were using the default values for `iskeyword` those folks will be moving from using this:
```
/\()\"':,.;<>~!@#$%^&*|+=[]{}`?-
``` 
to vscode's default for `editor.wordSeparators`
```
`~!@#$%^&*()-=+[{]}\|;:'",.<>/?
```
The two are the same set, but in different order so there should *not* be a change in …
=> fix: sync editor.wordSeparators and vim.iskeyword. closes #3166

extension.ts, src/cmd_line/commandLine.ts, src/cmd_line/commands/write.ts, src/configuration/remapper.ts, src/history/historyFile.ts, src/state/globalState.ts, src/util/logger.ts, src/util/util.ts, test/configuration/remapper.test.ts
* As there are cases where the command has not yet been registered by VS Code (ie. when an extension has not yet been activated), we can't ignore these remapped commands, so instead we'll log a warning
* Properly fixes #3295, but not awaiting the `executeCommand` and allowing the task queue to catch the error. 
#3295, #3307 
@xconverge this is likely going to conflict with your async PR
=> fix: log warning if remapped command does not exist. closes #3307

extension.ts, src/mode/modeHandler.ts
* extensions share a single process
* stop logging for unresolved promises for the entire process as we're logging errors from other extensions
#3333, #3329, #3328
=> fix: stop logging for unresolved promise for the process. 

src/history/historyFile.ts, src/mode/modeHandler.ts, test/cmd_line/historyFile.test.ts, test/testUtils.ts
I think this should resolve #3330. I say *think* because I wasn't able to repro the initial error on my machine. This PR replaces how we check for a directory existing from using `fs.exists` which has been deprecated to deferring to `mkdirp` which handles when a directory already exists. 
https://github.com/VSCodeVim/Vim/issues/3330
=> fix: defer to mkdirp for checking if directory exists

src/actions/commands/actions.ts
- Fix issue where half page down `<C-d>` gets stuck when on a column that doesn't exist in the destination line.
fixes #3376
relevant to #3345, which was fixed but fix may have caused this regression (haven't confirmed)
- `<C-u>`, `<C-f>`, `<C-b>` all seem fine without modification.
=> Fix <C-d> getting stuck when current column doesn't exist in destination

src/actions/commands/actions.ts, src/actions/operator.ts, test/operator/put.test.ts
Fixes visual block yank, delete and put behavior for selections contained on a single line.
#3231
#2961
#2336
#2093
#1796
-
=> Fix: visual block yank, delete and put behavior for single line selections

extension.ts, src/mode/modeHandler.ts, src/mode/modeHandlerMap.ts, test/jumpTracker.test.ts, test/mode/modeHandlerMap.test.ts
This seemed to do the trick to fix #3157. Instead of having an event handler for each modehandler (ie. text editor), declared a single event handler and delegated the event to the right mode handler. This should have the added benefit of improving perf.
To be perfectly honest however, I'm not entirely sure how this fixed the issue as the same callback code to update the position was still being called, albeit unnecessarily for all the other open text editors.
This PR also includes a minor refactor to add a wrapper around registering event handlers to ensure that we are disposing the events properly.
#3157 
=> fix #3157: register single onDidChangeTextDocument handler and delegate to appropriate mode handler

extension.ts, src/mode/modeHandler.ts, src/state/vimState.ts
Continuation of https://github.com/VSCodeVim/Vim/pull/3408 where this PR actually addresses #3157.
On the mouse event, the `handleSelection` callback was returning early as `prevSelection` had already been updated. We already have code that checks to determine if it is a mouse vs internal event so removing this check entirely. 
#3157 
=> fix: closes #3157

src/actions/commands/actions.ts
After running F8 to jump to next diagnostic location, ESC cannot dismiss the inline problems view (unless you click to focus into it).
See https://github.com/Microsoft/vscode/issues/66684#event-2101313157 for the command added.
- https://github.com/VSCodeVim/Vim/issues/3367
- https://github.com/Microsoft/vscode/issues/67086
Same addition as https://github.com/VSCodeVim/Vim/pull/1707.
=> Run `closeMarkersNavigation` on ESC. Fix #3367

src/actions/motion.ts, src/common/matching/quoteMatcher.ts, test/plugins/surround.test.ts
Fixes `ds"` with nested quotes e.g. `""te|st""` should become `"te|st"`.
Fixes `ds"` with cursor on close quote e.g. `"test|"` should become `test|`
#3415 
=> fix ds" with nested quotes and add some tests - fixes #3415

extension.ts, src/mode/modeHandler.ts
Reverting back to old non-async `syncCursors` resolves. Don't know why yet. Looking it later after fixing.
#3431
=> fix: revert back to previous non-async code when syncing cursor

src/configuration/configuration.ts, src/configuration/configurationValidator.ts, src/mode/modeHandler.ts, src/neovim/neovim.ts, src/state/vimState.ts, src/taskQueue.ts, test/configuration/configuration.test.ts
Check neovim configurations for validity and disables neovim if anything is amiss. Timeout when trying to attach neovim process.
#3433
=> fix: check neovim configurations and timeout on nvim attach

extension.ts, src/actions/commands/actions.ts, src/actions/commands/insert.ts, src/actions/motion.ts, src/actions/operator.ts, src/actions/plugins/easymotion/easymotion.cmd.ts, src/actions/plugins/surround.ts, src/actions/textobject.ts, src/cmd_line/commands/substitute.ts, src/cmd_line/node.ts, src/common/matching/matcher.ts, src/common/motion/position.ts, src/common/motion/range.ts, src/configuration/remapper.ts, src/jumps/jump.ts, src/jumps/jumpTracker.ts, src/mode/modeHandler.ts, src/neovim/neovim.ts, src/register/register.ts, src/state/vimState.ts, test/completion/lineCompletion.test.ts, test/multicursor.test.ts
It's best to review this PR by the individual commits:
* https://github.com/VSCodeVim/Vim/pull/3442/commits/fe707b41f0a8ff33d9cad215cadc21f4cc3cae0c - Validates and adjusts the cursor to ensure that it is within bounds. Resolves #3441, #2925.
* https://github.com/VSCodeVim/Vim/pull/3442/commits/4d63c47f1011c94abb66c9821aa97bf73f2518fe - Refactors some variables to make it more sensible and representative.
#3441, #2925
=> fix: ensure cursor is in bounds. closes #3441

src/actions/commands/actions.ts, src/actions/operator.ts, src/actions/textobject.ts, src/configuration/remapper.ts, src/jumps/jump.ts, src/mode/modeHandler.ts, src/state/vimState.ts
* rename cursorPositionJustBeforeAnythingHappened to cursorsInitialState
* make it a range[] type to align with `vimState.cursors`
=> refactor: rename cursorPositionJustBeforeAnythingHappened to cursorsInitialState

extension.ts, src/actions/plugins/imswitcher.ts, src/configuration/configuration.ts, src/configuration/configurationError.ts, src/configuration/configurationValidator.ts, src/configuration/iconfiguration.ts, src/configuration/iconfigurationValidator.ts, src/configuration/validators/inputMethodSwitcherValidator.ts, src/configuration/validators/neovimValidator.ts, src/configuration/validators/remappingValidator.ts, src/mode/modeHandler.ts, src/state/vimState.ts, test/configuration/configuration.test.ts, test/configuration/validators/neovimValidator.test.ts, test/configuration/validators/remappingValidator.test.ts, test/testConfiguration.ts, test/testUtils.ts
standardize the way in which we validate the configurations making it easier to test and add some UTs.
=> feat: configuration validators

extension.ts, test/configuration/validators/remappingValidator.test.ts
I still don't understand how this was a regression from 1.0.2 -> 1.0.3 (https://github.com/VSCodeVim/Vim/issues/3444#issuecomment-460254564). 
In any case, if selection changed to a paneled window (e.g. output window), we shouldn't be updating the cursors for the text editor. 
I repro-d the go-lang issue mentioned https://github.com/VSCodeVim/Vim/issues/3444 and confirmed that this is fixed. Was never able to get a wallaby repro as mentioned in #3459, but I'm going to hope for the best and presume that this fix resolves that as well.
https://github.com/VSCodeVim/Vim/issues/3444, https://github.com/VSCodeVim/Vim/issues/3459
=> fix: cursor jumps when selection changes to output window

package.json
As an alternative to https://github.com/VSCodeVim/Vim/pull/3525, we should at least specify that you need VSCode 1.31.0 or newer in order for the extension to run correctly. (In all reality, I should've done this with the [original CamelCaseMotion PR](https://github.com/VSCodeVim/Vim/pull/3483), but unfortunately overlooked that it was a possibility.)
This sadly won't help people who are having trouble with 1.1.0. Ideally we could unpublish that one release and the release 1.1.1 with this change included. But not sure if that's possible.
=> Bump minimum VSCode version to 1.31.0

src/actions/commands/insert.ts, test/mode/modeInsert.test.ts
Allows the input of the digraph characters in reverse order. The author was not aware of this short passage in the vim documentation and thus did not implement the feature in the original PR (#3407).
> If a digraph with `{char1}{char2}` does not exist, Vim searches for a digraph `{char2}{char1}`.  This helps when you don't remember which character comes first.
http://vimdoc.sourceforge.net/htmldoc/digraph.html#digraphs-use
**Which issue(s) this PR fixes**:  #3599
=> Digraphs: Allow input in reverse order (fixes #3599)

src/actions/commands/actions.ts, test/mode/normalModeTests/motions.test.ts
Allows you to cancel a search with backspace after deleting search term.
Fixes #3619
=> When backspace is hit on an empty search, cancel the search

src/actions/commands/actions.ts, test/mode/normalModeTests/motions.test.ts
When a search is cancelled (`<Esc>` after `/`), the search state should revert to the previous state, rather than being overwritten. This means the previous search should still be highlighted if `hlsearch` is enabled and `n` should go to the next instance of that search.
Fixes #3616
=> When a search is cancelled, revert to previous search state

extension.ts
Can track file open from explorer/quick open when `workbench.editor.enablePreview` is enabled.
#3507
=> Assign lastClosedModeHandler when onDidCloseTextDocument.

README.md
Thanks for this project! It's really great to be able to use most common things from Vim in VS Code!
Best practices are not documented for how to vertically move to wrapped lines when word wrap is on.
Ref: https://github.com/VSCodeVim/Vim/issues/2403#issuecomment-456365357
Ref: https://github.com/VSCodeVim/Vim/issues/2924#issuecomment-476121848
This documents the movements in a FAQ item:
- How can I move the cursor by display line with word wrapping?
If you have word wrap on and would like the cursor to enter each wrapped line when using <kbd>j</kbd>, <kbd>k</kbd>, <kbd>↓</kbd> or <kbd>↑</kbd>, set the following in VS Code's keybindings.json settings file ([other options …
=> Document display line movement best practices

src/common/motion/position.ts
**What this PR does / why we need it**
This PR fixes the performance issue reported in #3660. It changes the definition of the following properties in `Position`:
- `_nonWordCharRegex`
- `_nonBigWordCharRegex`
- `_nonCamelCaseWordCharRegex`
- `_sentenceEndRegex`
- `_nonFileNameRegex`
so that the construction of these regular expressions is performed only once.
The time to complete the benchmark task proposed in #3660 was **431ms** in average, which is 12x faster than the current version on my machine.
fixes #3660.
=> Improve performance of word motions

.github/CONTRIBUTING.md, README.md, package.json
Change to https for existing links and convert to heroku for azure ones
**What this PR does / why we need it**: Slack has moved to heroku apps but some of them still has the old azure link, also some heroku one has http instead of https
**Which issue(s) this PR fixes**: This doesn't start a fix for a particular issue but rather finish the fix for #3370
=> docs: update slackin link

src/actions/commands/actions.ts
This fixes #1951 in normal mode.
#1951
I realized that a range object from reverse selecting in insert or normal mode is not corresponding to the user's selection. 
In the PR #2062, native selections are used instead of ranges in insert mode.
I think there are two options to solve #1951.
1. Fix the problem between ranges and user's selections.
2. Use native selections instead of ranges in normal mode just like #2062.
This PR is based on option 2.
=> Fix reverse selecting in normal mode.

src/cmd_line/commands/substitute.ts
The confirmation text for replacing with `%s/oldText/newText/gc`, for instance, would read:
> Replace with oldText?
Now it reads
> Replace with newText?
Fixes #3715
=> Correct replacement confirmation text

src/actions/commands/actions.ts, test/mode/normalModeTests/commands.test.ts
Fixes the behavior of `<count>r<enter>`
The cursor now ends up at the beginning of the next line and will only ever insert one newline, regardless of count prefix.
Fixes #1884
=> Fix replace character (`r`) behavior with newline

src/actions/commands/actions.ts
The `C-[` and `C-c` keys should terminate search mode like `<Esc>` does.
Fix for #3668
=> <C-[> and <C-c> should terminate search mode

src/configuration/decoration.ts
When you use VSCode's built-in search, the results show up in the "overview ruler" (the scroll bar). Now our custom search does the same.
**Note:** this works perfectly when `hlsearch` is set. When it's unset, they show up while you're typing, but not once you actually do the search. I'm not sure what better behavior would be, but am open to changing it.
Fixes #1856
=> Show search results in the overview ruler

package.json
User settings linting for `vim.statusBarColors` shows errors when configuring a background and foreground colors. User settings expects a string, but `vim.statusBarColors` supports `string` and `string[]`.
https://github.com/VSCodeVim/Vim/issues/3607
=> Fix statusBarColors linting in vscode user settings.

src/actions/commands/actions.ts, src/cmd_line/commands/nohl.ts
`hlsearch` was enabled when a search was initiated (`/`), not when you actually search (`<enter>`). The result is that `:noh` would be undone when a search is cancelled (`/<esc>`).
Fixes #3748
=> Make sure :noh disables hlsearch until the next search is done

src/cmd_line/commands/write.ts
As title. Saving a remote file can be slow, and we don't want to block
the vim state it. We're not doing anything with the result anyway, so it
should(?) be okay to remove this await.
Fixes #3777, more context is there
=> Make the write command non-blocking on remote files

src/actions/commands/actions.ts, test/mode/modeNormal.test.ts
The behavior of `<c-u>` to move up half a page was inconsistent with vim/neovim when the first line is visible. With this PR `<c-u>` will jump to the first line when it is visible.
https://github.com/VSCodeVim/Vim/issues/3648
https://github.com/VSCodeVim/Vim/issues/3083
Note that I had changes the startColumn to 0 to match vim/neovim functionality. When a MoveUpHalfPage, we do not preserve the starting column and go the beginning of the line.
Also, the behavior of <C-b> when the first line is visible does not need to change. vim/neovim keeps the cursor where it is at when MoveUpFullPage is invoked and the first line is visible.
=> Fix MoveHalfPageUp (<C-u>) when first line is visible.

.travis.yml
Fix Linux build on Travis. See https://github.com/microsoft/vscode/issues/75873.
=> Fix build per microsoft/vscode#75873

.travis.yml, package-lock.json, package.json, src/actions/commands/actions.ts, src/actions/plugins/easymotion/easymotion.ts, src/configuration/remapper.ts, src/configuration/validators/inputMethodSwitcherValidator.ts
=> upgrade pkgs

src/util/logger.ts
#3591 changed the config key from 'vim.debug.suppress' to 'vim.debug.silent'.
Unfortunately, the log message still referenced the old config key.
This PR fixes this by printing out the correct config key in the log message.
=> fix log message for 'vim.debug.silent'

ROADMAP.md
Fixes typo in ROADMAP.md
Fixes #3823
=> Fix WORD wrapped in pipes

extension.ts, src/actions/commands/actions.ts
Fix GoToDefinition bug when use C# extension.
#3865
=> Assign activeTextEditor to local variable first.

src/actions/plugins/easymotion/easymotion.cmd.ts, test/plugins/easymotion.test.ts
Easymotion used regex to handle case-(in)sensitivity, which caused problems when searching for certain characters (among them `.`, `\`, and `^`). To fix this, I've changed it so that non-letter characters do not use the regex.
Fixes #3844
=> Do not treat easymotion input as regex unless it's a letter

src/actions/motion.ts, test/mode/normalModeTests/matchingBracket.test.ts
These have matches, but are not compatible with the `%` motion (matchesWithPercentageMotion=false). We should skip over them to find one that is compatible.
Fixes #3807
=> Make `%` skip over characters such as '>'

src/actions/motion.ts, src/configuration/notation.ts, test/mode/normalModeTests/motions.test.ts
`f`/`F`/`t`/`T` didn't work with <tab>. Now they do.
Fixes #2510
=> Fix f/F/t/T with <tab>

src/actions/commands/insert.ts, test/mode/modeInsert.test.ts
On an all-spaces line, you press backspace in insert mode, it'll cause an error. Now this corner case is accounted for.
Fixes #3915
=> Handle backspace on first character of all-space line correctly

.prettierrc, gulpfile.js
Move prettier configuration to `.prettierrc` (see https://prettier.io/docs/en/configuration.html)
This means that people can develop with the intended prettier configuration in their local editor (as will look for a `.prettierrc` by default) while maintaining the `forceprettier` functionality (and keeps the configuration in one place)
None that I could find
- The `prettier` cli will pick up this file during the gulp `forceprettier` step
- Hopefully the intent of this makes sense (eg. I personally run prettier in its default mode so need to update my config depending on the repo I'm working on, unless there's some config for my editor to pick up)
- The configuration could be moved …
=> Move prettier configuration to .prettierrc

src/actions/commands/actions.ts, test/cmd_line/substitute.test.ts
Implements the ampersand (`&`) action, which repeats the last substitution (equivalent to `:s`)
Fixes #3808
=> Implement ampersand (&) action

src/actions/commands/actions.ts, test/mode/normalModeTests/commands.test.ts
Things like `"aC` did nothing because mustBeFirstKey = true.
I'm not 100% sure that there wasn't a reason why mustBeFirstKey was true, but I can't see what it would be.
Fixes #2504
=> Make `C` work with registers

src/actions/commands/actions.ts, src/mode/modeHandler.ts, src/state/globalState.ts, src/transformations/transformations.ts
These show your search history via a QuickPick, allowing you to search through and re-do these.
Also implemented an alias for these, which is `<C-f>` while typing a search.
Refs #3949
=> Implement `q/` and `q?`

src/cmd_line/commandLine.ts
With neovim enabled, :h will replace your file with the output of help. While supporting :help by putting it into a new buffer at some point could be cool, this is...not good.
=> Disallow all forms of :help

src/cmd_line/commandLine.ts, src/cmd_line/commands/deleteRange.ts, src/cmd_line/commands/read.ts, src/cmd_line/commands/sort.ts, src/cmd_line/commands/substitute.ts, src/cmd_line/node.ts
We need to use VSCode's quickpick capabilities to do confirmation.
Fixes #3371
=> When the `c` (confirm) flag is used in a `:s` command, don't use neovim

package.json, src/actions/commands/actions.ts
Contributes keybindings and corresponding support in code for `<C-p>` and `<C-n>` to act as prev/next when entering a command or search term.
Fixes #3942
=> Allow <C-p> and <C-n> to be used as prev/next when entering a command or search

src/actions/operator.ts, test/operator/comment.test.ts
`gC`, which does a block comment, does one fewer than the selected characters in visual mode. I don't have the real commentary vim extension installed, but I don't think this is the correct behavior.
Fixes #2448
=> Fix `gC` in visual mode

package.json
Fix duplicated command added in c542b42, which cause the extension fail to load.
error message:
```
Activating extension `vscodevim.vim` failed:  command 'extension.vim_ctrl+n' already exists
```
=> Fix duplicated command added in c542b42

src/actions/commands/actions.ts
This lets you search through your command history so you don't have to retype everything. Equivalent to `q:`.
Refs #3949
=> `<C-f>` shows command history when pressed on command line

src/common/motion/position.ts, src/state/searchState.ts, test/mode/normalModeTests/motions.test.ts
Implements search offsets! If you're unfamiliar, this essentially allows you to tack something onto a search with `/` or `?` that changes where your cursor ends up. Details are here: http://vimdoc.sourceforge.net/htmldoc/usr_27.html#27.3
Line, beginning, and end offsets are implemented - no semicolon offsets (yet).
Fixes #3917
=> Implement search offsets

src/cmd_line/commands/write.ts, src/cmd_line/subparsers/write.ts
This changes the :w behavior to write in background to unfreeze the VS Code UI when the user is using VS Code Remote while allowing operation like wq and wa to work in VS Code
This fix the regression caused by https://github.com/VSCodeVim/Vim/pull/3998
https://github.com/VSCodeVim/Vim/pull/3998
https://github.com/VSCodeVim/Vim/issues/3922
https://github.com/VSCodeVim/Vim/issues/3777
=> :w write in background

README.md, src/actions/plugins/replaceWithRegister.ts, src/cmd_line/commands/sort.ts, src/configuration/notation.ts, test/plugins/replaceWithRegister.test.ts
This fixes the issue where ReplaceWithRegister doesn't work in visual mode
#4015
=> Make ReplaceWithRegister work in visual mode

package.json, src/configuration/configuration.ts, src/configuration/iconfiguration.ts, src/state/searchState.ts, test/motionLineWrapping.test.ts, test/testConfiguration.ts
Missing nowrapscan feature
#3155 
Inspired by aborted PR #3192
=> Implement `nowrapscan`

package.json, src/actions/baseMotion.ts, src/actions/motion.ts, src/actions/plugins/camelCaseMotion.ts, src/actions/plugins/sneak.ts, src/actions/plugins/surround.ts, src/actions/textobject.ts, src/common/motion/range.ts, src/configuration/configuration.ts, src/configuration/iconfiguration.ts, src/mode/modeHandler.ts, src/state/vimState.ts, test/testConfiguration.ts
It's called `sneakReplacesF` and is nice because it basically makes `f` work across newlines.
I had to pull a few interfaces and a base class out from motion.ts to avoid a circular import.
Closes #4012
=> Add flag to replace `f` with a single-character sneak

.travis.yml, .vscodeignore, gulpfile.js, package-lock.json, package.json, src/configuration/configuration.ts, webpack.config.js
Add WebPack support via a `gulp` plugin
Partially fixes #3127
In my tests, loading times (`Running Extensions` -> `Startup Activation`) decrease from 2-4s to <1s.
The `webpack-stream` package is a little outdated, and raises some deprecation and vulnerability warnings. The best alternative would be to migrate fully from `gulp` to `webpack`, but that requires some discussion.
=> WebPack builds for improved loading times

src/actions/operator.ts, test/mode/modeNormal.test.ts
**What this PR does / why we need it**: The `gq` command to "reflow" selected text in visual line mode didn't properly handle tabs, replacing them with spaces.
**Which issue(s) this PR fixes**: (none, I can create one if needed)
**Special notes for your reviewer**: I added another commented-out `gq` test case under the assumption that it would also "run poorly on Travis". It passes locally though (along with the two old commented-out `gq` tests).
=> Fix gq to handle tab indentation

extension.ts, package-lock.json, package.json, src/actions/commands/actions.ts, src/common/motion/position.ts, src/configuration/notation.ts, src/configuration/remapper.ts, src/history/historyTracker.ts, src/state/recordedState.ts, src/taskQueue.ts, test/extension.test.ts
filter, includes, find, etc.
After doing this, there was only one usage left (for escaping regex), so I removed the lodash dependency in favor of one that only exposes that functionality.
=> Don't use lodash for things ES6 supports natively

.github/CONTRIBUTING.md
Seems like the contributing markdown file was missing a `to` at the end when asking potential contributors to do their best to adhere to the style guidelines.
=> Add missing `to` in CONTRIBUTING.md

package.json, test/cmd_line/tabCompletion.test.ts
Add shift+tab to go back on autocompletion on cmd line
This is related to
#4032
=> Add shift+tab support for cmd line

src/cmd_line/parser.ts, src/cmd_line/subparser.ts, test/cmd_line/subparser.close.test.ts, test/cmd_line/subparser.quit.test.ts, test/cmd_line/subparser.substitute.test.ts, test/cmd_line/subparser.test.ts
Vim commands are (in nearly all cases) triggered by all strings "between" the command's abbreviation and its full name.
For instance, `:q`, `:qu`, `:qui`, and `:quit` all resolve to the same command.
Only the full command list will autocomplete, however: `:q<tab>` yields `:quit`.
We now handle both these cases correctly by storing both the full name and the shortest abbreviation.
=> Use command abbreviations

package.json, src/actions/commands/actions.ts, src/configuration/configuration.ts, src/configuration/iconfiguration.ts, test/testConfiguration.ts
Our implementation of `<C-u>` and `<C-d>` has never quite been right - currently, `<C-d>` gets stuck and `<C-u>` jumps to the top as soon as it's visible. We also stopped paying any attention to the `vim.scroll` option at some point.
This commit fixes all of the above and simplifies the logic.
=> Refactor <C-u> and <C-d>

src/statusBar.ts
Before now, all lines but the first would disappear, and your cursor could be "off screen".
=> Render newlines in command line as ^M

src/actions/motion.ts, test/mode/modeVisual.test.ts, test/mode/normalModeTests/motions.test.ts
Closes #4120. This more or less reverts the functionality introduced by commit
4b2e07933 and raised in issue #3890.
Unfortunately it is not currently possible to fully implement display
line movements over wrapped lines that will always preserve cursor
position. One of two things is necessary to change this, either the
VSCode API needs to be extended to return information about wrapped
lines (but this was rejected in issue microsoft/vscode#23045).
Alternatively VSCodeVim would need to reïimplement all motions using
vscode.commands.executeCommand() commands rather than manipulating
vscode.window.activeTextEditor.selections directly, as the former
preserves column position while the latter does not. However it's not
clear to me if all VIM beahviour could be reïmplemented this way without …
=> Fixes gj/gk behaviour on wrapped lines; closes #4120

.github/CONTRIBUTING.md
With the addition of Webpack bundling (issue #3127, commit 1f80b2d)
the instructions for how to run tests were no longer working.
=> Update CONTRIBUTING.md after webpack bundling addition

webpack.config.js
Excludes neovim module from whatever magic webpack is doing.
#4126 
We need better tests, but I'm not even sure how we can even test this on Travis...
=> fix: exclude neovim from webpack module. #4126

ROADMAP.md, src/actions/commands/actions.ts
Adds support for the Vim 'za' keybinding, which toggles a fold.
#1453 
This simply binds the new VSCode editor.toggleFold option to the 'za' combination. I was unable to find a way to implement specifying a number modifier, as you need to know whether or not to travel up or down.
=> Add support for za Vim binding

.github/CONTRIBUTING.md
The CONTRIBUTING.md guide recommends installing gulp globally, but you can instead run gulp with `npx gulp`, which avoids versioning issues inherent in global Gulp installs.
No issue, just noticed while looking into contributing ☺️
=> Update CONTRIBUTING.md to recommend npx gulp

src/actions/commands/actions.ts, src/textEditor.ts
Currently, when replacing characters using replace command from Visual and Visual block mode. Pressing tab replaces characters with `<tab>` instead of the tab character. This PR fixes the issue so that every character in the selection is replaced by the tab character (affected by `tabstop` and `expandtab` configuration).
#2499 
This is my first time contributing to an open source project. Please be kind 😄 .
=> fix replace commands from visual and visual block mode not inserting tab

src/common/number/numericString.ts, test/number/numericString.test.ts
When incrementing or decrementing a number, the `NumericString.parse` class is used to parse strings in to numbers of various formats. However, it used global (stateful) regexes to do this, which meant that funky things could happen after the first call to the method. This PR fixes the issue by simply removing the `g` flag from some regexes.
This fixes issues, for example, where pressing `<C-a>` on certain numbers more than once lead to numeric prefixes getting stripped or other odd behavior.
Fixes #3545
@Chillee added the `g` flag in https://github.com/VSCodeVim/Vim/pull/1721. I think the rest of the logic in that PR still works correctly _without_ the `g` flags, but feel free to …
=> Fix bug causing increment/decrement issues for some number formats

.github/CONTRIBUTING.md
With the revert of the webpack build PR (#4217), we also need to revert the documentation change in CONTRIBUTING.md. 
(Just noticed this when making a PR earlier today, figured it would be good so that new contributors aren't confused!)
Reverts #4128 manually
=> Remove prepare-test step from CONTRIBUTING.md

src/actions/commands/actions.ts, test/mode/modeNormal.test.ts
Make `gp` (and `gP`) correctly place cursor after pasting 4+ lines.
**Which issue(s) this PR fixes**:
#4246
This looks to me like a minor slip of the original author. Tests did not reveal the bug and it is not super obvious in day to day usage.
=> Fix `gp` when pasting more than three lines

src/configuration/configuration.ts, src/configuration/vimrc.ts, src/configuration/vimrcKeyRemappingBuilder.ts, test/configuration/vimrcKeyRemappingBuilder.test.ts
For instance, `nnoremap gs workbench.action.showAllSymbols` will now work.
Refs #463
=> Recognize VSCode commands in .vimrc

src/actions/textobject.ts
I fixed comment typos "postion" to "position"
fixing comment typos "postion" to "position"/ because some people who do not well English miss understand comment
"postion" to "position"
I'm a Korean college student who just started coding. I'm not good at it, but I'd also like to contribute comments in this project.
=> fix comment typos "postion" to "position"

src/state/searchState.ts, test/mode/normalModeTests/motions.test.ts
Fixed backward search from end of word (VSCodeVim #4266)
- Searching with 'N' after /e at the end of search fixed
- Changed comparison for next search result
- Change made in getNextSearchMatchRange in searchState.ts
Fix the issue reported,
1. Search for a recurring word and use offset e. E.g.` /word/e`
2. The cursor should now be at the end of the next result
3. Repeat search backwards with `N`
4. The cursor is still on the current result
Also fixed the larger issue, where backward search was broken in general. For example, the previous steps could be repeated with `?word?e`, where backward search with `n` also did move the cursor. 
#4266 
We tested this manually to verify it …
=> Fixed backward search from end of word (VSCodeVim #4266)

src/actions/motion.ts, test/mode/normalModeTests/motions.test.ts
=> Stop comma from switching the find direction

src/configuration/vimrcKeyRemappingBuilder.ts, test/configuration/vimrcKeyRemappingBuilder.test.ts
=> Require <CR> after a vim command in .vimrc if you want it to run

src/mode/modeHandlerMap.ts
this.modeHandlerMap.get(editorId) returns undefined all the time, which means that a new modeHandler gets created everytime getOrCreate() gets invoked on every key press. The result was modeHandler always being in its initial state and rendering the editor completely useless.
This fix properly checks if editorId exists in the map, if it does it properly retrieves its modeHandler.
Fixes #4332.
I'm not sure if what was expected here was that Map.get() would call EditorIdentity.isEqual() to check editorId against the keys, but that's not what was happening.
=> Fixed modeHandler being recreated on every key stroke

src/cmd_line/commands/substitute.ts, src/configuration/iconfiguration.ts, src/configuration/vimrc.ts
When config.vimrc.path is undefined, fs.readFileSync() will throw an error which results in the extension failing to activate. This PR fixes that issue by changing the variable passed to fs.readFileSync() to one that is guaranteed to not be undefined.
Fixes #4336
The correct default path ($HOME/.vimrc or $HOME/_vimrc) is already being assigned to the local _path variable which is properly being checked before using it to set the vimrcPath property. Thus, it is safe to assume vimrcPath will never be an invalid path and is safe to be passed to fs.readFileSync().
=> Fix fs.readFileSync() receiving a possibly undefined path

src/cmd_line/commandLine.ts, src/history/historyTracker.ts, test/mode/modeHandlerMap.test.ts
This seems like it could be incorrect sometimes, and we should make sure all changes are either declared finished at their creation or finished before they can be undone.
Also remove an instance of suite.only() that slipped in...whoops
Fixes #4351
=> Make sure DocumentChange.timestamp is always set

test/mode/modeNormal.test.ts
We should make sure `:s/abc/def` is handled correctly. 
Never added a test to this repo before, please let me know if I'm doing things incorrectly.
=> Added test to check can handle 'u' after :s/abc/def

README.md
I've tried copying this around to my config file and realized it had no commas on the ends of lines. I'm adding them here. :)
Fixes README by adding commas to the end of the chunk of JSON that enables statusBarColors.
Didn't file.
✨
=> Add commas to statusBarColors JSON on README

src/configuration/vimrc.ts
Adds support for `map` and `renoremap` in .vimrc 
#4403 
Had a test failure however it's currently failing on master.
```
1) Remapper
leader, c -> closeActiveEditor in visual mode through modehandler:
AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
1 !== 0
```
=> support vimrc map & noremap  

ROADMAP.md, src/actions/commands/actions.ts, src/actions/operator.ts, src/actions/plugins/sneak.ts, src/configuration/vimrc.ts, src/state/recordedState.ts, test/cmd_line/split.test.ts, test/cmd_line/vsplit.test.ts, test/operator/rot13.test.ts
=> `g?` (rot13) support

src/actions/base.ts, src/actions/baseMotion.ts, src/actions/commands/actions.ts, src/actions/motion.ts, src/mode/modeHandler.ts, test/mode/modeNormal.test.ts, test/mode/modeVisualLine.test.ts, test/mode/normalModeTests/motions.test.ts
basically the same as  #4298. That PR was causing a bunch of difficult to debug issues since it updated the default behaviour for all actions. This PR takes mostly the same approach, except it defaults `doesntChangeDesiredColumn` to `false` and just sets it to `true` for `zz`. There are probably other actions that update `desiredColumn` when they shouldn't, and this PR won't address those, but at least now there's an easy route to address those bugs as they're noticed. (just add `doesntChangeDesiredColumn = true`)
I also added a bunch of unit tests that I wrote while trying to debug the last PR. 
#4296
=> Fix zz updating desired column

src/actions/commands/actions.ts, test/mode/modeNormal.test.ts
Previously when leaving multi-cursor mode with `<Esc>` the cursor would move one column to the left. For instance, when triggering multi-cursor mode on a single word, the cursor would end at the second to last character. While this is expected behavior when leaving insert mode, it is not for visual mode (which multi-cursor mode is based on). To fix, remove special case handling altogether.
**Which issue(s) this PR fixes**:
#3775 
After giving it some thoughts, I decided to remove the special case completely. I could not reproduce any other case where conditions would match other than move-left after multi-cursor mode. To verify, I added a `console.log()` in the branch in question, and ran the complete test suite. …
=> Fix cursor off after leaving multi-cursor mode

src/actions/commands/actions.ts, src/jumps/jumpTracker.ts, src/mode/modeHandler.ts, src/state/vimState.ts, src/util/util.ts, test/completion/lineCompletion.test.ts, test/testSimplifier.ts
The issue this function was meant to solve seems to have disappeared.
Fixes #4432
=> Stop using timeout in `getCursorsAfterSync()`

src/actions/commands/actions.ts, src/actions/commands/insert.ts, src/actions/motion.ts, src/actions/operator.ts, src/actions/textobject.ts, src/cmd_line/commandLine.ts, src/common/matching/matcher.ts, src/common/motion/position.ts, src/mode/modeHandler.ts, src/neovim/neovim.ts, src/state/searchState.ts, src/textEditor.ts
The biggest change is in how PositionDiffs are constructed - now with a object parameter, so it's much easier to understand what the intention is.
BOL diffs no longer accept a character - they bring you to the beginning of the line.
And a few other small tweaks. This probably should've been split across a couple commits, but too late for that now.
=> Refactor `Position` and `PositionDiff`

src/actions/base.ts, src/actions/commands/actions.ts, src/actions/commands/insert.ts, src/actions/operator.ts, src/actions/plugins/replaceWithRegister.ts, src/actions/plugins/surround.ts, src/history/historyTracker.ts, src/mode/modeHandler.ts
Many commands, like movement and typing a search, will never change the document. We waste considerable time diffing the entire document on each of these keystrokes to figure out if we should add an undo step.
I've added a property to BaseAction, `mightChangeDocument`, which determines whether we should check for changes.
This defaults to false for the sake of brevity (most commands actually don't change the document), but this is a bit dangerous - what if I forgot to override it in a command that changes the document?
The planned solution is to release this as a check - we will always run the diff, as we currently do, then make sure a command didn't add a change when we asserted it wouldn't. After this is in the wild for a little while with no reported issues, we'll actually flip the …
=> Improve performance on large files by not checking for changes after commands which never change the document

src/configuration/configuration.ts, src/mode/modeHandler.ts
This PR fixes the issue of not changing the cursor style as per the user settings when we switch modes. I've done this by changing `modeName` from being a type `Mode` back to a type `string`, and having the modeHandler resolve `ModeHandler.currentMode` into a `string`. 
Fixes #4355 
The first reason why we cannot have `modeName` be a `Mode` is because it is a [numeric enum](https://www.typescriptlang.org/docs/handbook/enums.html#numeric-enums) and not an [string enum](https://www.typescriptlang.org/docs/handbook/enums.html#string-enums), which means that `modeName.toString()` will simply be the number corresponding to that particular member (e.g. `Mode.Normal.toString() === 0`). …
=> Fix getCursorStyleForMode() always returned undefined

src/cmd_line/commandLine.ts
I noticed that when running certain ex commands with neovim integration enabled, I wasn't seeing any output in the statusbar, regardless of the success or failure of the command. As a result I wasn't sure if commands had been successful or not.
On investigation I realised that there are two cases in which the extension passes an ex command to neovim for execution, but currently only one of them displays the result in the status bar. This commit brings the second case in line with the first so that the result of running the command is displayed:
As it was a simple fix I decided to just go ahead and make a PR rather than creating an issue.
As a side-note, watching the tests run was …
=> Update statusbar with result of ex command from neovim

src/mode/modeHandler.ts
It addresses the issue of revealing a range on a mouse click which causes us to not respect the default behaviour of `cursorSurroundingLines`. The default behaviour of `cursorSurroundingLines` (`"editor.cursorSurroundingLinesStyle": "default"`) is to ignore the scroll offset ([https://github.com/microsoft/vscode/blob/master/src/vs/editor/browser/viewParts/lines/viewLines.ts#L574](https://github.com/microsoft/vscode/blob/master/src/vs/editor/browser/viewParts/lines/viewLines.ts#L574)), thus not scrolling on a click event. 
VSCode handles revealing a range on a click, I believe it is addressed with [https://github.com/microsoft/vscode/blob/71b60d0d2201e5ba0a52d9bd2b914da2cee11ab5/src/vs/editor/browser/viewParts/lines/viewLines.ts#L649](https://github.c …
=> Respect default behaviour of cursorSurroundingLines

src/actions/baseMotion.ts, src/actions/motion.ts, test/mode/modeNormal.test.ts
This PR makes it so `MoveParagraphEnd` behaves exactly like it does in Vim when it is executed with an operator. It doesn't change the behaviour without an operator, which is already accurate.
The current implementation doesn't respect the cursor position, breaks when it is repeated by an operator with a count (only moves a paragraph on an odd number iteration) and doesn't respect the blank line at the end of a paragraph like regular Vim.
I've added two properties to `MoveParagraphEnd`:
1.  `iteration`: Keeps track of the iteration, this way we know when we're on the last iteration, in which case we want to return the position just before the blank line that `paragraphEnd` represents, so that we accurately emulate Vim's behaviour. 
2. …
=> Fix '}'(MoveParagraphEnd) behaviour to accurately emulate Vim's

package.json, src/actions/commands/insert.ts, src/editorIdentity.ts, test/mode/modeInsert.test.ts
In the insert mode, `<Del>` key are not handled by VSCodeVim. So `<Del>` commands used in insert mode are transparent to the `dot` command and cannot be repeated with it, which is very inconvenient. And another problem is that user cannot remap any key to `<Del>`.
With this pull request, these problems are solved.  
Fixes #2423, fixes #4219, fixes #4082. 
BTW: I think we need some documentation and code annotations. I spent a whole night tracking the missing delete commands and find out that this bug can be easily located even with a little documentation describing the key handling precedure......
=> Implement <Del> handler for insert mode

src/actions/plugins/surround.ts, test/plugins/surround.test.ts
This makes VSCodeVim behave more like vim-surround, which I think users would find more intuitive.
https://github.com/VSCodeVim/Vim/issues/3461
I've run the npm test. I had to change a few because the surround ones were checking for the old behavior. I checked that the new tests are consistent with vim-surround's behavior though.
I'm not too familiar with either typescript nor this repo, so I'm grateful for the patience and possibly extra support.
=> Fix surround cursor placement bug (#3461)

src/editorIdentity.ts, src/mode/modeHandlerMap.ts, test/mode/modeHandlerMap.test.ts
Hello, in my setup, this resolves #4479, #3277
From what i can observe, here's what i found to arrive to this conclusion:
- on `vscode.window.onDidChangeActiveTextEditor` i always get `lastClosedModeHandler = undefined` despite that the current file is exists on `ModeHandlerMap`
- due to `lastClosedModeHandler = undefined` jumping from current file doesn't push it to the jump stack
=> Fix wrong return in ModeHandlerMap.get

src/actions/commands/actions.ts, src/actions/operator.ts, src/common/motion/position.ts, src/mode/modeHandler.ts, src/state/vimState.ts, src/textEditor.ts
=> Make VisualLine and VisualBlock modes work with multiple cursors

src/actions/motion.ts, src/history/historyTracker.ts, src/neovim/neovim.ts, test/historyTracker.test.ts, test/mode/modeNormal.test.ts
Supports file marks.  I.e., just like normal marks, except when the mark is uppercase it should jump across files in addition to the cursor position.
Fixes #1692
Burrows heavily from #564 
This is my first pull request on this repo, so I'm not sure if I've missed something.  I was going to add tests, but I couldn't see any existing tests for marks, so I decided not to.
=> Globalmarks

src/actions/commands/actions.ts, test/mode/modeVisualLine.test.ts
So simple :-P
Fixes #4593
But currently these are just workaround. We need to simulate a cursor in visualLine mode in the future.
=> Fix misplaced cursor after `VV`

README.md
* many people seem to copy the 'quick example' from the readme as
their initial config. The problem with that quick example is that it
enables 'sneak', which by defaults breaks the S and s commands (see
issue #3274).
* by removing that setting from the example, people should have a
working config out of the box. If someone is interested in sneak,
other sections of the readme still go into details.
* #3274 
* Please see comment by @jpoon : https://github.com/VSCodeVim/Vim/issues/3274#issuecomment-594106691
=> readme: remove sneak from quick example

src/actions/commands/actions.ts, test/mode/normalModeTests/commands.test.ts
In original Vim, `[count]D` delete the characters under the cursor until the end of the line and (count - 1) more lines.
But this feature in not implemented.
e.g.
```
one
t|wo
three
four
```
execute `2D`, and then
```
one
|t
four
```
Fixes #3757
=> Implement "[count]D"

README.md
**What this PR does / why we need it**: Add a note to the FAQ about issues with setxkbmap. I think this is needed since it's common for people to remap escape and capslock with setxkbmap and given this isn't working but is possible to workaround we should add a note to the PAQ.
**Which issue(s) this PR fixes** closes https://github.com/VSCodeVim/Vim/issues/4612
=> add setxkbmap escape caps remapping not working to FAQ

package.json, src/actions/commands/actions.ts, src/actions/commands/commandLine.ts
This pull request addresses issue #1505 
Summary: In vim `<C-m>` key binding works in the same way as pressing enter in all modes. This is not very common across editors but is very handy since requires much less movements.
I've made necessary changes only to discover that I cannot really
capture exactly `<C-m>` shortcut, because it's used by vscode "Tab moves focus"
shortcut. I removed it from the settings, but it looks like Vim plugin
still is not able to get it.
As a proof of concept I added another shortcut - `<C-q>` that does what
`<C-m>` should do. This shortcut should be removed before this pull
request is merged.
I have a couple ideas on how to approach the problem:
1. Disable this setting totally in case of vim plugin enabled
2. Temporary disable "tab moves focus" shortcut in all …
=> Add support for <C-m> in insert, search in progress and commandline in progress modes

src/actions/commands/commandLine.ts, test/cmd_line/command.test.ts
Cancelled Searched not being added to search history.
`/foobar<Esc>`, then `/<C-p>`. Notice "foobar" does not show up.
fixes #4650 
Let me know on the issues with the PR as this is my first open source PR.
=> added escaped search string in global search state

src/mode/modeHandler.ts
With a folded region larger than 15 lines, when the cursor is below the
folded region, it is always 15 lines below the end of the first region,
so the existing logic will incorrectly tell vim to always re-center the
cursor. Instead, we should check if the cursor is either below all
visible regions, or above all visible regions.
Fixes:
https://github.com/VSCodeVim/Vim/issues/4643
https://github.com/VSCodeVim/Vim/issues/4632
=> Fix cursor movement with large folded regions.

src/actions/commands/commandLine.ts, test/mode/modeNormal.test.ts, test/mode/normalModeTests/motions.test.ts
`[count]/[word]`(and `[count]?[word]`) is not working.
And `d[count]/[word]` is not working either.
Fixes #4669 
Fixes #2464
`d[count]?[word]` is not working yet, and no tests added.
Because `d?[word]` doesn't work in the first place (#4506), so this is another problem.
=> Fix search with count

src/actions/commands/actions.ts, src/mode/modeHandler.ts, test/mode/modeVisualBlock.test.ts
`J` (join lines) works in visual block mode in original Vim, but this is not supported this extension.
expected:
If `J` is executed in the state of this image, expected to be:
```
one two three
four
```
- Cursor position after execution is different from original Vim, but this is the same behavior as visual mode and visual line mode. So I think this should be fixed as another Pull Request.
- In the above example, cursor should be before `three` after execution, but actually it is before `two`.
- `gJ` doesn't work either, but doesn't fix it. Because `gJ` has a bug like #2207 and it doesn't work properly.
And if necessary, I'd like to fix and create another PR for these as well 👻
=> Support `J` in visual block mode

package.json, src/actions/base.ts, src/actions/commands/actions.ts, src/actions/commands/commandLine.ts, src/actions/commands/insert.ts, src/actions/operator.ts, src/actions/plugins/replaceWithRegister.ts, src/actions/plugins/surround.ts, src/configuration/configuration.ts, src/configuration/iconfiguration.ts, src/history/historyTracker.ts, src/mode/modeHandler.ts, test/testConfiguration.ts
This replaces `mightChangeDocument`, which sought to do the same sort of optimization in a less effective and far more clumsy way.
Fixes #4665
=> Optimize HistoryTracker using a cached TextDocument.version

src/actions/commands/actions.ts, test/mode/modeVisualBlock.test.ts
Sorry, my PR (#4663) contained a bug 🙁
`J` doesn't work properly when the start position of the visual block is below the end position.
e.g.
At first the cursor is on the `|`.
```
one
two
t|hree
four
```
If execute `<C-v>kkJ`, of course expected result is as follows:
```
one two three
four
```
but not.
=> Fix a bug of `J` command in visual block mode

src/actions/commands/insert.ts, src/mode/modeHandler.ts, src/transformations/transformations.ts, src/util/util.ts
It fixes multicursor snippets, and adds support for stuff like auto-bracketing and auto-completion on multicursor mode.
5fd59f7: (Backspace Support)
Makes `range` represent the `selection` at `position`. This way we delete the correct `range` rather than the primary selection as it was before these changes.
59496be: (Multicursor Character Insert)
Makes multicursor text insertion behave like single cursor text insertion by ultimately using the `default: type` command rather than `vscode.TextEditor.insert()` which doesn't have support for snippet mode, auto completion, bracketing, etc.
To accomplish this, I've added an optional property (`isMultiCursor`) to `InsertTextVSCodeTransformation` which represents `vimState.isMultiCursor`at the time the …
=> Improve multicursor support

src/actions/commands/actions.ts
The issue this workaround used to solve appears to have been fixed in the upstream and is no longer reproducible. Additionally, because it would update the `activeTextEditor.selection` it caused vscode to loose our selections in multicursor mode, thus `editor.action.insertLineBefore` would only insert a line above the first cursor and subsequently take us out of multicursor mode.
fixes #1962 
A bit unrelated but I'm unsure if I should open an issue for this, I normally do format on save but since prettier was added it re-formats the whole document and would have made this PR a mess. Should I push another commit with the prettier formatting?
=> Remove old workaround that is no longer needed

src/actions/plugins/sneak.ts, test/plugins/sneak.test.ts
When you do a search with vim-sneak, VSCodeVim doesn't save your
position and you can't go back to where you were before using <C-o>.
This PR adds isJump to both sneak movements to fix that.
Fixes #4696.
=> Add isJump to sneak actions

src/actions/commands/actions.ts, test/mode/modeVisual.test.ts, test/mode/modeVisualBlock.test.ts, test/mode/modeVisualLine.test.ts
The cursor position after executing `J` command in visual (line / block) mode is different from expected.
**e.g.**
In the following state, for example,
```
o|ne
two
three
four
five
```
now, if execute `vjjjJ`, we will get the following state in the original Vim.
```
one two three| four
five
```
(The cursor should be in the space in front of the last word.)
but now, it's like this:
```
one| two three four
five
```
the same is true for visual line mode and visual block mode.
Same fix is not made for `gJ` because `[count]gJ` doesn't work properly... (#2207)
=> Fix cursor position after executing `J` in visual mode

src/actions/operator.ts, test/mode/modeNormal.test.ts
**Bugs:**
Incorrect behaviour when cursor is in the middle of a line.(fixed by expanding start and end.)
**Small Refactor:**
Indentation should be got in paragraph reflow rather than being passed in as a parameter.
Fixes #4590
=> `gq` range when cursor is in the middle of a line.

src/history/historyTracker.ts, test/configuration/remapper.test.ts
Fixes #4787 
Passes manual testing, however, I'm not able to run `npm test` and I'm currently not sure if that happens only on my computer or whether it is a common issue.
=> Fix insert mode remaps leaving behind a character

src/mode/modeHandler.ts
Fix macros not updating cursorsInitialState before each action
fixes #4827
On issue #4827 when it makes the second 'yy' to yank line the YankOperator will set the cursors to cursorsInitialState which hasn't been changed since the beginning of the macro replay. The cursorsInitialState should have the cursors state before each action.
=> Fix macros not updating cursorsInitialState before each action

src/history/historyTracker.ts, test/mode/normalModeTests/dot.test.ts, test/multicursor.test.ts
- Fix DotCommand deleting extra character when used after a remapped \<Esc\> in insert mode
Fixes #4817 and fixes #4814
- Fix remapped \<Esc\> leaving trailing character when used with multiple cursors
Fixes #4811
=> Fix bugs with a remapped <Esc> in insert mode

src/actions/commands/insert.ts, src/error.ts, test/mode/modeInsert.test.ts
Fixes #4846 
Throw E29 when there are no actions in '.' register
=> Throw E29 on empty `.` register

src/actions/commands/insert.ts, src/mode/modeHandler.ts, test/mode/modeInsert.test.ts
Fixes #4841 
The existing implementation did not reset `vimState.actionsCount` when we perform action that put user in insert mode after pressing `<C-o>`
=> Reset vimState.actionsCount when <C-o> pressed in insert mode

src/actions/commands/actions.ts, src/common/number/numericString.ts, test/mode/modeNormal.test.ts, test/number/numericString.test.ts
**The reason**
I've noticed the code about `<C-a>` and `<C-x>` is very fragile.
So I refactored it.
**What this PR achieves**
This PR totally fixes #4308, fixes #4457 and more.
Please check newly-added tests to get part of what this PR achieves.
These tests **all fails** without this PR, all of them are the correct behavior of original vim.
Now it's behavior on `<C-a>` and `<C-x>` is 99% similiar to the oiginal Vim.
**To the maintainer**:
PLZ don't ignore my pull request again... :-/
If something went wrong, at least give me a hint.
=> Refactor <C-a> logic

src/mode/modeHandler.ts
Fix recording macro not showing after 'setText'
- If 'setText' was called somewhere else like when undoing or when ':w'
the Recording info would be lost
- This commit makes it so that after the next key press we will get the
info back, this is the same behavior as Vim
Fixes #4753
The `Recording @` message was being erased because every time the `StatusBar.setText` is called it replaces the existing text with the new message.
This happens, for example, when the `:write`  command calls `setText` or when you undo something, which might happen in the middle of the macro recording and erases the recording message.
The message would only update again with the `Recording @` after a mode …
=> Fix recording macro not showing after 'setText'

gulpfile.js, test/index.ts, test/runTest.ts
Currently when you run `npx gulp` to build and run the tests it creates a Docker image from Dockerfile but it uses the extension root path as the context to build the image even though it is not needed. This means that every time we run the tests we are sending over 400MB to the daemon just to build the image and we don't even use anything from that context.
I changed the context to the `./build/` folder that contains the Dockerfile.
Then we create a container from that image but we don't give it the `--rm` flag which means after a while we have docker full of stopped vscodevim containers. I have added that flag to remove the container when done with the tests.
Also the `runTests.ts` file had the wrong path to 'extensionDevelopmentPath' because the …
=> Fix docker tests

README.md
The workaround for linux key changes & vsCode, which is displayed on line 713 ( "keyboard.dispatch": "keyCode"  ) had 'keycode' but it should be 'keyCode'. Using 'keycode' does not resolve the issue. The link 'known issue in VS Code' has the solution in it, and they also use keyCode. I've tested that keyCode resolves the issue still.
=> Fixed the workaround on line 713 so that it actually works

src/actions/commands/actions.ts, src/configuration/remapper.ts, src/mode/modeHandler.ts, src/state/recordedState.ts, test/configuration/remapper.test.ts, test/mode/modeNormal.test.ts
Change Count handling when remapping:
- The count value is already stored on RecordedState so we only need to
send the remap keys and the corresponding actions will act accordingly
- The commands weren't respecting the count, if we mapped '<' in visual
mode to the command 'editor.action.outdentLines' we couldn't use it with
count, now we can.
- If you pressed '2d3w' it would delete 23 words, when it should multiply both counts and only delete 6 words. This PR implements an `'operatorCount'` to keep track of the count before the operator to be able to multiply it to the count numbers after it.
fixes #2244
fixes #4903
I've only added a simple test. But I'm trying to create a new …
=> Change count handling on remapping, vscode commands and operators

package.json, src/configuration/vimrc.ts
This PR adds support for `init.vim` for automatic detection in `vim.vimrc.enable`.  We need this because as neovim becomes more and more popular, more people will be using `init.vim` files instead of `.vimrc` files.  Now, many people use both, and tell their `init.vim` to source `.vimrc`.  I put the `init.vim` as the lowest priority; favoring `.vimrc` before `init.vim`.
I was thinking of making an issue for this this morning, when I figured I could probably do it myself.  Should I make an issue too?
I put the `init.vim` as the lowest priority; favoring `.vimrc` before `init.vim`.  I looked through [vimrc.test](https://github.com/VSCodeVim/Vim/blob/master/test/configuration/vimrc.te …
=> Add `init.vim` support for vimrc

src/actions/commands/actions.ts, src/mode/modeHandler.ts, test/macro.test.ts
Fix macros not handling registers correctly:
- Recording a macro with an uppercase letter whose register doesn't
exist yet, now creates that corresponding register
- After finishing recording a macro by pressing 'q' no longer throws an
error with 'concat'
- Calling a macro that doesn't exist no longer throws error. It just
returns the same vimState.
- Add tests for these cases
fixes #4948
=> Fix macros not handling registers correctly

src/actions/plugins/surround.ts, test/plugins/surround.test.ts
Fix surround alias using wrong shortcut version
- Shortcut alias were using the version with space but they are supposed
to use the version without space
fixes #4965
- Add 'a' shortcut alias to '>'
- Add tests for alias
- Add some tests for visual and visual line mode (they are not extensive
but should be enough for now) but they are currently being skipped
because of issue #4973
fixes #4965
I've added the alias 'a' to '\>'. I've also added some visual mode tests, they're not very extensive but should be enough for now just to have something. However, those visual tests are currently being skipped because of issue #4973
=> Fix surround alias using shortcut version with space instead of the ones without

src/actions/commands/actions.ts, test/mode/modeInsert.test.ts, test/mode/modeNormal.test.ts
This PR implements a count for repeat by "."
Fixes #2192
Here is one more simple change.
This replaces the "exec" method by an "execCount" method. I assume that is the correct thing to do.
But I do not know the codebase or  TS well enough to really know that.
It passes tests (although I found only one other test in normal mode with repeat) and it "behaves" correctly when I run the build.
First build failed on one new test, as expected:
https://travis-ci.org/github/VSCodeVim/Vim/jobs/708243710
=> Implement count for CommandDot

package.json
Change the up/down arrow keys to check only if the 'parameterHints' or 'suggestWidget' are visible because the `parameterHintsMultipleSignatures` and the `suggestWidgetMultipleSuggestions` stay true even when the widgets aren't visible.
fixes #5029
=> Fix bug on issue #5029

src/cmd_line/subparsers/deleteRange.ts, src/cmd_line/subparsers/digraph.ts, src/cmd_line/subparsers/file.ts, src/cmd_line/subparsers/marks.ts, src/cmd_line/subparsers/read.ts, src/cmd_line/subparsers/sort.ts, src/cmd_line/subparsers/substitute.ts
Fix some commands not ignoring whitespace properly
- Some commands have a different behavior when called without arguments
and weren't considering the cases when called with only whitespace as no
arguments
For example, the `:marks` command when called without arguments list all the marks. But if you called it with trailing whitespace like this `:marks         ` it would try to find the mark ' ' (\<space\>) and return "No marks set" when it should've listed all the marks.
=> Fix some commands not ignoring whitespace properly

src/mode/modeHandler.ts, test/mode/modeVisual.test.ts
Fix visual mode not preserving desiredColumn
- When moving horizontally on visual mode the desiredColumn wasn't being kept correctly, because we were updating the desiredColumn after correcting our cursors by shifting the stop to the right so that vscode included our stop on its selection.
- Add test for this.
fixes #5048 
Why are we changing our cursors just to make vscode selection include the last character? Couldn't we just set the editor selections with the adjusted positions on 'updateView' without changing our cursors?
Also we are doing this adjust on 'runAction' when the start is before stop but then on 'updateView' we also make another adjust when start is after stop …
=> Fix visual mode not preserving desiredColumn

extensionBase.ts, src/configuration/remapper.ts, src/mode/modeHandler.ts, src/state/vimState.ts, test/mode/modeVisual.test.ts
Implement better synchronization of selections
- Store our selections when calling 'updateView' to be later ignored.
- Create a 'ignoreIntermediateSelections' flag that is set when running
an action to ignore any selection changes triggered by any step of that
action.
- When getting a selection change event we first check if it is one of
our selections. If it is we ignore it, if it is not we still ignore it
if the 'ignoreIntermediateSelections' flag is set or if we have other
selections to ignore, because that means this selection slipped in after
the end of the action. Otherwise we handle it.
- Create new handle for selection changes with kind 'Command'. (this is
triggered by editor commands like 'smartSelect.grow' but is also
triggered when we set …
=> Implement better synchronization of selections

package-lock.json, package.json, src/configuration/configuration.ts
Fixes #4503 by passing `languageId` in `getConfiguration`.  This required updating to `@types/vscode` 1.42, which appears to be the earliest version that supports this API.
=> make getConfiguration use the document languageId (fixes #4503)

extensionBase.ts
When entering composition state to enter Chinese characters we now don't send the characters to Vim even in insert mode, we only send them after composition end. This should also allow to use Chinese characters in remaps on insert mode.
fixes #4815 
fixes #5237 
=> Fix remaps when entering chinese input mode (composition state)

src/mode/modeHandler.ts
Stops the 'executeOperator' function from changing the editor selections.
- These selections will be changed on 'updateView' using the logic to
ignore them if needed
- This was in some cases creating a selection change event after the end
of the action and after 'updateView' had already finished. This event
would then wrongfully update the cursors.
fixes #5257 
I think I had previously removed this already, but it might have leaked through again in some merge conflict without me noticing it.
=> ExecuteOperator doesn't need to change selections

src/configuration/remapper.ts, src/mode/modeHandler.ts, test/configuration/remaps.test.ts
Fix remap bug with '<' and special keys remaps
- Fix remaps confusing '<' as potential remap to special keys like '\<C-x\>'
- Add test for this situation
- Prevent showing special keys like '\<C-x\>' with virtual key decoration
I don't think anyone has reported this yet
=> Fix remap bug with '<' and special keys remaps

gulpfile.js
It always changed to backslash, resulting in paths like 'out\src\platform\node' where the '\n' of '\node' would be considered a new line.
Build wasn't working on windows.
I've made this as a quick fix. It is what I've been doing manually every time. If there is a better way to fix this feel free to change it. I just wanted to get this fix in master so that I don't have to continuously add and remove this fix every time I change branches.
=> Fix gulpfile updatePath on windows

extensionBase.ts, src/configuration/remapper.ts, src/mode/modeHandler.ts, test/configuration/remaps.test.ts
Stop user forced stop remap from throwing error
- When the user force stops a recursive remapping it shouldn't throw an
error, it should just set the 'vimState.forceStopRecursiveRemapping'
which will then make all the remaining keys be ignored until the
recursive remap finishes.
- Add test for forced stop remaps on non infinite recursive remaps.
fixes #5419 
fixes #5347 
fixes #5219 
Some of the fixed issues are closed, but they were closed because the user changed remap to use `"after": ["<Esc>"]` instead of `"commands": ["extension.vim_escape"]` and the 'after' approach is still the preferred one, however the error shouldn't be thrown when using the command approach either, so …
=> Stop user forced stop remap from throwing error

src/actions/operator.ts
See https://doc.rust-lang.org/reference/comments.html
Currently there's a problem where if you have:
```rust
//! A library for reading in Verilog $readmemb/$readmemh files formatted per IEEE Std. 1364-2005, §17.2.9
```
and the user goes onto the long line and does `gqq`, it will split it into two lines like this:
```rust
//! A library for reading in Verilog $readmemb/$readmemh files formatted per
//IEEE Std. 1364-2005, §17.2.9
```
This is incorrect. It should do this:
```
//! A library for reading in Verilog $readmemb/$readmemh files formatted per
//! IEEE Std. 1364-2005, §17.2.9
```
**Which issue(s) this PR fixes**:
=> Add Rust's INNER_LINE_DOC to reflow list

src/mode/modeHandler.ts
When in insert mode and inserting a snippet it will no longer change to visual mode, now it stays in "Insert Mode" or "Insert Mode - Multicursor".
fixes #5240
fixes #5474
fixes #5538 
I've also reverted the ModeHandler static logger change, because like I mentioned before that made it so the logger was no longer working.
=> Stop snippet insertion from going to visual mode

src/actions/commands/actions.ts, src/actions/commands/commandLine.ts, src/actions/plugins/easymotion/easymotion.cmd.ts, src/configuration/notation.ts, test/cmd_line/tabCompletion.test.ts, test/configuration/notation.test.ts, test/mode/modeNormal.test.ts
Implement normalization for 'Shift+Tab' key combo
- \<Shift+Tab\> key was being captured but had no normalization
implemented, so only '\<shift+tab\>' would work.
- This commit, makes '\<s-tab\>' work as well
This basically makes it possible to use `<S-tab>` in remaps as well instead of only `<shift+tab>`.
fixes #4719
I've implemented only the `<S-tab>` notation since that is what normal Vim works and `<shift+tab>` to keep the same philosophy that was implemented for `<ctrl+...>` and `<cmd+...>`. This should allow for the normalization of any `shift+...` key combination, however currently we only capture `<Shift+Tab>` and `<Shift+BS>`.
I didn't implement `<Shift-Tab>` as suggested …
=> Implement normalization for 'Shift+Tab' key combo

src/mode/mode.ts, src/mode/modeHandler.ts
Simulate cursor "disappearing" on CommandLineMode
- Change the cursor in both command line modes to be 'UnderlineThin'.
I don't think we can actually make it disappear so this is the closest
to it. It at least allows the user to have a feedback that they are now
typing on a different place.
fixes #5198 
=> Simulate cursor "disappearing" on CommandLineMode

src/actions/plugins/easymotion/easymotion.cmd.ts
Fixes bug where `<C-o>` and `<C-i>` do not work after an easy motion movement.
Fixes #5730
The bug is due to isJump not being set on the BaseCommand class which means it's not recorded in the movement history.
Really great plugin. I use it every day. Thanks for all the hard work and effort put into this.
=> Fix bug where <C-i> <C-o> do not work after easy motion movement #5730

src/jumps/jumpTracker.ts
Remove zombie data creator
- When we perform a file jump (with \<C-o\> or \<C-i\> for example), the 'activeTextEditorChangedEvent' will already take care of getting the correct cursors to that new editor's `modeHandler`. Then we would call this 'getCursorsAfterSync' that would get the cursors of that new editor and apply them to the previous editor's `modeHandler` (which makes no sense)
- In this case we don't need to change cursors at all.
This would add an expected selection change that would never come (because it was from another file), thus leaving that "zombie" data). All further selection changes would then be ignored.
fixes #5813 
Might fix a bunch of the other issues we have with cursors failing or being …
=> Remove zombie data creator

src/actions/commands/actions.ts, test/multicursor.test.ts
Fix CommandSearch throwing error in multicursor
- Searching with `/` or  `?` no longer throws "Maximum call stack size exceeded"
- Set `runsOnceForEveryCursor` to false on `/` and `?` actions so that it doesn't try to run for every cursor when in multicursor.
fixes #5844
=> Fix CommandSearch throwing error in multicursor

extensionBase.ts, package.json
Remove "vim.remap" from the command palette
- This command is supposed to be used in keybindings, it can't be used
directly from the command palette
- fixes #5841
We should add an entry for this command explaining its use on the README file. I just don't know were or if we should even do it at all. I'm afraid it might create more confusion and future issues.
We really need a Wiki! 😄 Then we could add an advanced section inside a Remappings section where we could add this.
I also think this might be the cause of the issues related to #5306. But I'm not sure because no one as yet explained what they were doing...
=> Remove "vim.remap" from the command palette

package.json, src/configuration/configuration.ts, src/configuration/decoration.ts, src/configuration/iconfiguration.ts, src/mode/modeHandler.ts, test/testConfiguration.ts, yarn.lock
Adds the ability to see what marks you have set in the gutter.
This PR expands on the great work @gamcoh has in #4715 and adds the mark name to the "bookmark" icon (see screenshots below). Since this might not be everyone's cup of tea, I've added a new setting to enable / disable this (defaults to disabled).
This is my first PR in this project; let me know if I missed anything!
* Closes #3963
* Closes #5119
* Relates to #4710
_NOTE: the default is currently set to **off**_
=> Show Marks in Gutter

.github/CONTRIBUTING.md
1. `yarn test` runs `node ./out/test/runTest.js` which doesn't work because `out/test/runTest.js` does not exist yet.  Add `npx gulp prepare-test` step.
2. Mention how to build `.vsix` extension.
Mentioned as a side note in #5892
=> Document build/test process better

src/actions/operator.ts, test/mode/modeNormal.test.ts
Fixes the `gq` operator to not discard blank lines at the beginning or end of a chunk, like Vim does. This turned out to be a one-line change: blank lines at the beginning and end of a chunk were getting accidentally removed via an extra `.trim()` call. There was already code to properly deal with blank lines (which previously handled cases like reformatting two paragraphs separated by blank lines, but now also handle initial and final blank lines).
#2393 shows examples of the bad behavior.  Open any text document with multiple paragraphs (separated by blank lines), such as the repository's `README.md`.  Type `gqap` on a long-line paragraph (e.g. `VSCodeVim is a Vim emulator...`) and the newline(s) after that paragraph will disappear with the old …
=> Fix gq to preserve blank lines like Vim does (fix #2393)

src/actions/motion.ts, test/mode/modeNormal.test.ts
When `changeWordIncludesWhitespace` is `false`, 'cw' is supposed to act like 'ce' when the current character is a non-blank.  However, it is supposed to act like a regular 'w' motion when activated on a blank character.  This fixes a small typo for correctly detecting this case.  I also added a test to cover this case.
(haven't opened one, can do so if you wish)
* I'm surprised TypeScript allowed this bug.  I realized via `console.log` that `line[position.character]` was `undefined`.
=> Fix 'cw' behavior on whitespace

extensionWeb.ts, src/configuration/configuration.ts, src/platform/browser/constants.ts, src/platform/node/constants.ts, webpack.config.js
The Vimrc uses look back regex, which is not supported on Safari. Since we are not loading vimrc at all, instead of tweaking the regex, we can off load the vimrc module completely.
=> off load vimrc module in web

extensionWeb.ts, src/configuration/configuration.ts, src/configuration/validators/neovimValidator.ts, src/mode/modeHandler.ts, src/textobject/word.ts, src/util/externalCommand.ts, webpack.config.js
This is necessary as the new Webpack doesn't have them out of the box, which broke the extension running in Web.
=> Polyfill OS/Process/setImmediate

.github/CONTRIBUTING.md
For the "duplicate" link, I provided a sample search for "cursor" which returns 200+ issues. Many of which probably aren't duplicates, but I thought that might be a good starting point. MIght be better to link to a blank search for open issues.
For the "old" link, I gave page 25. Currently there are 34 pages, so I thought that would be sufficient insulation to still be "old" but not get shwooped off later
I saw a few folks claim that VSCodeVIM Team gives precedence to issues with more thumbs up, so I included that recommendation. I didn't want to say that so explicitly though, since I don't actually know.
**What this PR does / why we need it**: Some folks may want to contribute outside of code.
**Which issue(s) this PR fixes** I didn't create an issue for this, though …
=> Added "Improve Existing Issues" notes

src/configuration/notation.ts, src/mode/mode.ts, src/mode/modeHandler.ts, src/mode/modeHandlerMap.ts, src/state/vimState.ts, src/statusBar.ts
This PR starts cleaning up dependency cycles, which make code sensitive to the module initialization order.
#6177 (partially)
A very general plan is to make central types, such as vimState, globalState, recordedState and configuration to not depend on actions/commands and their parsers. Instead they will deal with commands/motions via interfaces.
=> Fix several dependency cycles

src/history/historyTracker.ts, src/jumps/jumpTracker.ts, test/historyTracker.test.ts, test/jumpTracker.test.ts
Implements previous context marks as described in Vim's `help m'` / `` help m` ``.
https://github.com/VSCodeVim/Vim/issues/4873
First contribution to the project, so please let me know if there's anything I can do differently. Thanks!
=> Implement previous context marks (add to jump list on m' / m`)

package.json
**What this PR does / why we need it**: <kbd>C-d</kbd> behavior is inconsistent with vim.use.
=> More consistent behavior of C-d

src/actions/operator.ts, test/mode/modeNormal.test.ts
* Rewrite 'gq' reflow to apply manual spacing (including `joinspaces` option) just when creating whitespace from what were linebreaks.
* Fix precision around `textwidth`. Now exactly fills lines to width `textwidth`, just like Vim. There's a test to verify this. This required modifying previous test outputs.
Fixes #6569
* I'm having trouble running the added tests locally, so I might need to tweak them slightly.
=> gq preserves whitespace between line breaks

src/cmd_line/commands/vsc.ts, src/cmd_line/commands/vscode.ts, src/cmd_line/subparser.ts
Add a `:vsc` command to run VSCode commands, including extension commands. 
Examples: 
```
:vsc editor.action.organizeImports
:vsc gitlens.toggleFileBlame
```
As a bonus, we can now map extension commands in vimrc. 
```
noremap <leader>glf :vsc gitlens.showFileHistoryView<CR>
```
#4463, #4733, probably others. While PR #4750 is another attempt at solving these issues, adding a new command is more in-line with approaches by other Vim emulators. e.g. VSVim uses `:vsc` and Ideavim uses `:action`. 
=> Implement :vsc to run VSCode commands

src/statusBar.ts
If you chose to customize your modes under `vim.statusBarColor`, and since `statusBar.debuggingBackground` is registered to colorCustomizations so it uses your current mode background, using debugger can render the statusBar unreadable. I'm simply registering the missing `statusBar.debuggingForeground`, so the statusBar uses both your mode's background and foreground, not just the background.
=> Add debuggingForeground to colorCustomizations

src/cmd_line/subparsers/substitute.ts, test/cmd_line/subparser.substitute.test.ts, test/cmd_line/substitute.test.ts
Fix `\` escaping in `:s` substitution commands. The pattern and replacement need to be processed differently, because `\`s need to be preserved in the pattern for passing to `RegExp`, whereas they need to actually be processed in the replacement.
* `parsePattern` generally leaves backslashes alone, passing them on  to the regular expression parser.
* New `parseReplace` interprets backslashes.  New definitions for `\b`  (backspace), `\&` (same as `$&`), and `\0` through `\9` (same as  `$1` through `$9`).
* Rewrite these parsers in imperative style to avoid any stack overflow.
Fixes #6890
I'd like to change how search (`/`) works as well, for #6520. But I'm finding …
=> Fix escaping in :s substitutions

src/state/searchState.ts, test/mode/modeNormal.test.ts
Require an odd number of `\`s before c for the case (in)sensitivity triggers `\c` and `\C`, enabling search for `\c` via `/\\c`.  This seems to match how vim works.
Fixes #6520.
* Thanks for the [pointer](https://github.com/VSCodeVim/Vim/pull/6891#issuecomment-883776019) to `searchState.ts`. I actually didn't know `\c` was a vim feature, which explains why it was just this particular case that was causing problems.
* I used lookbehind assertions which is not supported in all browsers, but seems to work fine in VSCode/Node.
* `/[\c]` is equivalent to `/c` in vim, but it still won't work with this patch. This seems less common, and I'm not sure how robustly I could fix it with a …
=> Fix /\\c by requiring odd number of \'s before c for case (in)sensitivity

src/actions/languages/python/motion.ts, src/state/searchState.ts
The newly introduced look behind regex breaks Vim in VS Code on Safari.
=> Remove look behind for Safari

src/actions/motion.ts
Fix microsoft/vscode#130425.
VS Code introduced a new Interactive Window editor whose input box is a regular editor with history support. However the history are navigated through arrow keys, which conflict with Vim. In this PR, we call VS Code's command to do history navigation when it's in insert mode and the cursor is at the first line or last line.
=> Fix history navigation in VS Code interactive window

package.json
Hi, this is developer from VS Code. As we are rolling out web extensions we are trying to fine tune and simplify the concepts around web extensions. As a result, we are no longer supporting web as an extension kind to identify as a web extension. Instead we infer it from other properties - See https://github.com/microsoft/vscode-docs/blob/vnext/api/extension-guides/web-extensions.md#web-extension-enablement for more details. With latest vsce, it will validate extension kind for appropriate values which are `ui`, `workspace`. Since this extension has `web` extension kind, this PR fixes it properly.
It seems vim aways wants to run close to UI, so it is recommended to mark it as strict ui extension so that it will run close to UI in any environment.
Hence changed vim extension kind to be …
=> make vim strict ui extension

src/cmd_line/commands/bang.ts, test/cmd_line/bang.test.ts
Fixes the bang `!` command when used with a range, which is currently broken since any bang commands with ranges operate on all lines since the range isn't passed in properly.
Also improved some tests which should've detected this regression, but didn't because they executed on all lines.
#3136
=> Fix bang command with ranges

src/textobject/word.ts
`configuration.iskeyword` is evaluated only once when the extension is initialized. This means that `iskeyword` for a specific language is not respected when it's different from the language used for initialization. This PR solves the issue by evaluating it every time the word movement command is called.
#7123
=> iskeyword is evaluated when a command is called (#7123)

src/util/child_process.ts, src/util/externalCommand.ts
Refactors `externalCommand.ts` to use event emitters instead of temporary files to read the command output into the Vim buffer. This is much more cross-platform friendly. Creating temporary files and file paths are OS-dependent, which has made it difficult to build a `vim.shell` setting for #7100... so instead, this PR lets `exec`'s event emitters handle reading stdout/stderr for us. 
No change in behavior as this is an under-the-hood change, and existing tests in `bang.test.ts` and `filter.test.ts` pass.
N/A
=> Refactor `externalCommand.ts` to not use temporary files

src/actions/base.ts, src/actions/commands/actions.ts, src/actions/commands/put.ts, src/actions/commands/replace.ts, src/actions/operator.ts, src/actions/plugins/surround.ts, src/cmd_line/commandLine.ts, src/cmd_line/commands/quit.ts, src/cmd_line/commands/write.ts, src/cmd_line/commands/writequit.ts, src/cmd_line/commands/writequitall.ts, src/mode/modeHandler.ts, src/state/recordedState.ts, src/state/vimState.ts, src/vimscript/exCommand.ts
Adds a boolean property "isRepeatableWithDot" to exCommand to identify commands which should and should not be repeatable via dot command.
Adds a boolean property "lastCommandDotRepeatable" to vimState to keep track of if the last command executed is repeatable via dot command and should update the globalState.previousFullAction.
Resolves an issue where save, quit, and savequit commands would be treated as repeatable for the purpose of the dot command, making the dot command less effective.
fixes #6829 
New to the code base and new to open source, feedback appreciated!
=> Exclude :w, :q, and :wq from dot command

src/actions/commands/commandLine.ts, test/cmd_line/tabCompletion.test.ts
Tab completion of file names should be case insensitive on Windows
fixes #7160 
=> Tab completion of file names is case insensitive on Windows

src/cmd_line/commandLine.ts
I think it should fix all the lately reported bugs with "Failed to handle key ... Cannot read property 'substring' of undefined"
fixes #7512
and lots more of them.
=> fix bugs with: Failed to handle key ... Cannot read property 'substring' of undefined

src/vimscript/pattern.ts
Using timeout is more correct then limiting the search results.
#6957
I think 1 second should be enough. We can finetune this value for better experience.
We can use both timeout and max number of ranges, but as a conjuction:
```ts
if (timeout && before.length + after.lenth > MAX_RANGES) {
break;
}
```
This will keep the current behavior, while allowing more searches to be found.
=> Use timeout for search

.github/workflows/release.yml
Hey there VS Code Vim team 👋!
This PR adds automatic publishing to the OpenVSX registry and therefore fixes #7183.
There are some more steps to take:
1. Add a repo secret for GitHub Actions called `OPEN_VSX_TOKEN` with a PAT obtained via following [this guide](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) (steps 1-4)
2. After merging, try publishing for the first time 🚀
3. (Optional) claim the namespace by following [this doc](https://github.com/eclipse/openvsx/wiki/Namespace-Access#how-to-claim-a-namespace) so that the extension is verified on the registry.
cc @J-Fields
=> Publish VSCodeVim to OpenVSX

src/configuration/configuration.ts
Default hanldeKeys' value at configuration seems to be an object.
=> Fix default hanldeKeys' type and value at configuration

package.json, src/configuration/configuration.ts, test/configuration/configuration.test.ts
Currently the vim.textwidth setting is global which means that all
languages must share the same value. This works most of the time but
for some cases like git commits it can be useful to have a custom value
to adhere to specific guidelines.
This updates setting configuration to be "language-overridable" which
allows VSCode to autocomplete the value in the settings page for
languages. This allows us to update the `textwidth` property to a getter
where VSCode will automatically return the correct value.
Fixes https://github.com/VSCodeVim/Vim/issues/4993
I don't typically work on VSCode extensions so if there's a better way to test this I'd appreciate any feedback on how to improve …
=> Make vim.textwidth configurable per-language

src/common/number/numericString.ts, test/mode/modeNormal.test.ts, test/number/numericString.test.ts
Current impl of `<C-a>` and `<C-x>` lowercases hex string even if original string is capital.
This PR preserves lowercase/uppercase in below strategy:
1. If the string is hex string, find the last alphabet in the word, check if it is lowercase/uppercase.
2. If the hex string doesn't have alphabet in it, think it as lowercase.
3. If the string is not hex, think it as lowercase.
4. Finally, when doing `toString()`, transform whole hex string to lowercase or uppercase. 
=> Preserve case when inc/decrement (`<C-a>`/`<C-x>`) num

CHANGELOG.md, src/actions/commands/fold.ts
Add folds using the new vscode commands "editor.createFoldingRangeFromSelection" and "editor.removeManualFoldingRanges".
Everything seems to work fine except for the cursor position in some cases. For some reason setting `vimState.cursors` does not work.
fixes: #4865
Testing is in WIP.
=> Folding visual selected lines (`zf`)

src/actions/commands/actions.ts, src/actions/commands/put.ts, src/actions/operator.ts, test/operator/put.test.ts
Previous fix for #7870 resulted in all blockwise text being right padded when yanked into a register, but text should only be right padded as necessary (based on surrounding document text) on put command execution.
Fixes #7870 "Text is not aligned when pasting a range yanked in blockwise"
The previous discussion we had is visible on d8c50a1.
I reverted the changes for d8c50a1 in this PR as well.
=> Fix for pasting ragged blockwise text

src/actions/operator.ts, test/mode/modeVisualBlock.test.ts
Visual block indent operator should have different behavior from visual and visual line indent operators, but they're all currently implemented the same way. This PR correctly implements the visual block indent operator.
Fixes #7640 
I noticed that the visual block outdent operator also doesn't work as expected, so I'll submit another PR later on to fix that issue.
=> Implement correct behavior for visual block indent operator

src/actions/motion.ts, test/mode/modeNormal.test.ts
Fix incorrect behavior of `cW` when the cursor is at the end of a word
fixes #7981 
=> Fix: cW behaves incorrectly when the cursor is at the end of a word

src/actions/operator.ts, test/mode/modeVisualBlock.test.ts
Visual block outdent operator has its own unique behavior in Vim/Neovim that's not currently emulated by VSCodeVim. This PR implements the operator correctly.
No issue had been posted concerning visual block outdent operator. See #8007 for previous discussion on visual block indent operator.
=> Implement correct behavior for visual block outdent operator

src/actions/commands/put.ts, test/operator/put.test.ts
Cursor position may be incorrect after `gp` and `gP` operations. This PR correctly adjusts the cursor position and fixes one test case that was incorrect.
Related to the changes for #7870
=> Fix cursor position after visual block gp and gP operations

.vscode/tasks.json
Add task 'prepare-test' to tasks.json in order to do RUN AND DEBUG 'Run Tests'  on VS Code.
Before this PR, when select 'Run Tests' and press F5 key, this error was displayed.  
`Could not find the task 'gulp: prepare-test'.`
not yet
=> Add task 'prepare-test' to tasks.json

webpack.dev.js
Webpack sourcemaps were disabled in f02ed71ed848d8aca2e1fef77d8d2490a3b9e1e7, which inadvertedly also stopped vscode from picking up sourcemaps when debugging the extension. This resulted in vscode breakpoints not working at all.
Couldn't find any reported issues regarding this - I encountered it while working on https://github.com/VSCodeVim/Vim/pull/8077.
=> Enable sourcemaps in dev builds

.github/ISSUE_TEMPLATE/bug_report.md
This PR corrects a typo in `bug_report.md` in which there is a line that says to run "Developers: Show Running Extensions". There is no such command in VSCode. Rather the correct command is "Developer: Show Running Extensions"
fixes #8387
=> Fix typo in `bug_report.md`

src/mode/modeHandler.ts, src/transformations/execute.ts, test/mode/modeInsert.test.ts
By default in VSCode with VSCodeVim disabled, selecting text and typing an opening bracket or quote will surround the selection, while *keeping the selection*, allowing for further non-surrounding keystrokes to overwrite the selected text.
Currently, with VSCodeVim enabled, in insert mode the functionality is still partially present, but broken.  
The text gets surrounded, but the selection is lost, and the cursor is placed one character short of the right end.
This is a pain when filling in snippet holes with strings.
I want to be able to just type my new text in, but when VSCodeVim is enabled, if I am inserting a string or bracketed expression, I have to delete the placeholder text first to prevent it from interfering.  
e.g. if the selected …
=> Fix #7159 bad handling of auto-surrounding selections

src/textobject/sentence.ts, test/motion.test.ts, test/sentenceMotion.test.ts
This change updates the definition of a sentence to be more in line with vim's definition.
Today, a sentence end is a punctuation character (`.`, `?`, `!`) followed by whitespace/line end - which means that something like `(potential sentence end.)` doesn't count as a sentence end (even though it does in vim).
With this change, we allow a sentence end to include any amount of closing: 1. single quotes; 2. double quotes; 3. parentheses; 4. square brackets.
#8390 
none
=> update sentence definition to allow for closing quotes/parens/squarebrackets

extensionBase.ts, package.json, src/taskQueue.ts, yarn.lock
The commit 50bc4fe1e32434cc15098173a5dfc42c7818ac8e removed `TaskQueue`. But some issues rised after this commit like: #8577 #8603
I have investigated this issue and foud that there are some nested event invocations. With `TaskQueue`, these events are added to a queue and processed event by event. But as of 1.26.0, some events are invoking other event processing immediately before finishing current event and this behaviour is different from pre 1.26.0 versions.
This commit is just a revert of 50bc4fe1e32434cc15098173a5dfc42c7818ac8e.
#8577 #8603
I think there are two ways to solve this problem:
- Find and fix all nesting issues case by case
- Task queue recovery
For this commit I …
=> Revert TaskQueue removal

src/cmd_line/commands/file.ts
Fixes the use of `:sp`/`:vs` with non-existing files, opening a new split with the specified file and creating it right away (the file will need to be manually saved to apply changes).
Fixes #7283
Partially fixes #8671
=> Support to `:sp`/`:vs` open non-existing files.

src/mode/modeHandler.ts, test/mode/modeVisual.test.ts
The selectin can't correct sync when use 'editor.action.smartSelection.expand' in VisualLine mode.
The sync problem has fixed in pr #5015, but VisualLine is not included.
Now, If you use 'editor.action.smartSelection.expand' in VisualLine mode,  the mode will change to Visual mode. The behavior is the same as nvim-treesitter and ideavim
fixes #8773
=> Fix incorrect expand selection in VisualLine mode(#8773)

extension.ts, extensionBase.ts, src/configuration/vimrc.ts
- Fix a typo in the warning message that appears when the .vimrc file fails to open.
- Now uses `loadConfiguration` from extension.ts instead of `configuration.load`.
- Now uses `context.globalStorageUri.fsPath` instead of `context.globalStoragePath` which is deprecated.
=> Fix .vimrc warning & more

src/actions/commands/put.ts, src/mode/modeHandler.ts, test/mode/modeInsert.test.ts
The pull request fixes several annoying issues with the positioning of the cursor when using `Ctrl-o` in INSERT mode.
1. https://github.com/VSCodeVim/Vim/issues/8948
2. https://github.com/VSCodeVim/Vim/issues/1791
Refactored interface in `BasePutCommand.getCursorPosition` method.
=> Fix `Ctrl-o` behavior when cursor is behind last character in INSERT mode or when using `p` next

src/actions/commands/scroll.ts, test/mode/modeNormal.test.ts, test/testSimplifier.ts
Set scroll option with `[count]<C-u>` and `[count]<C-d>`.
Rename `CommandMoveHalfPageDown` to `CommandCtrlD` and `CommandMoveHalfPageUp` to `CommandCtrlU`, since HalfPage is only true when `scroll=0`. This also aligns with `CommandCtrlE` and `CommandCtrlY`.
Wrap a docstring with \` since `<` and `>` need escaping in rendered format.
Fixes  #8984
=> Set scroll option with <C-u> and <C-d>

src/actions/plugins/easymotion/easymotion.ts
fixes #9006 easymotionDimColor has no effect
#9006 
This static property is initialized immediately when the class is loaded (due to the nature of static properties in TypeScript/JavaScript), not when an instance of the class is created. it only depends on the file containing the class (easymotion.ts) being processed by the JavaScript runtime.
https://github.com/VSCodeVim/Vim/blob/0e1e48797c5205df914f79a08b6e773be3c6feb0/src/actions/plugins/easymotion/easymotion.ts#L26-L28
So, when we used import, this value is initialized
https://github.com/VSCodeVim/Vim/blob/0e1e48797c5205df914f79a08b6e773be3c6feb0/src/mode/modeHandler.ts#L8
But at this time, the configuration.asymotionDimColor …
=> fixes #9006 easymotionDimColor has no effect

src/cmd_line/commands/only.ts
Currently when running `:only` all editors from other groups are closed. This is surprising for a seasoned vim user because in vim all buffers would be kept open. It's especially annoying when there are terminal opened in editor area executing. some long-running tasks.
=> Don't close editors in other groups with `:only`

src/statusBar.ts
Converts the status bar icon (`--NORMAL--`) into a button. It can be clicked to quickly disable the extension.
The below gif shows it working in the environment
=> Add Toggle button to status bar

src/mode/modeHandler.ts
This PR sets `vim.command` in VSCodeContext to `recordedState.commandString`. This allows pending actions that are waiting for a movement argument (e.g. `d` or `y`) to be read in the `when` clause of keyboard shortcuts.
There is currently no change to VSCodeContext in such a pending state, making it impossible to correctly configure some keyboard shortcuts, such as commands that should be activated in Normal mode, but *not* if a command is started. Making that information available in VS Code's context gives users greater flexibility and precision in setting up custom keyboard shortcuts.
Fixes #7833 by allowing users to add `!vim.command` to the `when` clause of the keyboard shortcut.
**Special notes for your …
=> Set vim.command in VSCodeContext on key press.

src/mode/modeHandler.ts, test/mode/normalModeTests/dot.test.ts
It fixes #7397 and adds three tests for this.
#7397 
Hi there I am happy to make my first contribution to this amazing project!
I implemented the fix for all commands that start with a (numbered) `CommandRegister` action. I could not think of or find a dot repeatable command that has a numbered register in it but does not not start with it. If there is one, please let me know.
BTW: is there a way to filter tests? I do not want to run all tests _while_ I'm trying to fix a small bug 😉
=> Fix 7397 dot with numbered registers

src/actions/motion.ts, test/operator/surrogate.test.ts
It fixes an issue where you'll sometimes need to press 'h' twice to go to the next left char, if your current char is a surrogate pair. 
Happens when the character corresponding to the current cursor position is a low surrogate, so you'll only get to the next left char after you've moved to the high surrogate char (two `MoveLeft`s).
Before:
After this PR:
=> Avoid needing two `MoveLeft`s if the current character is a low surrogate

src/mode/modeHandler.ts, test/mode/modeVisual.test.ts
After executing o twice, keep the selection of the space after the last character
AS-IS
TO-BE
not yet
=> Fix: keep the selection of the space after the last character

src/actions/motion.ts
**What this PR does / why we need it**: This PR makes the moveInsideCharacter behavior more consistent with the actual vim move inside commands like "di(" or "ca{"
Original Line: `this (is) a (bug)`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^
- Old Behavior: `this () a (bug)`
- New/Expected Behavior: `this (is) a ()`
**Which issue(s) this PR fixes**: #9576
**Special notes for your reviewer**: Hi I am new to open source and have never worked on a VS Code extension so I apologize in advance if I did anything wrong.
=> Fix: #9576 | Move Inside Character when multiple character pairs are there and the cursor is out not in between the character pairs

src/actions/plugins/surround.ts, src/textobject/word.ts, test/plugins/surround.test.ts
Big thanks @J-Fields for maintaining this project 😊
Fixes a "change surrounding tag" issue when using kebab case
```html
<custom-tag></custom-tag>
```
When using a command to replace the tag with `h1` you get this:
```html
<h1-tag></custom-h1>
```
- #8177
What I've done to try fix the issue is created a new `WordType` of `TagName`. Currently it's using `nextWordEnd` and `prevWordStart` to select the tag name which is why we are getting that strange behaviour.
=> Fix change surrounding tag, fixes #8177

src/actions/motion.ts, test/mode/modeVisualLine.test.ts
Fixes the weird behaviour when using `VisualLine` mode with the `Vi{` or `Vi(` or `Vi[` when the matching braces are on different lines. The issue is well explained in #9337 (relevant images explaining the problem are present there so I have omitted them here).
As a fix for issue #9337 
Only affects `VisualLine` mode when using `Vi{`. Everything else is left untouched, all tests pass locally.
=> Fixing Vi{ incorrectly grabbing the ending braces
