src/cmd_line/command_node.ts, src/cmd_line/lexer.ts, src/cmd_line/main.ts, src/cmd_line/node.ts, src/cmd_line/parser.ts, src/cmd_line/scanner.ts
=> Assorted fixes

README.md, extension.ts, gulpfile.js, package.json, src/mode/modeNormal.ts, test/extension.test.ts
* Add test to ensure all keybindings have handlers and that they are no duplicate key bindings
* Implement 'ctrl+r'
=> Implement Redo, Refactor Keybindings

src/cursor.ts
* fix line/ column end limitation
=> fix bug for Cursor class

src/cursor.ts, src/mode/modeNormal.ts
=> support x command

extension.ts, package.json, src/mode/modeNormal.ts
This one works better than #44 that I had earlier since it uses the Cursor you guys have in there.
Let me know if any issues
Thanks,
Joe
=> '$' and '^' for Moving to beginning and end of line

.travis.yml, appveyor.yml
Fixes #73 and #24. 
Setting personal token used for TSD in the CI configs.
=> Fix PR builds

CONTRIBUTING.md
I was thinking about the contributing process for a project like this, so I've taken the liberty of drafting a `CONTRIBUTING.md` with some ideas.
It's just a draft, but I figured it would be a good start for a discussion.
=> Added CONTRIBUTING doc

README.md
* compliments of @guillermooo.
=> Readme: update with keyboard configuration 

src/motion/motion.ts
As master changed quite a bit from https://github.com/VSCodeVim/Vim/pull/102, merged the awesome work of @AndersenJ and @markrendle. Fixes #19. 
Caveats:
* Still see a blinking cursor in Normal mode
* Tabs are selected as a whole
=> Block Cursor

README.md, src/keyboard.ts
This is my first pull request that will fix issue #124
=> added danish keyboard layout - fix issue #124

.gitignore, extension.ts, package.json, src/mode/modeNormal.ts, src/motion/motion.ts, src/motion/position.ts, test/motion.test.ts
Add `{` and `}` motions, plus a couple of tests.
=> Add paragraph motions

src/motion/position.ts, test/motion.test.ts
The word motion has a weird edge case where it doesn't go to the final character of a word on any line except the final line. Fixed it and fixed the tests as well.
=> Fix word and back-word motions, and fix tests.

extension.ts, package.json, src/mode/modeNormal.ts, test/mode/modeNormal.test.ts
Something went wonky with the CI last time, but this should be a simple change.
=> Add ctrl-c.

src/motion/position.ts
In my previous commit fixing w/b I didn't actually perfectly fix b, which led to some weird behavior when you hit b on the first letter of the first line. This should fix that.
=> Fix b motion.

test/mode/modeNormal.test.ts
@tienshiao, check out how nice it is! :)
=> Convert test to async/await style.

src/mode/modeInsert.ts
=> Fix for block cursor in insert mode

src/keyboard.ts
=> Spanish keyboard mappings

.travis.yml, appveyor.yml
=> add github_token to appveyor/travis

package.json
I noticed that the automated build failed for your pull request at:
https://github.com/VSCodeVim/Vim/pull/208
I believe this tweak to package.json will fix the issue.
Thanks for contributing to this great tool.
=> I think this may fix the build failure.

README.md
As implemented by f0b53887ee71a76f272482c75d4241658bc0629c
=> Add check mark to D key in README

src/mode/modeHandler.ts
#220 
passes `gulp tslint`.
passes tests.
=> keymap configurations only override defaults that are changed

.travis.yml
=> Install Gulp for Travis

src/mode/modeNormal.ts, test/mode/modeNormal.test.ts
I'm a solipsistic OSX user, my bad!
=> Don't use ctrl-c to leave insert mode by default.

src/actions/actions.ts, src/mode/modeHandler.ts, src/mode/modeVisualLine.ts, src/motion/position.ts
Vim has some really tricky EOL behavior in visual mode that is breaking both visual and visual line mode in subtle ways. Going to fix that next, then add tests for this.
=> Add Visual Line mode

test/mode/modeVisualLine.test.ts
It's not a lot but ugh all this test writing is tiring me out
=> Add visual line mode tests.

src/actions/actions.ts, src/mode/modeHandler.ts, test/mode/modeNormal.test.ts
Also refactor some of the main function.
=> No longer special case insert mode keys.

src/actions/actions.ts, test/mode/modeNormal.test.ts, test/testSimplifier.ts, test/testUtils.ts
This PR encompasses @darrenweston's awesome work on the testing infrastructure. I also fixed the three bugs that he managed to find while adding new tests.
=> @darrenweston's test improvements + more work

src/actions/actions.ts, test/mode/modeNormal.test.ts
I'm just adding things a key at a time until VsCode/Vim matches my muscle-memory. Hope that's OK :smile:
=> Tilde key toggles case and moves forwards

src/actions/actions.ts, test/mode/modeNormal.test.ts
With `getDownByCount`, supporting Nyy is real simple.
=> Implement <count>yy

extension.ts, package.json, src/actions/actions.ts
100% @rebornix, I just did the merge.
=> Rebornix switch pane

ROADMAP.md, src/actions/actions.ts, test/mode/normalModeTests/motions.test.ts
Add four motions
`[(`, `[)`, `[{`, `[}`
=> Unclosed brackets

src/actions/actions.ts
=> Use Arrows in Insert Mode.

src/cmd_line/commands/file.ts, src/cmd_line/scanner.ts, src/cmd_line/subparsers/file.ts, test/cmd_line/scanner.test.ts
=> Use correct API for file open.

README.md
=> Fix Roadmap link in Readme

ROADMAP.md
Users can have ideas of what they can do / do not with v0.1.
=> Update window command status

ROADMAP.md
No related issue, since this is pretty trivial and probably only bothers me.
=> Fix checkmark syntax on roadmap

gulpfile.js, src/actions/actions.ts
=> Enforce TSLint. Closes #456

package.json
I suppose @johnfn typed too fast :)
=> Fix wrong command for ctrl+f

extension.ts, src/mode/modeHandler.ts
With the newly API introduced in https://github.com/Microsoft/vscode/commit/70a083d54b2dd39220cd4d999dc1ee3c361d8936 , now we can handle CJK in all modes.
=> CJK in all modes

extension.ts
Cursor update was wrong if we don't pass correct filename into ModeHanlder initialization.
=> Turn around for cursor problem

ROADMAP.md, src/actions/actions.ts
Update Roadmap about Fold and add commands which are possible.
=> Correct Fold behavior and update roadmap

ROADMAP.md, src/actions/actions.ts, src/motion/position.ts
=> Move sections

test/mode/normalModeTests/motions.test.ts
As title. Since we still have test failure in local (those `god name` ones), sometimes we fail to realize our code change brings more failure.
=> Fix test regression

ROADMAP.md, src/actions/actions.ts, src/matching/tagMatcher.ts, test/mode/modeNormal.test.ts, test/mode/modeVisual.test.ts
=> Implement tag movements

src/actions/actions.ts
=> fix #639 visual block mode minor issues

src/mode/modeHandler.ts
fix #641 forgot to put that in the commit
ps: someday I will stop using the mouse...today is not the day
=> fix for extra character when double click mouse selection

ROADMAP.md, src/motion/position.ts
So people know they can turn it on/off.
=> Document autoindent option

README.md
Reorganize readme. Shifting away from specific `FAQ` inquiries to explanation of the VIM settings.
=> Add vim.* settings to readme. Fixes #503

src/actions/actions.ts, test/mode/modeNormal.test.ts
=> fixes #696

src/actions/actions.ts
=> fixes #718 A and I have cursor in right position now

test/mode/modeVisualBlock.test.ts
=> Visual block tests

README.md
minor, might want to change the way we do this for the future, especially since there is the extension contribution section now
=> fixes #750

gulpfile.js, package.json
* Remove gulp-filter
* Update gulp-tslint 5.0.0 => 6.1.1
* 2 space tabs to match rest of codebase
=> clean gulpfile

ROADMAP.md, src/cmd_line/commands/substitute.ts, src/cmd_line/lexer.ts, src/cmd_line/node.ts, src/cmd_line/parser.ts, src/cmd_line/token.ts, test/cmd_line/substitute.test.ts
Allow users to use Marks when they substitute.
=> Substitute marks

src/actions/actions.ts
=> fixes #759

src/actions/actions.ts
=> fixes #764

src/actions/actions.ts
=> fixes #740

README.md
=> Updated documentation for linux system clipboard use

src/cmd_line/subparser.ts
=> Fixes #817

.vscode/launch.json
=> Show debug console when session launches

src/mode/modeHandler.ts
=> fixes #832

src/mode/modeHandler.ts
=> fixes #882

src/actions/actions.ts, src/motion/position.ts
=> fixes #888

src/actions/actions.ts
=> fixes #652

src/mode/modeHandler.ts, src/register/register.ts
@rebornix 
Just a quick change to allow numbered registers for macros
also update the status bar to display what register you are recording to
=> Support num registers macros

src/actions/actions.ts
=> fixes #879

src/cmd_line/commands/quit.ts
=> make tab sequence feel right

extension.ts, src/mode/modeHandler.ts
=> stop revealing cursor when not necessary

src/actions/actions.ts
Add commands is `s` and `S` in visual block mode.
=> Add commands is `s` and `S` in visual block mode.

src/actions/actions.ts
=> fixes #878

test/mode/modeVisualLine.test.ts
=> Run all tests

src/number/numericString.ts
Our most requested feature is fixed now
=> fixes #663

src/actions/actions.ts, src/motion/position.ts
This just removes iterating over every character and instead iterates over lines. Still works with blank lines and partial lines as well.
=> Improved performance of visual block replace by a lot

ROADMAP.md
=> Update "r" for visual modes on roadmap

src/mode/modeHandler.ts
@rebornix @johnfn 
I git blamed this change and couldn't find a good reason for it being there
=> fixes #983

package.json, src/actions/actions.ts
=> fixes #1000 and a minor replace issue

package.json, src/actions/actions.ts, src/mode/modeHandler.ts
I think that this is pretty good...
@rebornix @johnfn
=> fix mouse clicking past EOL

src/actions/actions.ts, test/mode/modeVisualBlock.test.ts
=> Visual block fixes to cursor position and tests

src/configuration/configuration.ts
=> How can I fix travis failure

src/actions/actions.ts
=> fixes #1064

src/cmd_line/commands/file.ts
=> fixes #1035

src/actions/actions.ts, test/mode/modeVisual.test.ts
Some fixes for visual around matching brackets and parenthesis
=> fixes #1023

src/actions/actions.ts
=> fixes #1073

src/mode/modeHandler.ts
This seems like a simple enough mitigation?
=> fixes #1034

src/mode/remapper.ts
fix for mixing different length remappers (jj to esc AND q to esc would have had issues before)
=> fixes #1076

src/motion/position.ts
Minor cleanup with a debug print here
=> Removed debug print

ROADMAP.md
=> Update roadmap for ctrl-o

src/actions/actions.ts, src/motion/position.ts
=> Implement open file command - Issue #801

src/configuration/configuration.ts
=> avoid syncing style back to config

package.json, src/actions/actions.ts
=> Override home key (for pressing home in visual for example)

src/cmd_line/subparser.ts
=> Added more aliases for nohl

README.md
=> Update readme for easymotion

ROADMAP.md, src/actions/actions.ts, src/mode/modeHandler.ts, test/mode/modeVisual.test.ts
Let me know what you think, works on visual, visual line, and visual block selections
=> Reselect visual implemented (gv)

src/actions/actions.ts, test/mode/modeNormal.test.ts, test/mode/modeVisual.test.ts
=> fixes #1136

src/actions/actions.ts, test/mode/modeVisual.test.ts
Definitely helps that I have been adding tests for each one of these that gets closed...
=> Select inner vi( fix

README.md
#1181 
Quick documentation addition for insight on mapping leader bindings.
=> Adds documentation for adding leader bindings

src/mode/modeHandler.ts
Temporary workaround, not too bad though :)
=> fixes #1173

src/actions/actions.ts, src/register/register.ts
=> fixes #1214

README.md
Simple spelling mistake that was bothering me.
=> Fixes README spelling mistake

src/actions/actions.ts, src/easymotion/easymotion.ts
Pretty easy since we had gv setup already!
I like easymotion a lot, it is definitely some cool stuff, I just can't get myself to use it ever :(
=> fixes #1199 easymotion in visual mode

src/actions/actions.ts
=> fixes #1258

src/util.ts
=> fixes travis with minor hack used in tests

src/mode/modeHandler.ts
this stuff is super confusing...
visual block still has the issue, but atleast visual line and visual work correctly
=> fixes #1290, visual block still has the same issue though

test/mode/modeVisual.test.ts
=> Fix lint issue.

src/actions/actions.ts
=> Add ctrl-w q action to quit current window.

src/actions/actions.ts
=> fixes #1313

src/actions/actions.ts, src/motion/position.ts, test/mode/normalModeTests/motions.test.ts
- fixed gg
- removed duplicate position command for document begin as well
=> fixes #1320

package.json, src/actions/actions.ts, src/mode/modeHandler.ts
I think that this should really work across all platforms.
=> Fix clipboard copy

package.json
https://github.com/Microsoft/vscode-extension-vscode/issues/53
=> [WIP] fix travis due to double digit version numbers

src/actions/actions.ts
This is a funky one but o well, I think it is better here than somewhere else... What do you think?
=> fixes #1385 % motion with a count

src/actions/actions.ts, src/mode/modeHandler.ts
=> fixes #1382

src/actions/actions.ts
=> fixes #1448

package.json
It warns that array is expected, though object is the correct value.
Sorry, didn't run the tests. Is short of time.
=> Fix type suggestion for handleKeys object

ROADMAP.md
cleanup, formatting got messed up at some point..
=> Fix tables in roadmap

src/actions/actions.ts, src/easymotion/easymotion.ts
There has to be a regex for first non whitespace character on line but I couldn't figure it out...
=> fix easymotion j and k

src/actions/actions.ts, src/mode/modeHandler.ts, src/transformations/transformations.ts, test/mode/modeInsert.test.ts
Fixes #1122
@johnfn what do you think, looking for any ways to clean this up a bit
=> Add 5i= or 4a- so that the previously inserted text is repeated upon exiting to normal mode

src/configuration/configuration.ts
We need to handle ctrl+c separately, as vim.overrideCopy should override vim.useCtrlKeys. 
I plan on adding tests later today.
=> Fixed issue #1533

src/actions/actions.ts
=> Fix surround aliases

src/actions/actions.ts
Add Rust triple slash document comments to list of comment types.
=> fixes #1449

src/mode/modeHandler.ts
Update to the new and stable api for `workbench.colorCustomizations`
=> Fix status bar color when change mode

src/cmd_line/main.ts
I think this is an improvement, and in addition, it follows what vim does.
=> Made command line persistent when switching windows

src/textEditor.ts
=> fixed getLineMaxColumn

.vscode/launch.json, gulpfile.js, package.json
- Fix warning in package.json
- Remove useless task in gulp
- Rename tasks in `tasks.json` to something more descriptive
=> Fix warning

package.json, src/actions/actions.ts, src/cmd_line/commands/write.ts, src/cmd_line/lexer.ts, src/cmd_line/main.ts, src/cmd_line/subparsers/substitute.ts, src/cmd_line/subparsers/write.ts, src/cmd_line/subparsers/writequit.ts, src/configuration/configuration.ts, src/mode/modeHandler.ts, src/motion/position.ts, src/register/register.ts, test/testSimplifier.ts, tsconfig.json, tslint.json
=> Upgrade typescript 2.2.1->2.3.2. tslint 3.10.2->2.3.2. Fix errors

.vscode/launch.json
Fix: `breakpoint ignored because generated code not found (source map problem?)`
Need to use the glob pattern with the outFiles property in task.json
cc @Chillee
=> outfiles needs to be globbed

extension.ts, package.json, src/globals.ts, src/mode/modeHandler.ts
=> Toggle vim

src/actions/actions.ts, src/cmd_line/main.ts, src/matching/tagMatcher.ts, src/textEditor.ts, test/mode/modeNormal.test.ts
The only bug that isn't fixed right now (that I can tell), is dit on a tag that's empty (I added a jank experimental fix for cit for empty tags). Otherwise, I think this PR is in a pretty good place, and I'd love to hear about any more bugs. Specifically, I fixed the latter two bugs linked [here](https://github.com/VSCodeVim/Vim/pull/1454#issuecomment-296725399)
EDIT: I have now fixed all of the bugs I know of.
This is building off of work done by @jrenton in #1454.
=> Further work on tag matching (based off of #1454)

src/matching/tagMatcher.ts
=> Fixes #1360: Fixed bug with recently submitted tag PR

src/actions/actions.ts
=> Added #1637, #1638: z- and z<CR> movements

.travis.yml, src/error.ts, test/cmd_line/parser.test.ts, test/cmd_line/read.test.ts, test/cmd_line/writequit.test.ts, test/error.test.ts, test/extension.test.ts, test/index.ts, test/macro.test.ts, test/mode/modeHandler.test.ts, test/mode/modeNormal.test.ts, test/mode/modeVisualBlock.test.ts, test/mode/normalModeTests/dot.test.ts, test/operator/comment.test.ts, test/register/register.test.ts, test/testSimplifier.ts, test/testUtils.ts
* increase timeout to 10s
* change some `setup` to `suiteSetup`
* travis: `npm init` should also take care of doing `gulp` task
* made the `Error` test suite more useful
=> clean up tests. increase timeout

src/actions/operator.ts
Don't think this is everything, but it's a start.
=> Fixed some regressions I introduced

src/mode/remapper.ts
=> Fixes #1403: VisualBlock doesn't respect keybindings.

src/actions/commands/actions.ts, src/actions/motion.ts, src/state/searchState.ts, test/mode/modeVisual.test.ts, test/mode/modeVisualLine.test.ts
We just need to add another piece of state in searchState, that stores our previous mode.
I'll add some tests later.
=> Fixes #1520: search in visual/visualLine/visualBlock mode

package.json
Wow git is so hard. https://github.com/VSCodeVim/Vim/pull/1728
=> Actually readded <c-j> and <c-k>

package.json, src/actions/commands/insert.ts, test/mode/normalModeTests/motions.test.ts
We'll need to reopen #612.
But, us handling tab leads to autocompletion being broken. Ugh.
=> Fixes #1752: Tab Completion

extension.ts, package.json, src/actions/commands/actions.ts, src/actions/commands/insert.ts, src/cmd_line/main.ts, src/neovim/nvimUtil.ts, test/mode/normalModeTests/motions.test.ts
Fixes #1754, fixes #612, fixes #1756
=> Some patches for v0.8.0

src/textEditor.ts
https://github.com/VSCodeVim/Vim/issues/1027#issuecomment-303304153
Probably not though.
=> fixed #1027 maybe?

src/cmd_line/main.ts
=> Fixes #1826: Jump to line with neovim disabled doesn't work

src/actions/operator.ts, test/mode/modeNormal.test.ts
This was most likely for multicursor? It is hard to chase it back through git blame due to the refactor
=> Fix yiw cursor pos

src/mode/modeHandler.ts
??????
I have no idea why this works. I tried this fix as a bit of a hunch, and it seems to work fine.
@rebornix I would really appreciate if you had any idea what was going on here.
EDIT: As in, I don't know what is causing this, and I'd be really grateful if you could look into it.
=> Fixes #1827: Autocomplete fails when any lines are wrapped/folded

src/actions/commands/actions.ts, src/actions/commands/insert.ts, test/mode/modeInsert.test.ts
Still a bit weird but works for me
=> fixes #1843 A and I preceded by count

README.md
Updated key for adding new cursor from gc (now comment) to gb.
=> Update README.md (minor)

src/actions/commands/actions.ts, test/mode/normalModeTests/commands.test.ts
This just seems to be a dumb oversight.
=> Fixes #1857: P not creating an undo stop

src/mode/modeHandler.ts, test/mode/modeVisual.test.ts
=> Fixes #1886: indent repeat doesn't work in visual mode

test/register/repeatableMovement.test.ts
=> Renamed test to reflect purpose

src/actions/textobject.ts, test/mode/modeNormal.test.ts
=> Fixed iW on beginning of word (#1935)

package.json, src/actions/commands/actions.ts
=> Use Go To Def & history absent a tag stack.

README.md, package.json, src/configuration/configuration.ts, src/mode/modeHandler.ts
No performance impact with this since we are not changing the way we create cursors here
=> Fixes #2050 Allow custom cursor styles per mode

src/actions/commands/actions.ts
Removed code which does not get executed anymore due to change in #2062.
It removed this code before but I got a bit confused with the pull-request handling so I did not commit it in #2062. Sorry for the additional work.
=> removed code which is not needed anymore due to #2062

README.md, package.json, src/configuration/configuration.ts, src/mode/modeHandler.ts
Pretty straight forward... Not sure why showcmd wasn't working before, the configuration option was not used anywhere in the codebase
=> fixes #1576 and showcmd configuration option

test/mode/modeNormal.test.ts
I have added 5 unit tests to cover basic functionality for new commands `gi`, `` `. ``, and `'.` as well as covering `g;` and `g,` which were previously not covered. This is an extension to the work I did for #1824 and #1248.
=> Added unit tests for movement commands.

.vscode/launch.json, .vscode/tasks.json
* Enable running all `gulp` tasks through VS Code
* Run "gulp: default" to build.
=> fix vscode launch/tasks

test/mode/modeNormal.test.ts
=> fix(1673): re-enable some tests

src/mode/modeHandler.ts
- use map to translate cursor style
- remove unused context `vim.platform`
=> refactor(modehandler-updateview): use map and remove unused context

src/history/historyTracker.ts
Fairly simple fix for #2184. Opened an editor without any documents opened and confirmed error is gone.
=> fix(2184): handle situation when no document is opened

src/mode/modeHandler.ts
**What this PR does / why we need it**: Fixes regression with search string not appearing in the status bar.
**Which issue(s) this PR fixes**: Fixes #2261
=> fixes(2261): fix regression. show search string in status bar

extension.ts, src/mode/modeHandler.ts
**What this PR does / why we need it**: Regression from refactor. Need to refresh screen following a command line run. 
**Which issue(s) this PR fixes**: Fixes #2264
=> fix(2264): go-to-line

src/configuration/configuration.ts, src/mode/modeHandler.ts
**What this PR does / why we need it**: `handleKeys` config trumps `useCtrlKeys`
**Which issue(s) this PR fixes** Fixes #2162 
=> fix(2162): handleKeys was previously only handling negation

extension.ts
**What this PR does / why we need it**: This likely isn't solving the root of the problem. Temporary workaround.
**Which issue(s) this PR fixes**. #2273 
=> fix: no need to change cursor if there is no active editor. closes #2273

test/actions/base.test.ts
**What this PR does / why we need it**: Add UTs for compareKeyPressSequence
=> fix: add tests for compareKeyPressSequence

package.json
Add 'h', 'l' keybinding for sidebar.
'l' - expand folder/select file
'h' - fold folder
This PR closes: #2230
=> feature: "h", "l" keybindings for sidebar

src/cmd_line/commandLine.ts, src/cmd_line/commands/write.ts, src/mode/modeHandler.ts, src/statusBar.ts, test/configuration/notation.test.ts
**What this PR does / why we need it**: Takes into account if a macro is being recorded. If so, we need to update the status bar.
**Which issue(s) this PR fixes** #2296
=> fix: status bar not updating properly when recording macros. fixes #2296. 

src/configuration/configuration.ts
**Which issue(s) this PR fixes**: #2322 #2321
=> fix: bad jason. fix bad release. 

src/mode/modeHandler.ts, src/state/vimState.ts, test/actions/baseAction.test.ts, test/mode/modeNormal.test.ts, test/register/register.test.ts, test/testSimplifier.ts, test/testUtils.ts
**What this PR does / why we need it**: refactor vimState. No need to set current mode twice. Support x-plat for all tests. 
=> refactor: no need to set current mode twice

src/actions/commands/actions.ts
Added keybind [`<C-w>=`](http://vimdoc.sourceforge.net/htmldoc/windows.html#CTRL-W_=)
* https://github.com/VSCodeVim/Vim/issues/2379#issuecomment-365677806
=> feat: Added <C-w>= keybind

src/neovim/neovim.ts
=> neovim.ts: typo in log

README.md
**What this PR does / why we need it**: Add documentation about `xsel` dependency on Linux
**Which issue(s) this PR fixes**: #2071 
=> docs: add documentation for installing xsel. fixes #2071

src/actions/commands/actions.ts
In visual mode, pressing `*` or `#` searches using the current selection _only_ if `vim.visualstar` is true. Otherwise, it searches using the current word under the cursor.
#2469 
=> Respect vim.visualstar configuration (fixes #2469)

package-lock.json, package.json, src/actions/operator.ts
Upgrades  gulp-bump, gulp-git, gulp-typescript, prettier, typescript, vscode npm packages
=> chore(dep): upgrade gulp-bump, gulp-git, gulp-typescript, prettier, typescript, vscode

ROADMAP.md
=> Fix description in 🔢 % command

.travis.yml, gulpfile.js, package-lock.json, package.json, src/common/motion/position.ts
**Which issue(s) this PR fixes** https://github.com/VSCodeVim/Vim/issues/2598
=> fix: fail on ts transpile errors by setting noEmitOnErrors

src/actions/commands/actions.ts, src/mode/modeHandler.ts, src/state/searchState.ts, test/mode/modeNormal.test.ts, test/mode/modeVisual.test.ts
Vim's `gn` and `gN` command is so powerful.
It works in normal-mode, visual-mode, operator-pending-mode.
I implemented normal-mode and visual-mode.
~~But supporting operator-pending-mode seems a little bit difficult.~~
~~So this PR does not include it 😭~~
I made it to work in also operator-pending-mode! 😆 
~~This PR does not fix, but related to #1955~~
Fixes #1955
=> Implement gn,gN command

src/actions/commands/actions.ts, src/mode/modeHandler.ts, test/multicursor.test.ts
=> Fixes #2632

gulpfile.js, test/cmd_line/tab.test.ts, test/testUtils.ts
Fix problems of develop environment on Windows.
#2649 
#2650
=> Fix development problems on win

gulpfile.js, tslint.json
Before:
```
D:\Coding\Vim (master) (vim@0.12.0)
λ gulp
[00:08:33] Using gulpfile D:\Coding\Vim\gulpfile.js
[00:08:33] Starting 'prettier'...
[00:08:33] Starting 'tslint'...
[00:08:33] Starting 'compile'...
[00:08:33] Finished 'prettier' after 244 ms
Warning: The 'no-use-before-declare' rule requires type information.
[00:08:41] Finished 'tslint' after 7.98 s
[00:08:42] Finished 'compile' after 9.43 s
[00:08:42] Starting 'default'...
[00:08:42] Finished 'default' after 41 μs
```
After:
```
D:\Coding\Vim (fix_warning) (vim@0.12.0)
λ gulp
[00:28:00] Using gulpfile D:\Coding\Vim\gulpfile.js
[00:28:00] Starting 'prettier'...
[00:28:00] Starting 'tslint'...
[00:28:01] Starting 'compile'...
[00:28:02] Finished 'prettier' after 1.51 s
[00:28:08] Finished …
```
=> fix: fix 'no-use-before-declare' requires type information lint warning

README.md
Fixes bad description in README.
=> Fix vim-commentary description in README

extension.ts, package.json, src/actions/motion.ts, src/actions/plugins/easymotion/easymotion.ts, src/common/motion/position.ts, src/textEditor.ts, src/util/logger.ts, test/cmd_line/commandLineHistory.test.ts, test/testUtils.ts
This is instead of renovate bots attempt so that the fixes can be applied
https://github.com/VSCodeVim/Vim/pull/2687
=> Update prettier dependency

src/actions/commands/actions.ts, src/cmd_line/commands/file.ts, src/cmd_line/subparsers/file.ts
fix gf to be like issue #2683
#2683 
=> fix gf to be like issue #2683

test/cmd_line/tab.test.ts, test/mode/modeNormal.test.ts, test/mode/normalModeTests/dot.test.ts, test/mode/normalModeTests/matchingBracket.test.ts, test/mode/normalModeTests/motions.test.ts, test/multicursor.test.ts, test/operator/comment.test.ts, test/operator/put.test.ts, test/operator/shift.test.ts, test/plugins/easymotion.test.ts, test/plugins/sneak.test.ts, test/plugins/surround.test.ts
* Remove duplicate UTs
* Clean-up unused imports
=> fix: remove duplicate UT

README.md, extension.ts, package.json
* Use a more explicit configuration for logging Level instead of configuring a json object
* Add more logging to `extension.ts`
* Re-arrange event handlers in `extension.ts`
=> fix: use explicit configuration for logginglevel

package-lock.json, package.json, src/actions/commands/actions.ts
We added basic view information to the editor `editor.visibleRanges` in vscode, with which we can do some math to make Ctrl+D/U position correct.
#1348
It requires VSCode 1.22 at least so I updated the vscode dependency. Once we merge this RP and publish, users using VSCode prior to 1.22 will not get the update.
=> Fix #1348. ctrl+D/U correct position

README.md
**What this PR does / why we need it**: The previous code didn't work if you're pasting at the end of a line. Used a different solution to achieve the same thing without a bug. https://stackoverflow.com/a/5093286
**Which issue(s) this PR fixes**: Related to #2726
=> Update visualModeKeyBindingsNonRecursive example

src/configuration/remapper.ts
Add support for insertModeKeybindings to also apply to replace mode
#1472 
=> fix: closes #1472. insertModeKeyBindings apply to insert and replace modes

src/configuration/notation.ts, test/configuration/notation.test.ts
Enable mapping of `<enter>` key in addition to the `<cr>` support we had.
#2390 
=> fix: closes #2390. enables remapping using '<enter>' 

src/actions/commands/insert.ts
@Chillee I couldn't trace back your comment in the issue, but this should be a "harmless" change, anything simple I am missing here?
=> fixes #1980

src/configuration/remapper.ts
Fixes an issue where undefined arguments in user remappings would cause vscode to error out when running `executeCommand` API.
#2774 
I couldn't figure out a more elegant one-liner for doing this :(
=> fix: fixes bug where null arguments to vscode executecommand would fail

README.md
* Add emoji's to the readme
* Add link to changelog
* Make ToC collapsible
=> doc: emojify readme

CHANGELOG.md, package-lock.json, package.json
=> bump version

src/actions/commands/actions.ts, src/cmd_line/commands/tab.ts
=> Make gt work correctly like gT

src/actions/commands/actions.ts, src/mode/modes.ts, src/state/vimState.ts
This is a bit wacky as well but works well and greatly improves the functionality of history navigation
=> Add "cursor" to commandline entry

README.md, package.json, src/actions/plugins/sneak.ts, src/configuration/configuration.ts, src/configuration/iconfiguration.ts, test/testConfiguration.ts
=> Add config option for sneak to use smartcase and ignorecase

.vscode/launch.json
=> fix: don't run test when launching through vscode

README.md
=> docs: add section on debugging remappings

README.md, package.json, src/actions/motion.ts, src/actions/wrapping.ts, src/common/motion/position.ts, src/configuration/configuration.ts, src/configuration/iconfiguration.ts, test/configuration/configuration.test.ts, test/motionLineWrapping.test.ts, test/testConfiguration.ts
Adds support for whichwrap
http://vim.wikia.com/wiki/Automatically_wrap_left_and_right
#1211
I am new to VS Code extension development, typescript, and this codebase. I tried to match style/etc. to the existing code. Let me know what changes are needed.
=> Add whichwrap

src/cmd_line/commandLine.ts, test/testConfiguration.ts
`wrapKeys` is missing from the test configuration. Needed as I did a bad merge over in https://github.com/VSCodeVim/Vim/pull/2736.
https://github.com/VSCodeVim/Vim/issues/2868
=> fix: add missing wrapkeys to test configuration

src/neovim/neovim.ts
=> Improve error reporting with neovim commandline

src/actions/base.ts
Instead of a giant list, organize all actions into a map based on the action's relevant mode. On a test of 100 random mainly insert/normal-mode actions, we save about 0.2ms in trying to find the relevant action. 
Not significant, but still an improvement. Next step would be to implement a trie... but I don''t think this is the major cause of #2021 
#2021 
=> fix: use map to search for relevant actions. #2021

README.md
=> docs: clean-up readme

ROADMAP.md
Fix type in docs to improve docs.
NA
NA
=> Fix type in ROADMAP.md

extension.ts, src/cmd_line/commandLine.ts, src/editorIdentity.ts, src/mode/modeHandler.ts, src/mode/modeHandlerMap.ts, src/neovim/neovim.ts, src/state/vimState.ts, test/cmd_line/commandLineHistory.test.ts
- In an attempt to reduce start-up times, lazy load neovim.
https://github.com/VSCodeVim/Vim/issues/2947
=> Lazy Load Neovim

package-lock.json, src/mode/modeHandler.ts
When an action causes the cursor to move outside of the viewport, center it vertically in order to better mimic Vim's behavior.
Also, update `package-lock.json` to reflect the latest npm package updates.
Fixes #2960 
Thank you for this amazing extension!
P.S. The files in this project sure are long :)
=> Center cursor vertically on movement out of viewport

package-lock.json, src/mode/modeHandler.ts
=> Revert "Center cursor vertically on movement out of viewport"

package-lock.json, package.json
=> fix: add activationevent onCommand type. closes #3016

src/configuration/configuration.ts
usage:
```
:set relativenumber
:set norelativenumber
```
#3020 
=> fix: re-enable relativelinenumbers. closes #3020

package.json
=> fix `<C-f>` in 「Insert」mode

package-lock.json, package.json, src/actions/commands/actions.ts, src/cmd_line/commands/tab.ts
VSCode merged a fix to https://github.com/Microsoft/vscode/issues/55205 in  https://github.com/Microsoft/vscode/pull/56441
This cleans up the hacked implementation
=> Cleanup gt count command

src/mode/modeHandler.ts
=> Allow dot to repeat after doing any EasyMotion move

src/actions/commands/actions.ts, test/mode/modeNormal.test.ts
=> Minor C-a C-x fix

src/configuration/remapper.ts
This is a fix for issue #2752 
First pull request, let me know if I messed anything up. The issue was just that only the first cursor was being manipulated when using a remapped command in insert mode.
=> Fix for #2752

renovate.json, src/mode/modeHandler.ts, src/state/substituteState.ts, src/util/util.ts
Dear @renovate-bot,
We don't want to be bothered. Just automerge patch/minor versions.
K. Thanks. Bye.
=> fix: automerge renovate minor/patch

build/Dockerfile
It enables Ubuntu devs to run the tests from docker container
Issue #3168 
It would be nice to test this on other than ubuntu OS.
=> Issue #3168 - Ubuntu tests

CHANGELOG.md, package-lock.json, package.json
=> v0.16.13 -> v0.16.14

src/cmd_line/subparser.ts, src/util/vscode-context.ts
Add `on` as alias for `only`
https://github.com/VSCodeVim/Vim/issues/3286
=> feat: add on as alias for only

src/statusBar.ts
`object.assign` first argument is the target, so we were re-writing it. Therefore the comparison would always be equal. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign
https://github.com/VSCodeVim/Vim/issues/3316
=> fix: closes #3316

package-lock.json, package.json, src/cmd_line/commandLine.ts, src/neovim/neovim.ts, src/state/vimState.ts
Tested with both 0.3.1 and 0.3.3 and both work with the commands I tested (:sort mostly)
=> Update to new neovim node library

src/common/motion/position.ts, src/mode/modeHandler.ts
Check if the texteditor is still open before we update any further state. 
#3331 
=> fix: dont update cursors if editor has been close. closes #3331

src/cmd_line/commands/setoptions.ts
=> Move setoptions querying to status bar

README.md
No longer a MSFT employee => no more free azure. http://vscodevim.herokuapp.com/
Fixes https://github.com/VSCodeVim/Vim/issues/3370
=> docs: change slackin host

extension.ts, src/actions/commands/actions.ts, src/actions/commands/insert.ts, src/actions/motion.ts, src/actions/operator.ts, src/actions/textobject.ts, src/cmd_line/commands/deleteRange.ts, src/cmd_line/commands/read.ts, src/cmd_line/commands/sort.ts, src/cmd_line/commands/substitute.ts, src/cmd_line/node.ts, src/register/register.ts, src/state/globalState.ts, src/util/clipboard.ts, tslint.json
=> Misc async fixes - new revision

extension.ts, src/actions/motion.ts, src/actions/plugins/sneak.ts, src/state/globalState.ts, src/state/vimState.ts
* didn't see a reason for `last(semicolon/comma)repeatablemovement` to be static properties. made them normal properties to align with the rest of the class
* made globalstate a singleton class instead of littering statics everywhere. 
=> refactor: make globalstate singleton class

gulpfile.js
* Not sure how we managed to push a release (v1.0.4) that wasn't built from master considering the PR looked good (https://github.com/VSCodeVim/Vim/pull/3427), and the `gulp release` script was used to generate said PR and tag.
* To help prevent this, adding a `version` in our `/out` which contains the commit hash of the version of code used to build. 
#3429 
=> feat: output commit hash. closes #3429

src/configuration/configuration.ts, src/configuration/configurationValidator.ts, src/configuration/remapper.ts
* validate that remappings should be string arrays. 
* issue discovered while investigating #2233 
#2233 
=> fix: validate that remappings are string arrays

src/actions/commands/actions.ts, src/actions/commands/insert.ts, src/actions/motion.ts, src/cmd_line/node.ts, src/common/motion/position.ts, src/mode/modeHandler.ts, src/textEditor.ts, test/testSimplifier.ts
* ugh, annoying how many different ways there were to create a `Position` object.
=> refactor: no need for so many different ways to create a position object

src/mode/modeHandler.ts, src/state/vimState.ts, test/state/vimState.test.ts
* No need to iterate the cursor list twice.
=> fix: de-dupe cursors

src/actions/commands/actions.ts, src/actions/operator.ts, test/mode/modeVisual.test.ts, test/mode/modeVisualLine.test.ts
In visual mode, makes `gu` equivalent to `u` and `gU` equivalent to `U`, as is the case in vim.
#3491
=> Support for gU and gu in visual mode

ROADMAP.md
The roadmap seems to be a bit out of date. I've updated it to include several features I've noticed have been implemented but are still listed as unimplemented. No guarantees I didn't miss anything.
N/A
=> Mark several features that have been implemented as complete in ROADMAP.md

package.json, src/actions/commands/actions.ts, src/cmd_line/commands/fileInfo.ts, src/cmd_line/subparser.ts, src/cmd_line/subparsers/fileInfo.ts, src/util/statusBarTextUtils.ts
These both show the file name, line count, and relative position in the status bar.
Fixes #3700
=> Implement Ctrl+G and :file

src/actions/commands/actions.ts, src/state/globalState.ts, test/mode/normalModeTests/motions.test.ts
`*` and `#` add to the search history in vim
Fixes #3031
=> Add searches from * and # to the search history

src/actions/commands/actions.ts
Hitting `<BS>` on an empty command line should close it and return to normal mode.
Fixes #3729
=> Return to normal mode after hitting <BS> on empty command line

ROADMAP.md
Possibly there's a reason there are multiple entries, lmk if so
Separately: `ROADMAP.md` is the most helpful guide for keys, but I didn't originally expect to find the best docs in the Roadmap. If this was in the main docs / readme / better named, I would have found it more easily
=> Consolidate documentation for visual modes

src/actions/commands/actions.ts, src/util/path.ts
=> fix: fix build break

package.json
Updates the link in the description field for the `autoSwitchInputMethod` setting, and adds a missing space before it.
=> chore: fix URL for input method setting

src/configuration/validators/neovimValidator.ts
Allows setting `nvim` as the path to Neovim.
#3754
=> Fixes #3754. Don't require full path to neovim

package.json
Maybe this will raise awareness and focus the discussion of other performance issues.
=> Be clear in package.json that vim.statusBarColorControl reduces performance

src/configuration/configuration.ts
Fix console warning
fixes #3926
=> Fix console warning

src/cmd_line/commands/sort.ts, test/cmd_line/sort.test.ts
Fixes sorting when not ignoring case, see #3939
=> Fix case sensitive sorting

src/actions/operator.ts, test/mode/modeNormal.test.ts
fixes #4024
This makes the change operator behave linewise when appropriate. e.g. `cj` and `ck` delete the entire start and end line.
#4024
=> linewise change operator

src/actions/commands/actions.ts
This PR fixes the issue where <C-v> doesn't respect the cursor in search mode
Fixed #4044
=> <C-v> doesn't respect the cursor in search mode

test/cmd_line/command.test.ts
=> Tests for special keys on the command line

src/actions/motion.ts, test/mode/modeVisual.test.ts
=> Adding backspace motion in visual mode

test/cmd_line/substitute.test.ts, test/macro.test.ts, test/mode/modeInsert.test.ts, test/mode/modeNormal.test.ts, test/mode/modeReplace.test.ts, test/mode/modeVisual.test.ts, test/mode/modeVisualBlock.test.ts, test/mode/modeVisualLine.test.ts, test/mode/normalModeTests/commands.test.ts, test/mode/normalModeTests/dot.test.ts, test/mode/normalModeTests/matchingBracket.test.ts, test/mode/normalModeTests/motions.test.ts, test/motionLineWrapping.test.ts, test/operator/comment.test.ts, test/operator/format.test.ts, test/operator/put.test.ts, test/operator/shift.test.ts, test/plugins/easymotion.test.ts, test/plugins/sneak.test.ts, test/plugins/surround.test.ts, test/register/register.test.ts, test/register/repeatableMovement.test.ts, test/testSimplifier.ts
It would be nice to add tests that can be skipped until future support
for the specified behaviour can be implemented.
=> Make it possible to add skipped tests

package.json, src/actions/commands/actions.ts, src/actions/motion.ts, src/actions/operator.ts, src/common/motion/position.ts, src/configuration/configuration.ts, src/configuration/iconfiguration.ts, src/state/replaceState.ts, test/mode/modeNormal.test.ts, test/mode/modeVisual.test.ts, test/mode/normalModeTests/motions.test.ts, test/testConfiguration.ts
Also, refactor <C-d> for the sake of DRY and a bit of cleanup.
Fixes #4137
=> Implement `startofline`

package.json, src/actions/operator.ts, src/configuration/configuration.ts, src/configuration/decoration.ts, src/configuration/iconfiguration.ts, test/testConfiguration.ts
=> Add configuration for highlight/yank highlight text colors

package-lock.json, package.json
Added in https://github.com/VSCodeVim/Vim/pull/3908 and in weird state in npm
=> Remove fs unused dependency

package.json
Changes the default value in settings.json for `vim.vimrc.enable` to false.
#4419 
=> Change default value of experimental vimrc support to a boolean

src/mode/modeHandler.ts, src/state/vimState.ts
=> Center the viewport around the cursor if the previous action moved the cursor at least 15 lines off screen

src/actions/base.ts, src/actions/baseMotion.ts, src/actions/commands/actions.ts, src/actions/motion.ts, src/actions/operator.ts, src/actions/plugins/easymotion/easymotion.cmd.ts, src/actions/plugins/surround.ts, src/common/motion/position.ts, src/common/number/numericString.ts, src/configuration/notation.ts, src/mode/modeHandler.ts, src/state/vimState.ts, src/util/util.ts, test/number/numericString.test.ts
=> A whole bunch of small refactors

src/actions/commands/actions.ts, test/mode/modeVisualBlock.test.ts
=> Fix `X` in visual block mode

README.md
Changes a bit the phrasing of how to get to the `Contributions` tab. Making it because it took me a bit to understand how to open that page and others might do the same in the future, especially people new to vscode
None of opened issues
=> Add documentation details about contributions page

src/actions/commands/actions.ts, test/mode/modeVisualBlock.test.ts
Register selection using " is not working in visual block mode, so fixed it to work.
Fixes #4038
Fixes #4192
=> Fix selecting register using " not working in visual block mode

src/mode/modeHandler.ts
=> Code shrinking

src/mode/modeHandler.ts, test/multicursor.test.ts
This PR fixes the multicursor inner motions (`iw`, `ib` etc.). Now they execute correctly and keep all cursors alive.
Fixes #4206
=> Fix inner motions cancel multicursors

test/macro.test.ts
After the PR #4830 I found weird that none of the tests captured the issue #4827.
After looking up the tests I found that there were no macro tests that handled multiple lines on same macro (like what happens on that issue) so decided to create a new test to prevent future issues like that one.
=> Add test to macros to prevent issues like #4827

package.json
**Note: this PR is a proposal. Please read the caveats below about remote development. Would love to hear thoughts.**
I'm running WSL on Windows. When I try to use Neovim, VSCodeVim can't find it. This change prefers having me install the extension on WSL instead, where it can find my copy of Neovim and everything is great.
I frustratingly ran into #4614 and did a bunch of research on how to resolve this. I believe this is the most straightforward approach. The fact that this extension is trying to spawn a process using a file means that it (I think?) it's unequivocally a workspace extension. See https://code.visualstudio.com/api/advanced-topics/remote-extensions#architecture-and-extension-kinds and let me know if you agree. Looking at [the original …
=> Swap workspace and ui in extensionKind to enable WSL neovim use

src/actions/commands/actions.ts, src/cmd_line/commands/undo.ts, src/cmd_line/subparser.ts, test/cmd_line/undo.test.ts
This PR implements the :u[ndo] command (a requested feature which is available in Vim)
Issue #3197 
First contribution, so very open to feedback/suggestions! Also I will continue to work on the undo command to add the :undo n argument to undo n number of steps.
=> fixes issue #3197: Adding :u[ndo] cmd and appropriate test

src/actions/commands/actions.ts, test/mode/normalModeTests/commands.test.ts
The `gJ` command with count did not work expectedly.
Fixes #2207
=> Fix `[count]gJ`

src/actions/commands/actions.ts, test/mode/modeVisual.test.ts, test/mode/modeVisualBlock.test.ts, test/mode/modeVisualLine.test.ts
`gJ` command is not working expectedly in visual mode and is not implemented in visual line/block mode.
`gJ` is correctly implemented in #5014, so it's now available in visual mode as well.
Fixes #5027
=> Support `gJ` in visual modes

src/cmd_line/commands/bang.ts
Small addendum to #4989: the bang command should be neovim capable :)
N/A
N/A
=> Enable neovim capability for bang command

package.json, src/configuration/configuration.ts, src/configuration/iconfiguration.ts, src/state/vimState.ts, test/testConfiguration.ts
Adds support for `smartRelativeLine` which basically toggles VSCode's lineNumbers between `on` and `relative` depending on insert mode.
https://github.com/VSCodeVim/Vim/issues/3020
=> Add support for smartRelativeLine

README.md
=> Fix key binding typo in README

ROADMAP.md
Fix misspelling of will.
**What this PR does / why we need it**: Fixes a misspelling in ROADMAP.md.
**Which issue(s) this PR fixes**: Fixes a misspelling in ROADMAP.md.
=> Update ROADMAP.md Spelling

src/actions/operator.ts
Thanks for reviewing and merging #5892!  I was just getting #5895 ready for review, and I noticed some leftover debugging statements made it into #5892. Very sorry about this!
=> Remove stray console.log statements

src/state/searchState.ts
=> no look behind for safari

src/cmd_line/subparsers/substitute.ts, test/cmd_line/substitute.test.ts
substitute string to backslashes properly without neovim integration.
#2710 
This is my first PR to OSS. I'm going to follow the contributing guide, if there is any inconvenience, please tell me what to do. thx!
=> Bugfix substitute with backslash(fixes #2710)

README.md
This PR improves documentation for all the modes used by vim (for example visual, normal, replace).
Fixes #5273
=> Added documentation for all Vim Modes

ROADMAP.md
This PR changes `ROADMAP.md` to fix a typo.
**Which issue(s) this PR fixes**:.
**Special notes for your reviewer**:.
=> fix ROADMAP.md typo

src/vimscript/pattern.ts, test/cmd_line/substitute.test.ts, test/mode/modeNormal.test.ts
it implements `\%V` in search.
substitution will come in later (maybe in this PR). **Edit:** substitution works out-of-the-box.
fixes #4936 
=> search operator `\%V`

src/textobject/textobject.ts, test/mode/modeNormal.test.ts
This PR fixed text objects such as iw and aw to behave like vim.
When a textobject such as iw or aw is entered and its position is on an empty line, 
* aw(W) will select to the end of the next word.
* iw(W) will select up to the next word.
#6418
=> add sentence when currentChar is undefined

extension.ts, extensionBase.ts, package.json
Fixes https://github.com/VSCodeVim/Vim/issues/7469
=> Fix extension for web

syntaxes/vimrc.tmLanguage.json
Support syntax hightlight for command_id which contains number, hyphen and underscore
#7618 
- Before This PR:
- After This PR:
Thanks for reviewing this PR!
=> Vimrc: support syntax hightlight for command_id which contains number, hyphen and underscore

README.md
Fix broken fenced code blocks in the README
- Before
- After
=> [Docs] fix broken fenced code blocks in the README

extensionBase.ts
Fix for #7357 not only started setting # register but also added
additional call to file jump handling that broke the jump list. So,
still set # register if activeTextEditor is undefined, but skip the
extra task.
Fixes #7825.
Fixes a jump list regression (#7825) caused by #7357.
#7825 
Since I've done zero VsCode/Typescript/JS development before today, I can't tell you why this was the problem, only that the fix seems to work.
=> Fix the jump list (#7825)

package.json, src/actions/commands/scroll.ts, src/actions/motion.ts, src/actions/operator.ts, src/cmd_line/commands/breakpoints.ts, test/historyTracker.test.ts, test/testUtils.ts, yarn.lock
This is needed to support some requested features, e.g. #7687 
=> fixes for vscode 1.67.0

src/textobject/textobject.ts
**What this PR does / why we need it**: This PR enables indent text objects in VisualLine mode.
**Which issue(s) this PR fixes** Fixes #8048
**Special notes for your reviewer**: Fairly simple fix - I expected it to be much more work! Credit to the codebase and its maintainers 🙏
=> Support indent objects in visual line mode

src/actions/motion.ts, test/mode/normalModeTests/motions.test.ts
fixes special case for hadling `{`, when there are no characters before it in the same line.
fixes #2982
=> special treatment for {

package.json
Fixes a typo on `vim.targets.enable` description
=> fix: correct typo on vim.targets.enable desc

extensionBase.ts, package.json, src/actions/base.ts, src/actions/commands/actions.ts, src/actions/commands/commandLine.ts, src/actions/operator.ts, src/actions/types.d.ts, src/cmd_line/commandLine.ts, src/configuration/configuration.ts, src/configuration/vimrc.ts, src/register/register.ts, webpack.config.js, yarn.lock
What this PR does / why we need it:
This PR removes all the remaining dependency cycles and adds circular-dependency-plugin to prevent backslide.
Which issue(s) this PR fixes
#6177
=> Fix the remaining dependency cycles.

src/vimscript/lineRange.ts, test/vimscript/exCommandParse.test.ts, test/vimscript/lineRangeParse.test.ts
This PR makes the line range with an empty start number like the one below;
```
:,3d     // this deletes from the current line to the 3rd line
```
#8083 
=> fix #8083 - support the line range with no start line

.github/CONTRIBUTING.md
Update install prerequisites: Nodejs v16.x from v14.0.0
Prevent yarn install error due to nodejs v14 environment installed by this doc.
```
$ yarn install
...
error @vscodetest-electron@2.2.3 The engine node is incompatible with this module. Expected version =16. Got 14.21.3
...
```
=> Update install prerequisites: Nodejs v16.x

src/actions/commands/scroll.ts
Super simple PR, there was a simple mistake when using `vimState.actionCount` to multiply the amount of scroll actions to do.
Fixes: #8095
I've noticed that there aren't any tests that go through this specific functionality. Let me know if you'd like one written up.
=> fixes #8095 now can scroll with vimState.recordedState.count

README.md
Adds some docs about the affinity setting, which can enhance the performance of VSCodeVim, and could be beneficial to many users.
The setting has been praised [here](https://github.com/VSCodeVim/Vim/issues/7606) and [here](https://github.com/microsoft/vscode/issues/75627#issuecomment-1078827311).
#7606
I wanted to display this near the top of the README, because I think many people may want to consider this setting. But I put more detailed documentation lower down, in the F.A.Q.
=> Document the affinity setting for improved performance

src/actions/commands/actions.ts
Jump relative to project root with `gf`.
Closes #1940
=> feat: gf relative to project root

src/actions/commands/actions.ts, src/cmd_line/commands/file.ts
Fixed `gf` with line number was not working.
=> fix: gf to jump with line number

src/cmd_line/commands/tab.ts
make `tabedit` work with relative path (like the `:e <path>` does)
#4730
=> make `tabedit` work with relative path, fix #4730

src/actions/commands/actions.ts, src/cmd_line/commands/tab.ts, src/error.ts, src/vimscript/exCommandParser.ts, test/vimscript/exCommandParse.test.ts
Supports `:b[uffer] {bufname}`. See `:b[uffer]` https://vimhelp.org/windows.txt.html#windows.txt
#9154
=> Support :b[uffer] {bufname}

CHANGELOG.md
=> fix(changelog): typo on the 1.29.2 version number

README.md
Update the README about VSCodeVIm's full settings, the tab name changed from VSCode.
=> Update README about settings

ROADMAP.ZH.md
fix a missing translation in ROADMAP.ZH.md
=> fix: add missing translation

README.md
- Document how to enable key-repeating for Windsurf
- None - but maybe some will be prevented in the future :)
- https://windsurf.com/editor
=> Document enable key-repeating for Windsurf

README.md
Cursor manually vets requires a link to the openvsx marketplace be placed alongside links to other marketplaces
https://cursor.com/docs/configuration/extensions#publisher-verification
#9773
None
=> Add a link to the OpenVSX marketplace.

src/cmd_line/commands/write.ts
Fixes https://github.com/VSCodeVim/Vim/issues/9697
=> disable preview on save
